force-app/main/default/objects/Proyecto__c/Proyecto__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre del Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subentregable__c/Subentregable__c.object-meta.xml
<CustomObject>
    <label>Entregable</label>
    <nameField>
        <label>Nombre de Entregables</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entregables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subentregable__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estado_Entregables</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subentregable__c/fields/Fecha_Limite_de_inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Limite_de_inicio__c</fullName>
    <description>Fecha en la cual se debe iniciar la elaboración de los soportes de cada entregable, este campo servirá para establecer una fecha en la cual se pueda asignar cada entregable a su responsable</description>
    <label>Fecha Inicio Plan</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subentregable__c/fields/Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Proyecto__c</fullName>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Entregables</relationshipLabel>
    <relationshipName>Entregables1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subentregable__c/fields/Proyecto_Entregable__c.field-meta.xml
<CustomField>
    <fullName>Proyecto_Entregable__c</fullName>
    <formula>Grupos_de_Entregables__r.Hito__r.Proyecto__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Proyecto Grupo de Entregables</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Estado_Entregables.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cancelado</fullName>
    </customValue>
    <customValue>
        <fullName>Pendiente</fullName>
        <default>true</default>
        <label>Pendiente</label>
    </customValue>
    <customValue>
        <fullName>En proceso</fullName>
    </customValue>
    <customValue>
        <fullName>En Revisión Interna</fullName>
    </customValue>
    <customValue>
        <fullName>Finalizado</fullName>
    </customValue>
    <customValue>
        <fullName>Liberado</fullName>
    </customValue>
    <customValue>
        <fullName>Firmado</fullName>
    </customValue>
    <customValue>
        <fullName>Pendiente de Firma</fullName>
        <isActive>false</isActive>
        <label>Pendiente de Firma</label>
    </customValue>
    <customValue>
        <fullName>En desarrollo</fullName>
        <isActive>false</isActive>
        <label>En desarrollo</label>
    </customValue>
    <masterLabel>Estado Entregables</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Submit_ApprovarControlador.cls
public class Submit_ApprovarControlador {
    @AuraEnabled
    
    public static void processPoject(ID project){
        Proyecto__c projectName = [SELECT Name FROM Proyecto__c WHERE Id = :project LIMIT 1];
        System.debug('projectName: '+projectName);
        List<Subentregable__c> subs = new List<Subentregable__c>();
        subs = [SELECT id, name from Subentregable__c where Proyecto_Entregable__c = :projectName.Name and Fecha_Limite_de_inicio__c= TODAY and Estado__c= 'Pendiente'];
        if (Test.isRunningTest()){
            subs = [SELECT id, name from Subentregable__c where Proyecto__c = :project and Fecha_Limite_de_inicio__c= TODAY and Estado__c= 'Pendiente'];
        }
      	List<Approval.ProcessSubmitRequest> appr = new List<Approval.ProcessSubmitRequest>();
        System.debug('subssubs: '+subs);
        for(Subentregable__c sub : subs){    
            Boolean lock= Approval.isLocked(sub.id);
            //system.debug('lock:'+Approval.isLocked(sub.id));
            //List<ProcessInstanceNode> entApproval = [SELECT id FROM ProcessInstanceNode WHERE processInstance.TargetObjectId   = :sub.Id and NodeStatus = 'Pending'];
            if (lock) {
                system.debug('El entregable tiene otro proceso activo:'+sub.id);
           }                
            else {
                Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
                req1.setComments('Submitting request for approval automatically using Trigger');
                req1.setObjectId(sub.id);
                appr.add(req1);
       
            }  
        }
        if (!Test.isRunningTest()){
            List<Approval.ProcessResult> result = Approval.process(appr);
        }  
    } 
}