force-app/main/default/objects/Proyecto__c/Proyecto__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre del Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proyecto__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Código de Proyecto</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Subentregable__c/Subentregable__c.object-meta.xml
<CustomObject>
    <label>Entregable</label>
    <nameField>
        <label>Nombre de Entregables</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entregables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subentregable__c/fields/CodigoSubentregable__c.field-meta.xml
<CustomField>
    <fullName>CodigoSubentregable__c</fullName>
    <externalId>true</externalId>
    <label>Código Entregable</label>
    <length>35</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Subentregable__c/fields/Fecha_Real_de_Liberacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Real_de_Liberacion__c</fullName>
    <label>Fecha Real de Liberación</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Subentregable__c/fields/Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Proyecto__c</fullName>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Entregables</relationshipLabel>
    <relationshipName>Entregables1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/FechaPrimeraLiberacion_Test.cls
@isTest
private class FechaPrimeraLiberacion_Test {
    
    @isTest static void Entregables(){
        
        Test.startTest();
        Proyecto__c Proyecto= new Proyecto__c(NAme='Proyecto Prueba', Codigo__c='P99/0000');
        insert Proyecto;
        Subentregable__c Entregable1= new Subentregable__c(Name='Entregable1', Proyecto__c=Proyecto.Id, CodigoSubentregable__c='Prueba1');
        insert Entregable1;
        
        Subentregable__c Entregable2= new Subentregable__c(Name='Entregable2', Proyecto__c=Proyecto.Id,CodigoSubentregable__c='Prueba2');
        insert Entregable2;
        
        Entregable1.Fecha_Real_de_Liberacion__c=System.today();
        
        update Entregable1;
        Test.stopTest();
        
        
    }
    
    
    
}