force-app/main/default/objects/No_ejecutar_triggers__c/No_ejecutar_triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>No ejecutar triggers</label>
</CustomObject>

force-app/main/default/objects/No_ejecutar_triggers__c/fields/Correo_usuario__c.field-meta.xml
<CustomField>
    <fullName>Correo_usuario__c</fullName>
    <label>Correo usuario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bloqueo_por_aprobacion__c.field-meta.xml
<CustomField>
    <fullName>Bloqueo_por_aprobacion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bloqueo por aprobación</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Engineering.recordType-meta.xml
<RecordType>
    <fullName>Engineering</fullName>
    <active>true</active>
    <businessProcess>Engineering</businessProcess>
    <label>Engineering</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Ingenier_a.recordType-meta.xml
<RecordType>
    <fullName>Ingenier_a</fullName>
    <active>true</active>
    <businessProcess>Ingeniería</businessProcess>
    <label>Ingeniería</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/IT_DS.recordType-meta.xml
<RecordType>
    <fullName>IT_DS</fullName>
    <active>true</active>
    <businessProcess>IT%26DS</businessProcess>
    <label>IT&amp;DS</label>
</RecordType>

force-app/main/default/objects/Parametrica_2__c/Parametrica_2__c.object-meta.xml
<CustomObject>
    <description>Parametrica que contiene los datos de Ibermatica</description>
    <label>Parametrica Ibermática</label>
    <nameField>
        <label>Nombre de Parametrica Ibermática</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parametricas Ibermática</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parametrica_2__c/fields/CPV__c.field-meta.xml
<CustomField>
    <fullName>CPV__c</fullName>
    <label>CPV</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Descripcion_CPV__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_CPV__c</fullName>
    <label>Descripción CPV</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/recordTypes/CPV.recordType-meta.xml
<RecordType>
    <fullName>CPV</fullName>
    <active>true</active>
    <label>CPV</label>
</RecordType>

force-app/main/default/classes/CRM_IB_CPVControllerTest.cls
@IsTest
public class CRM_IB_CPVControllerTest {

    @IsTest
    static void testValoresCPV() {
        
        //datos de pruebas
        Parametrica_2__c param1 = new Parametrica_2__c(
            Name = 'CPV',
            CPV__c = '30000000-1',
            Descripcion_CPV__c = 'CPV prueba 1',
            RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'CPV' LIMIT 1].Id
        );
        insert param1;
        system.debug('param1: '+param1);

        Parametrica_2__c param2 = new Parametrica_2__c(
            Name = 'CPV',
            CPV__c = '30000000-2',
            Descripcion_CPV__c = 'CPV prueba 2',
            RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'CPV' LIMIT 1].Id
        );
        insert param2;
        system.debug('param2: '+param2);
        
        No_ejecutar_triggers__c saltar_trigger = new No_ejecutar_triggers__c();
        saltar_trigger.Correo_usuario__c='';
        insert saltar_trigger;

        Opportunity opp = TestDataFactory.createOpportunity('Cualificación', 'Digital impact','IT_DS');
        opp.CPV_varios__c = '30000000-3 (CPV prueba 3);30000000-4 (CPV prueba 4)';
        update opp;
        

        // llamada al método valoresCPV
        Test.startTest();
        Map<String, Object> result = CRM_IB_CPVController.valoresCPV(opp.Id);
        Test.stopTest();

        // validación de datos
        List<String> opciones = (List<String>) result.get('opciones');
        List<String> valoresSeleccionados = (List<String>) result.get('valoresSeleccionados');

        System.assertEquals(2, opciones.size(), 'Debe haber 2 opciones disponibles.');
        System.assert(opciones.contains('30000000-1 (CPV prueba 1)'), 'La opción "30000000-1 (CPV prueba 1)" debería estar disponible.');
        System.assert(opciones.contains('30000000-2 (CPV prueba 2)'), 'La opción "30000000-2 (CPV prueba 2)" debería estar disponible.');

        System.assertEquals(2, valoresSeleccionados.size(), 'Debe haber 2 valores seleccionados.');
        System.assert(valoresSeleccionados.contains('30000000-3 (CPV prueba 3)'), 'El valor "30000000-3 (CPV prueba 3)" debería estar seleccionado.');
        System.assert(valoresSeleccionados.contains('30000000-4 (CPV prueba 4)'), 'El valor "30000000-4 (CPV prueba 4)" debería estar seleccionado.');
    }

    @IsTest
    static void testSaveOportunidadCPV() {
        
        //datos de prueba
        Parametrica_2__c param1 = new Parametrica_2__c(
            Name = 'CPV',
            CPV__c = '30000000-1',
            Descripcion_CPV__c = 'CPV prueba 1',
            RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'CPV' LIMIT 1].Id
        );
        insert param1;
        system.debug('param1: '+param1);
       
        No_ejecutar_triggers__c saltar_trigger = new No_ejecutar_triggers__c();
        saltar_trigger.Correo_usuario__c='';
        insert saltar_trigger;

        Opportunity opp = TestDataFactory.createOpportunity('Cualificación', 'Engineering Design & Architecture','Ingenier_a');
        opp.CPV_varios__c = '';
        opp.Bloqueo_por_aprobacion__c = True;
        update opp;

        // nueva selección de CPV
        String nuevaSeleccion = '30000000-2 (CPV prueba 2)';

        // llamada al método saveOportunidad_CPV
        Test.startTest();
        CRM_IB_CPVController.saveOportunidad_CPV(opp.Id, nuevaSeleccion);
        CRM_IB_CPVController.oportunidadBloqueada(opp.Id);
        Test.stopTest();

        // comprobción de datos
        Opportunity oppActualizada = [SELECT CPV_varios__c FROM Opportunity WHERE Id = :opp.Id LIMIT 1];
        System.assertEquals(nuevaSeleccion, oppActualizada.CPV_varios__c, 'El campo CPV_varios__c debería haberse actualizado con la nueva selección.');
    }
}