force-app/main/default/objects/No_ejecutar_triggers__c/No_ejecutar_triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>No ejecutar triggers</label>
</CustomObject>

force-app/main/default/objects/No_ejecutar_triggers__c/fields/Correo_usuario__c.field-meta.xml
<CustomField>
    <fullName>Correo_usuario__c</fullName>
    <label>Correo usuario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Correo_Oferta_enviado__c.field-meta.xml
<CustomField>
    <fullName>Correo_Oferta_enviado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>¿Correo Oferta enviado?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Engineering.recordType-meta.xml
<RecordType>
    <fullName>Engineering</fullName>
    <active>true</active>
    <businessProcess>Engineering</businessProcess>
    <label>Engineering</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Ingenier_a.recordType-meta.xml
<RecordType>
    <fullName>Ingenier_a</fullName>
    <active>true</active>
    <businessProcess>Ingeniería</businessProcess>
    <label>Ingeniería</label>
</RecordType>

force-app/main/default/classes/Codigo_Oferta_Ingenieria_ControllerTest.cls
@isTest
public class Codigo_Oferta_Ingenieria_ControllerTest {
    
    @testSetup 
    static void setup() {
        No_ejecutar_triggers__c saltar_trigger = new No_ejecutar_triggers__c();
        saltar_trigger.Correo_usuario__c='';
        insert saltar_trigger;
    }
 
    @isTest 
    static void test_enviarCorreoOferta() { 

        // Test data setup
        Opportunity oports = TestDataFactory.createOpportunity('Cualificación', 'Engineering Design & Architecture','Ingenier_a');
        
        // Perform test
        Test.startTest();  
        String resultStr = Codigo_Oferta_Ingenieria_Controller.enviarCorreoOferta(oports.Id);
        Test.stopTest();
        
        System.debug('test_enviarCorreoOferta  - resultado: ' + resultStr);
        System.assertEquals('OK', resultStr, 'El resultado debe ser OK tras enviar correo');
        
        Opportunity oppActualizada = [SELECT Correo_Oferta_enviado__c FROM Opportunity WHERE Id = :oports.Id];
        System.assertEquals(true, oppActualizada.Correo_Oferta_enviado__c, 'El campo Correo_Oferta_enviado__c debe ser true'); 
    } 
}