force-app/main/default/objects/ImporteSME__c/ImporteSME__c.object-meta.xml
<CustomObject>
    <label>Importe</label>
    <nameField>
        <label>Nombre de Importe</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Importes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ImporteSME__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Coste__c.field-meta.xml
<CustomField>
    <fullName>Coste__c</fullName>
    <label>Coste</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Coste_horas__c.field-meta.xml
<CustomField>
    <fullName>Coste_horas__c</fullName>
    <label>Coste horas</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>40</fullName>
            </value>
            <value>
                <fullName>45</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>80</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Descuento__c.field-meta.xml
<CustomField>
    <fullName>Descuento__c</fullName>
    <defaultValue>0</defaultValue>
    <label>% Descuento</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Horas__c.field-meta.xml
<CustomField>
    <fullName>Horas__c</fullName>
    <label>Horas</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Importe_Bruto__c.field-meta.xml
<CustomField>
    <fullName>Importe_Bruto__c</fullName>
    <label>Importe Bruto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Modulo__c.field-meta.xml
<CustomField>
    <fullName>Modulo__c</fullName>
    <label>Modulo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Observaciones__c.field-meta.xml
<CustomField>
    <fullName>Observaciones__c</fullName>
    <label>Observaciones</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Oportunidad__c</referenceTo>
    <relationshipLabel>Importes</relationshipLabel>
    <relationshipName>Importes_SME</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <label>Producto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Seccion__c.field-meta.xml
<CustomField>
    <fullName>Seccion__c</fullName>
    <label>Sección</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HARD</fullName>
            </value>
            <value>
                <fullName>MTTO.HARD</fullName>
            </value>
            <value>
                <fullName>SOFT</fullName>
            </value>
            <value>
                <fullName>MTTO.SOFT</fullName>
            </value>
            <value>
                <fullName>SRV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Solucion__c.field-meta.xml
<CustomField>
    <fullName>Solucion__c</fullName>
    <label>Solución</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nueva licencia</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Migración</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Tipo_de_Pago__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pago__c</fullName>
    <label>Tipo de Pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PLC</fullName>
            </value>
            <value>
                <fullName>YLC</fullName>
            </value>
            <value>
                <fullName>QLC</fullName>
            </value>
            <value>
                <fullName>PSC</fullName>
            </value>
            <value>
                <fullName>YSC</fullName>
            </value>
            <value>
                <fullName>QSC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Oportunidad__c/Oportunidad__c.object-meta.xml
<CustomObject>
    <label>Oportunidad</label>
    <nameField>
        <label>Tema</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Oportunidades</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Oportunidad__c/fields/Etapa__c.field-meta.xml
<CustomField>
    <fullName>Etapa__c</fullName>
    <label>Etapa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Captación</fullName>
            </value>
            <value>
                <fullName>Cualificación</fullName>
            </value>
            <value>
                <fullName>Demostrando</fullName>
            </value>
            <value>
                <fullName>Oferta</fullName>
            </value>
            <value>
                <fullName>Cerrada</fullName>
                <label>Presentada (negociación y cierre)</label>
            </value>
            <value>
                <fullName>Abierta</fullName>
                <isActive>false</isActive>
                <label>Abierta</label>
            </value>
            <value>
                <fullName>Anulada</fullName>
                <isActive>false</isActive>
                <label>Anulada</label>
            </value>
            <value>
                <fullName>Aprobada</fullName>
                <isActive>false</isActive>
                <label>Aprobada</label>
            </value>
            <value>
                <fullName>Aprobada QA</fullName>
                <isActive>false</isActive>
                <label>Aprobado pdte Presentar</label>
            </value>
            <value>
                <fullName>Preparando QA</fullName>
                <isActive>false</isActive>
                <label>En preparación</label>
            </value>
            <value>
                <fullName>Ganada</fullName>
                <isActive>false</isActive>
                <label>Ganada</label>
            </value>
            <value>
                <fullName>Pedido Código Oferta</fullName>
                <isActive>false</isActive>
                <label>Pedido Código Oferta</label>
            </value>
            <value>
                <fullName>Pedir Código Oferta</fullName>
                <isActive>false</isActive>
                <label>Pedir Código Oferta</label>
            </value>
            <value>
                <fullName>Pendiente QA</fullName>
                <isActive>false</isActive>
                <label>Pendiente QA</label>
            </value>
            <value>
                <fullName>Perdida</fullName>
                <isActive>false</isActive>
                <label>Perdida</label>
            </value>
            <value>
                <fullName>Presentada</fullName>
                <isActive>false</isActive>
                <label>Presentada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <label>Producto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/Parametrica_2__c.object-meta.xml
<CustomObject>
    <description>Parametrica que contiene los datos de Ibermatica</description>
    <label>Parametrica Ibermática</label>
    <nameField>
        <label>Nombre de Parametrica Ibermática</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parametricas Ibermática</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parametrica_2__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>Activo</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>Inactivo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Modulo__c.field-meta.xml
<CustomField>
    <fullName>Modulo__c</fullName>
    <label>Modulo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <label>Producto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Solucion__c.field-meta.xml
<CustomField>
    <fullName>Solucion__c</fullName>
    <label>Solucion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/recordTypes/Area_Solucion_Producto.recordType-meta.xml
<RecordType>
    <fullName>Area_Solucion_Producto</fullName>
    <active>true</active>
    <label>Area Solucion Producto</label>
</RecordType>

force-app/main/default/classes/CRM_IB_Boton_Nuevo_Importe.cls
public class CRM_IB_Boton_Nuevo_Importe {

    @AuraEnabled
    public static String areaImporteSME(String OppId){
        String result = '';
        
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        //Recuperamos valores de gestor de produccion
        List <Parametrica_2__c> parametrica = [SELECT Id, Name,Area__c, Solucion__c, Producto__c, Tipo__c 
                                               FROM Parametrica_2__c 
                                               WHERE RecordType.DeveloperName = 'Area_Solucion_Producto' and Estado__c = '1' order by Area__c];
        List <String> valoresArea = new List<String>{''};
        
        for (Parametrica_2__c param: parametrica){
            if(!valoresArea.contains(param.Area__c)){
                valoresArea.add(param.Area__c);
            }
        }
        
        gen.writeObjectField('area', valoresArea);
        
        Oportunidad__c opp = [SELECT id,Name,RecordType.Name,Etapa__c FROM Oportunidad__c WHERE Id=:OppId];
        String RecordTypeOp = opp.RecordType.Name;
        
        gen.writeObjectField('RecordTypeOp', RecordTypeOp);
        gen.writeObjectField('oportunidad', opp);
        
        result = gen.getAsString();
        System.debug('result '+ result);
        return result;
    }
    
    @AuraEnabled
    public static List <String> solucionImporteSME(String Area){
        System.debug('Código area para filtrar: '+ Area );
        
        
        List <Parametrica_2__c> parametrica = [SELECT Id, Name, Tipo__c,Solucion__c
                                               FROM Parametrica_2__c
                                               WHERE RecordType.DeveloperName = 'Area_Solucion_Producto'  and Area__c =: Area and Estado__c = '1' order by Solucion__c];
        
        List <String> valoresSolucion = new List<String>{''};
        for (Parametrica_2__c param: parametrica){
            if(!valoresSolucion.contains(param.Solucion__c)){
                valoresSolucion.add(param.Solucion__c);
            }
        }
        
        system.debug('valores_solucion: ' + valoresSolucion);
        
        
        return valoresSolucion;
    }
    
    
 
     @AuraEnabled
    public static List <String> Producto_valoresImporteSME(String Area, String Solucion){
        System.debug('Código solucion y area para filtrar: '+ Area + ' / ' + Solucion );
        
        
        List <Parametrica_2__c> parametrica = [SELECT Id, Name, Tipo__c,Solucion__c,Producto__c
                                               FROM Parametrica_2__c
                                               WHERE RecordType.DeveloperName = 'Area_Solucion_Producto'  and Area__c =: Area and Solucion__c =: Solucion and Estado__c = '1' order by Producto__c];
        
        List <String> valoresProducto = new List<String>{''};
        for (Parametrica_2__c param: parametrica){
            if(!valoresProducto.contains(param.Producto__c)){
                valoresProducto.add(param.Producto__c);
            }
        }
        
        system.debug('valores_producto: ' + valoresProducto);
        
        
        return valoresProducto;
    }
       @AuraEnabled
    public static List <String> Modulo_valoresImporteSME(String Area, String Solucion, String Producto){
        System.debug('Código solucion y area para filtrar: '+ Area + ' / ' + Solucion );
        
        
        List <Parametrica_2__c> parametrica = [SELECT Id, Name, Tipo__c,Solucion__c,Producto__c,Modulo__c
                                               FROM Parametrica_2__c
                                               WHERE RecordType.DeveloperName = 'Area_Solucion_Producto'  and Area__c =: Area and Solucion__c =: Solucion and Producto__c =: Producto and Modulo__c != null and Estado__c = '1' order by Modulo__c];
        
        List <String> valoresModulo= new List<String>();
        for (Parametrica_2__c param: parametrica){
         
            if(!valoresModulo.contains(param.Modulo__c) && param.Modulo__c != null ){
                valoresModulo.add(param.Modulo__c);
            }
        }
        
        system.debug('valoresModulo: ' + valoresModulo);
        
        
        return valoresModulo;
    }
    @AuraEnabled
    public static String saveInfoImportes(String OppId, String Name_importe, String select_Seccion, Decimal Importe_bruto,Decimal Descuento,Integer Cantidad, Decimal Coste, String select_Costehoras,Decimal Horas, String select_Tipo, 
                                          String select_Tipo_Pago, String Observaciones, String Area,String Solucion,String Producto, String Modulo ){
        
       System.debug('Entro en saveInfoImportes');
        ImporteSME__c imp = new ImporteSME__c();
        
        imp.Oportunidad__c = OppId;
        imp.Name = Name_importe;
        imp.Seccion__c= select_Seccion;
        imp.Importe_Bruto__c=Importe_bruto;
        imp.Descuento__c  =Descuento;
        imp.Cantidad__c =Cantidad;
        imp.Coste__c= Coste;
        imp.Coste_horas__c= select_Costehoras;
        imp.Horas__c=Horas;
        imp.Tipo__c=select_Tipo;
        imp.Tipo_de_Pago__c=select_Tipo_Pago;
        imp.Observaciones__c=Observaciones;                                     
        imp.Area__c= Area;
        imp.Solucion__c= Solucion;
        imp.Producto__c= Producto;
        imp.Modulo__c = Modulo;
         System.debug('Importe a crear: ' + imp);
        try{
           
         insert imp; 
        }catch(Exception e){ 
            System.debug('Error guardar registro: ' + e.getMessage());
            return e.getMessage();            
        }
        
        system.debug('Actualizado');
        return 'SUCCESS';
        
    }
}