force-app/main/default/objects/ImporteSME__c/ImporteSME__c.object-meta.xml
<CustomObject>
    <label>Importe</label>
    <nameField>
        <label>Nombre de Importe</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Importes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ImporteSME__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Area_picklist__c.field-meta.xml
<CustomField>
    <fullName>Area_picklist__c</fullName>
    <label>Area_picklist</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APS</fullName>
            </value>
            <value>
                <fullName>CIBER</fullName>
            </value>
            <value>
                <fullName>ERP</fullName>
            </value>
            <value>
                <fullName>ING</fullName>
            </value>
            <value>
                <fullName>MES</fullName>
            </value>
            <value>
                <fullName>OTROS</fullName>
            </value>
            <value>
                <fullName>GLOBAL</fullName>
            </value>
            <value>
                <fullName>MCS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Coste__c.field-meta.xml
<CustomField>
    <fullName>Coste__c</fullName>
    <label>Coste</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Coste_horas__c.field-meta.xml
<CustomField>
    <fullName>Coste_horas__c</fullName>
    <label>Coste horas</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>40</fullName>
            </value>
            <value>
                <fullName>45</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>80</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Descuento__c.field-meta.xml
<CustomField>
    <fullName>Descuento__c</fullName>
    <defaultValue>0</defaultValue>
    <label>% Descuento</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Descuento_cantidad__c.field-meta.xml
<CustomField>
    <fullName>Descuento_cantidad__c</fullName>
    <formula>Importe_Bruto__c *Descuento__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Descuento cantidad</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Horas__c.field-meta.xml
<CustomField>
    <fullName>Horas__c</fullName>
    <label>Horas</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Importe__c.field-meta.xml
<CustomField>
    <fullName>Importe__c</fullName>
    <formula>Importe_Bruto__c *(1-Descuento__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Importe</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Importe_Bruto__c.field-meta.xml
<CustomField>
    <fullName>Importe_Bruto__c</fullName>
    <label>Importe Bruto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Margen__c.field-meta.xml
<CustomField>
    <fullName>Margen__c</fullName>
    <formula>IF( 
				AND(
								ISPICKVAL(Seccion__c,&apos;SRV&apos;), 
								Horas__c &lt;&gt; 0
				)
,
				Importe__c - VALUE(TEXT(Coste_horas__c))*Horas__c , 
				Importe__c-Coste__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Margen</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Modulo__c.field-meta.xml
<CustomField>
    <fullName>Modulo__c</fullName>
    <label>Modulo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Observaciones__c.field-meta.xml
<CustomField>
    <fullName>Observaciones__c</fullName>
    <label>Observaciones</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Oportunidad__c</referenceTo>
    <relationshipLabel>Importes</relationshipLabel>
    <relationshipName>Importes_SME</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <label>Producto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Record_Type_Opp__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Opp__c</fullName>
    <formula>Oportunidad__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Type Opp</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Seccion__c.field-meta.xml
<CustomField>
    <fullName>Seccion__c</fullName>
    <label>Sección</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HARD</fullName>
            </value>
            <value>
                <fullName>MTTO.HARD</fullName>
            </value>
            <value>
                <fullName>SOFT</fullName>
            </value>
            <value>
                <fullName>MTTO.SOFT</fullName>
            </value>
            <value>
                <fullName>SRV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Solucion__c.field-meta.xml
<CustomField>
    <fullName>Solucion__c</fullName>
    <label>Solución</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nueva licencia</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Migración</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ImporteSME__c/fields/Tipo_de_Pago__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pago__c</fullName>
    <label>Tipo de Pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PLC</fullName>
            </value>
            <value>
                <fullName>YLC</fullName>
            </value>
            <value>
                <fullName>QLC</fullName>
            </value>
            <value>
                <fullName>PSC</fullName>
            </value>
            <value>
                <fullName>YSC</fullName>
            </value>
            <value>
                <fullName>QSC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Oportunidad__c/Oportunidad__c.object-meta.xml
<CustomObject>
    <label>Oportunidad</label>
    <nameField>
        <label>Tema</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Oportunidades</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Oportunidad__c/fields/Clonada__c.field-meta.xml
<CustomField>
    <fullName>Clonada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Clonada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/Desglose_importes__c.field-meta.xml
<CustomField>
    <fullName>Desglose_importes__c</fullName>
    <label>Desglose importes</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/Importe_Licitacion__c.field-meta.xml
<CustomField>
    <fullName>Importe_Licitacion__c</fullName>
    <inlineHelpText>Total fee if indicated by the client in the tender document or estimated fee when opening the opportunity.</inlineHelpText>
    <label>Importe Total (sin IVA) €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/importe_mtoHard__c.field-meta.xml
<CustomField>
    <fullName>importe_mtoHard__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Importe Mtto. HW</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/importe_mtoSoft__c.field-meta.xml
<CustomField>
    <fullName>importe_mtoSoft__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Importe Mtto. SW</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/importe_productoHard__c.field-meta.xml
<CustomField>
    <fullName>importe_productoHard__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Importe HW</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/importe_productoSoft__c.field-meta.xml
<CustomField>
    <fullName>importe_productoSoft__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Importe SW</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/importe_servicio__c.field-meta.xml
<CustomField>
    <fullName>importe_servicio__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Importe Servicio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/Importe_total_sin_IVA__c.field-meta.xml
<CustomField>
    <fullName>Importe_total_sin_IVA__c</fullName>
    <inlineHelpText>En el campo Importe total ofertado (sin IVA) en Euros se indicará todo el contrato (incluida la parte del posible socio) y en el Importe SAP (€) se indicará la parte del contrato correspondiente a Ayesa durante el presente ejercicio.</inlineHelpText>
    <label>Importe total ofertado (sin IVA) Euros</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/margen_mtoHard__c.field-meta.xml
<CustomField>
    <fullName>margen_mtoHard__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Margen Mtto. HW</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/margen_mtoSoft__c.field-meta.xml
<CustomField>
    <fullName>margen_mtoSoft__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Margen Mtto. SW</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/Margen_Previsto_Euros__c.field-meta.xml
<CustomField>
    <fullName>Margen_Previsto_Euros__c</fullName>
    <label>Margen Previsto Euros</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/margen_productoSoft__c.field-meta.xml
<CustomField>
    <fullName>margen_productoSoft__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Margen SW</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/margen_servicio__c.field-meta.xml
<CustomField>
    <fullName>margen_servicio__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Margen Servicio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <label>Producto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/Rentabilidad_HW__c.field-meta.xml
<CustomField>
    <fullName>Rentabilidad_HW__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rentabilidad HW</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/Rentabilidad_SW__c.field-meta.xml
<CustomField>
    <fullName>Rentabilidad_SW__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rentabilidad SW</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CRM_ImportesSME_Utils.cls
public class CRM_ImportesSME_Utils {
    
    @AuraEnabled
    public static void recalcularImportesOportunidad(Id idOportunidad, boolean dmlaction) {
        
        System.debug('Metodo recalcularImportesOportunidad');
        
        Id recordTypeSME = Schema.SObjectType.Oportunidad__c.getRecordTypeInfosByName().get('Ibermatica SME').getRecordTypeId();
        Double descuento = 1;
        Double importe;
        Double margen;
        
        List <Oportunidad__c> oportunidades = [SELECT Id, name,Clonada__c,Desglose_importes__c,importe_mtoHard__c, importe_productoHard__c, importe_mtoSoft__c, importe_productoSoft__c, importe_servicio__c,
                                               margen_productoHard__c, margen_productoSoft__c, margen_mtoHard__c, margen_mtoSoft__c, margen_servicio__c,
                                               Rentabilidad_HW__c, Rentabilidad_Mtto_HW__c, Rentabilidad_Mtto_SW__c, Rentabilidad_SW__c, Rentabilidad_Serv__c, 
                                               Importe_total_sin_IVA__c,Importe_Licitacion__c,Margen_contrato__c,Margen_Previsto_Euros__c,recordTypeId
                                               FROM Oportunidad__c
                                               WHERE Id = :idOportunidad LIMIT 1];
    
        
        if (!oportunidades.isEmpty()) {
                            
            Oportunidad__c opp = oportunidades.get(0);
            
            //Blanqueamos campos para el recalculo
            opp.importe_productoHard__c = 0;
            opp.margen_productoHard__c = 0;
            opp.Rentabilidad_HW__c = 0;
            opp.importe_mtoHard__c = 0;             
            opp.margen_mtoHard__c  = 0;
            opp.Rentabilidad_Mtto_HW__c = 0;
            opp.importe_productoSoft__c = 0;
            opp.Margen_productoSoft__c = 0;                 
            opp.Rentabilidad_SW__c = 0;
            opp.importe_mtoSoft__c = 0;
            opp.margen_mtoSoft__c = 0;                                  
            opp.Rentabilidad_Mtto_SW__c = 0;
            opp.importe_servicio__c = 0;                
            opp.margen_servicio__c = 0;                     
            opp.Rentabilidad_Serv__c = 0;
            opp.Importe_total_sin_IVA__c = 0;
            opp.Margen_Previsto_Euros__c = 0;
            opp.Modificar_importes__c = true;
            
            List<ImporteSME__c> importes = [SELECT Id, Name, Importe_Bruto__c, Descuento_cantidad__c, Coste__c, Cantidad__c, Descuento__c, Oportunidad__c, Seccion__c, Tipo__c, 
                                            Tipo_de_Pago__c, Observaciones__c, Importe__c, Area__c, Solucion__c, Producto__c, Area_picklist__c, Modulo__c, Record_Type_Opp__c, 
                                            Coste_horas__c, Margen__c, Horas__c 
                                            FROM ImporteSME__c 
                                            WHERE Oportunidad__c = :idOportunidad];
                                            
            if (!importes.isEmpty()) {
                
                for (ImporteSME__c item : importes) {
                
                    if (item.Descuento__c != 0 || item.Descuento__c != null){
                        descuento = (100-item.Descuento__c)/100; 
                    }
                    importe = item.Importe_bruto__c*descuento;
                    margen = importe - item.Coste__c;
                    
                    System.debug('Importe ' + item.Name + ', Descuento: ' + descuento + ', Importe: ' + importe + ', Margen: ' + margen);
                    
                    switch on item.Seccion__c {     
                        when 'HARD' {
                            opp.importe_productoHard__c += importe;
                            opp.margen_productoHard__c += margen;                       
                            if(importe != 0 && importe != null){
                                opp.Rentabilidad_HW__c +=  margen*100 / importe;
                            }           
                        }
                        when 'MTTO.HARD' {              
                            opp.importe_mtoHard__c += importe;              
                            opp.margen_mtoHard__c  += margen;
                            if(importe!= 0 && importe != null){
                                opp.Rentabilidad_Mtto_HW__c +=  margen*100 / importe;
                            }
                        }
                        when 'SOFT' {
                            opp.importe_productoSoft__c += importe;
                            opp.Margen_productoSoft__c += margen;                   
                            if(importe!= 0 && importe != null) {
                                opp.Rentabilidad_SW__c += margen*100 / importe;
                            }       
                        }           
                        when 'MTTO.SOFT' {
                            opp.importe_mtoSoft__c += importe;
                            opp.margen_mtoSoft__c += margen;                                    
                            if(importe != 0 && importe != null){
                                opp.Rentabilidad_Mtto_SW__c += margen*100 / importe;
                            }       
                        }
                        when 'SRV' {
                            if(opp.RecordTypeId == recordTypeSME){
                                opp.importe_servicio__c += importe;
                                
                                Double coste_hora_calc = decimal.valueOf(item.Coste_horas__c)*item.Horas__c;
                                item.Coste__c=coste_hora_calc;
                                
                                opp.margen_servicio__c += (importe - coste_hora_calc);
                                
                                if(importe != 0 && importe != null){
                                    opp.Rentabilidad_Serv__c +=  (importe - coste_hora_calc)*100/ importe;                          
                                }
                            } else {
                                opp.importe_servicio__c += importe;             
                                opp.margen_servicio__c += margen;   
                                if(importe != 0 && importe != null){
                                    opp.Rentabilidad_Serv__c += margen*100 / importe;
                                }
                            }
                        }
                    }
                    
                    if(opp.Importe_total_sin_IVA__c == null) {
                        opp.Importe_total_sin_IVA__c = importe;
                    } else {
                        opp.Importe_total_sin_IVA__c += importe;
                    }
                    if(opp.Margen_Previsto_Euros__c == null) {
                        opp.Margen_Previsto_Euros__c = item.Margen__c;
                    } else {
                        opp.Margen_Previsto_Euros__c += item.Margen__c;
                    }               
                }
                
                if (dmlaction) {
                    update opp;                   
                    //Cambio a false el modificar importes
                    opp.Modificar_importes__c = false;
                    update opp;                     
                } else {
                    System.debug('Datos Oportunidad:');
                    System.debug('importe_productoHard__c:' + opp.importe_productoHard__c);
                    System.debug('margen_productoHard__c :' + opp.margen_productoHard__c);
                    System.debug('Rentabilidad_HW__c:' + opp.Rentabilidad_HW__c);
                    System.debug('importe_mtoHard__c:' + opp.importe_mtoHard__c);               
                    System.debug('margen_mtoHard__c:' +  opp.margen_mtoHard__c);
                    System.debug('Rentabilidad_Mtto_HW__c:' + opp.Rentabilidad_Mtto_HW__c);
                    System.debug('importe_productoSoft__c:' + opp.importe_productoSoft__c);
                    System.debug('Margen_productoSoft__c:' + opp.Margen_productoSoft__c);                   
                    System.debug('Rentabilidad_SW__c:' + opp.Rentabilidad_SW__c);
                    System.debug('importe_mtoSoft__c:' + opp.importe_mtoSoft__c);
                    System.debug('margen_mtoSoft__c:' + opp.margen_mtoSoft__c);                                 
                    System.debug('Rentabilidad_Mtto_SW__c:' + opp.Rentabilidad_Mtto_SW__c);
                    System.debug('importe_servicio__c:' + opp.importe_servicio__c);                 
                    System.debug('margen_servicio__c:' + opp.margen_servicio__c);                       
                    System.debug('Rentabilidad_Serv__c:' + opp.Rentabilidad_Serv__c);
                    System.debug('Importe_total_sin_IVA__c: ' + opp.Importe_total_sin_IVA__c);
                    System.debug('Margen_Previsto_Euros__c: ' + opp.Margen_Previsto_Euros__c);
                }  
                
            } else {        
                System.debug('No se han encontrado importes para la oportundiad ' + idOportunidad);
            }
        } else {
            System.debug('No se ha encontrado oportunidad para el id ' + idOportunidad);
        }
    }
}