force-app/main/default/objects/WebService__c/WebService__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>WebService</label>
</CustomObject>

force-app/main/default/objects/WebService__c/fields/password__c.field-meta.xml
<CustomField>
    <fullName>password__c</fullName>
    <label>password</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CRM_Responsable_ProyectoHelper.cls
public class CRM_Responsable_ProyectoHelper {
    
    public static String buildBusquedaEmplRequestBody(String buscarTexto){
        
        WebService__c webServiceData = WebService__c.getInstance();
        String user = webServiceData.username__c;        
        String pass = webServiceData.password__c;
        
       // return String.format(CRM_IntegrationConstants.INTEGRATION_RESPONSABLE_BODY_TEMPLATE, new List<String>{user, pass, buscarTexto});
        return CRM_IntegrationConstants.INTEGRATION_RESPONSABLE_BODY_TEMPLATE;
        
    }

}