force-app/main/default/objects/Oportunidad__c/Oportunidad__c.object-meta.xml
<CustomObject>
    <label>Oportunidad</label>
    <nameField>
        <label>Tema</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Oportunidades</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Oportunidad__c/fields/CPV__c.field-meta.xml
<CustomField>
    <fullName>CPV__c</fullName>
    <inlineHelpText>CPV (Common Procurement Vocabulary - Vocabulario Común de Contratación Pública) es un sistema de identificación y categorización de todas las actividades económicas susceptibles de ser contratadas mediante licitación o concurso público en la Unión Europea. Si no se tiene, escribir No Aplica</inlineHelpText>
    <label>CPV</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/CPV_varios__c.field-meta.xml
<CustomField>
    <fullName>CPV_varios__c</fullName>
    <inlineHelpText>CPV es un sistema de identificación y categorización de todas las actividades económicas susceptibles de ser contratadas mediante licitación o concurso público en la Unión Europea. Elija uno o varios valores.</inlineHelpText>
    <label>CPV varios</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/Parametrica_2__c.object-meta.xml
<CustomObject>
    <description>Parametrica que contiene los datos de Ibermatica</description>
    <label>Parametrica Ibermática</label>
    <nameField>
        <label>Nombre de Parametrica Ibermática</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parametricas Ibermática</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parametrica_2__c/fields/CPV__c.field-meta.xml
<CustomField>
    <fullName>CPV__c</fullName>
    <label>CPV</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Descripcion_CPV__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_CPV__c</fullName>
    <label>Descripción CPV</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/recordTypes/CPV.recordType-meta.xml
<RecordType>
    <fullName>CPV</fullName>
    <active>true</active>
    <label>CPV</label>
</RecordType>

force-app/main/default/classes/CRM_IB_CPVController.cls
public class CRM_IB_CPVController {
   
    //Componente CPV
    @AuraEnabled
    public static Map<String, Object> valoresCPV(String Id_oportunidad){
        System.debug('CRM_IB_CPVController valoresCPV...');
        
        Map<String, Object> result = new Map<String, Object>(); // mapa para almacenar las opciones disponibles y los valores seleccionados
		
        // obtenemos los valores CPV de la parametrica
        List<Parametrica_2__c> valores_CPV = [SELECT Id, Name, CPV__c, Descripcion_CPV__c, RecordType.Name
                                               from Parametrica_2__c 
                                               where RecordType.Name = 'CPV' order by CPV__c];
        System.debug('valores CPV encontrados en la paramétrica: ' + valores_CPV.size());
        
        // los añadimos en una lista para el dualListbox
        List<String> opciones = new List<String>();
        for (Parametrica_2__c param : valores_CPV) {
            if (!opciones.contains(param.Name) && param.Name != null) {
                opciones.add(param.CPV__c + ' (' + param.Descripcion_CPV__c + ')');
            }
        }
        result.put('opciones', opciones);
        
        // obtenermos los valores seleccionados previamente en el registro de oportunidad
        if (Id_oportunidad != null) {
            Oportunidad__c opp = [SELECT Id, Name, CPV_varios__c FROM Oportunidad__c where Id =: Id_oportunidad];
            System.debug('Oportunidad recuperada "'+ opp.Name + '" y su/s valor/es CPV: ' + opp.CPV_varios__c  );
            if (opp.CPV_varios__c != null) {
                List<String> valoresSeleccionados = opp.CPV_varios__c.split(';');
                result.put('valoresSeleccionados', valoresSeleccionados);
            }
        }
        System.debug('valoresCPV result: ' + result);
        return result;
    }

    @AuraEnabled
    public static void saveOportunidad_CPV(Id Id_oportunidad, String seleccionCPV){
        
        System.debug('saveOportunidad_CPV... CPV seleccionados: ' + seleccionCPV);
        
        Oportunidad__c opp = [SELECT Id, Name, CPV_varios__c FROM Oportunidad__c where Id =: Id_oportunidad LIMIT 1];
        
        if (String.isNotBlank(seleccionCPV)) {
            try{
                opp.CPV_varios__c = seleccionCPV;
                update opp;
                system.debug('Actualizado');
            } catch(DMLException e){ 
                System.debug('Error CPV Oportunidad: ' + e.getMessage());            
            }	
        } else if (String.isBlank(seleccionCPV)) {
            try {
                opp.CPV_varios__c = seleccionCPV;
                update opp;
                system.debug('Actualizado');
            } catch(Exception e) { 
                System.debug('Error CPV Oportunidad: ' + e.getMessage());  
            }
        }
    }

}