force-app/main/default/objects/Oportunidad__c/Oportunidad__c.object-meta.xml
<CustomObject>
    <label>Oportunidad</label>
    <nameField>
        <label>Tema</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Oportunidades</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Oportunidad__c/fields/Estado_de_Cierre__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_Cierre__c</fullName>
    <inlineHelpText>Close the opportunity when you become aware of the outcome. If awarded the bid, we suggest closing it once the PSP (Project Structure Plan) has been opened.</inlineHelpText>
    <label>Estado de Cierre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Perdida</fullName>
            </value>
            <value>
                <fullName>Anulada</fullName>
            </value>
            <value>
                <fullName>No Presentada</fullName>
            </value>
            <value>
                <fullName>Contratada</fullName>
            </value>
            <value>
                <fullName>Adjudicada</fullName>
                <isActive>false</isActive>
                <label>Adjudicada</label>
            </value>
            <value>
                <fullName>Ganada</fullName>
                <isActive>false</isActive>
                <label>Ganada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/Etapa__c.field-meta.xml
<CustomField>
    <fullName>Etapa__c</fullName>
    <label>Etapa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Captación</fullName>
            </value>
            <value>
                <fullName>Cualificación</fullName>
            </value>
            <value>
                <fullName>Demostrando</fullName>
            </value>
            <value>
                <fullName>Oferta</fullName>
            </value>
            <value>
                <fullName>Cerrada</fullName>
                <label>Presentada (negociación y cierre)</label>
            </value>
            <value>
                <fullName>Abierta</fullName>
                <isActive>false</isActive>
                <label>Abierta</label>
            </value>
            <value>
                <fullName>Anulada</fullName>
                <isActive>false</isActive>
                <label>Anulada</label>
            </value>
            <value>
                <fullName>Aprobada</fullName>
                <isActive>false</isActive>
                <label>Aprobada</label>
            </value>
            <value>
                <fullName>Aprobada QA</fullName>
                <isActive>false</isActive>
                <label>Aprobado pdte Presentar</label>
            </value>
            <value>
                <fullName>Preparando QA</fullName>
                <isActive>false</isActive>
                <label>En preparación</label>
            </value>
            <value>
                <fullName>Ganada</fullName>
                <isActive>false</isActive>
                <label>Ganada</label>
            </value>
            <value>
                <fullName>Pedido Código Oferta</fullName>
                <isActive>false</isActive>
                <label>Pedido Código Oferta</label>
            </value>
            <value>
                <fullName>Pedir Código Oferta</fullName>
                <isActive>false</isActive>
                <label>Pedir Código Oferta</label>
            </value>
            <value>
                <fullName>Pendiente QA</fullName>
                <isActive>false</isActive>
                <label>Pendiente QA</label>
            </value>
            <value>
                <fullName>Perdida</fullName>
                <isActive>false</isActive>
                <label>Perdida</label>
            </value>
            <value>
                <fullName>Presentada</fullName>
                <isActive>false</isActive>
                <label>Presentada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/Existencia_de_Incoherencias__c.field-meta.xml
<CustomField>
    <fullName>Existencia_de_Incoherencias__c</fullName>
    <description>Validación de incoherencias en los datos de la oportunidad</description>
    <formula>OR(
  AND(
    NOT ( ISPICKVAL(Etapa__c, &apos;Cerrada&apos;) ),
    Fecha_limite_de_presentacion__c  &lt;  TODAY() 
  ),
  AND(
    NOT ( ISPICKVAL(Etapa__c, &apos;Cerrada&apos;) ),
    Fecha_estimada_de_cierre__c  &lt;  TODAY() 
  ),
  AND(
    NOT ( ISPICKVAL(Etapa__c, &apos;Cualificación&apos;) ),
    NOT ( ISPICKVAL(Tipo_de_Oportunidad__c, &apos;Licitación&apos;) )
  ),
  Fecha_estimada_de_cierre__c &lt;= Fecha_limite_de_presentacion__c
)</formula>
    <inlineHelpText>Validation of inconsistencies in the data of the opportunity</inlineHelpText>
    <label>Existencia de Incoherencias</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/recordTypes/Ayesa.recordType-meta.xml
<RecordType>
    <fullName>Ayesa</fullName>
    <active>true</active>
    <description>Flujo de Ayesa</description>
    <label>Ayesa</label>
</RecordType>

force-app/main/default/classes/CRM_Notific_Op_Incoherentes.cls
global class CRM_Notific_Op_Incoherentes implements Database.Batchable<sObject>{
    global String errMsg = '';
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        system.debug('Ejecución de consulta de oportunidades incoherentes...');
        
        string query='SELECT Id, Name, OwnerId, Owner.name, Owner.email FROM Oportunidad__c WHERE Existencia_de_Incoherencias__c = true and (Etapa__c != \'Cerrada\' or estado_de_cierre__c = \'Contratada\') order by OwnerId' + (Test.isRunningTest()?' LIMIT 10':'');                

        return Database.getQueryLocator(query);
        
    }
    
    global void execute(Database.BatchableContext BC, List<Oportunidad__c> ownerByOppIncoherente){
        system.debug('Tamaño de lista de oportunidades con INCOHERENCIAS:  ' + ownerByOppIncoherente.size());
               
       	//Se crea lista de emails
  		List<Messaging.SingleEmailMessage> theEmails = new List<Messaging.SingleEmailMessage>(); 
        
        //Guardo los Id's de los usuarios (idioma 1.1)
        Set <Id> lista_Ids_RPS = new Set<Id>();
        for (Oportunidad__c opp : ownerByOppIncoherente){
            lista_Ids_RPS.add(opp.OwnerId);
        }
        //system.debug('Total de usuarios:  '+ lista_Ids_RPS.size());
        
        //Hago lista de usuarios con esos IDS (idioma 1.2)        
        List<User> lista_Usuarios = [SELECT id, email, LanguageLocaleKey FROM User where id IN :lista_Ids_RPS ];        
        system.debug('Tamaño de lista de Usuarios con INCOHERENCIAS: ' + lista_Usuarios.size());
        
        //Recuperamos plantilla a utilizar para el envío del correo
        EmailTemplate et = [SELECT Id FROM EmailTemplate WHERE DeveloperName = 'CRMEmailOportunidadesIncoherentes'];
                                      
        //enviamos correo a cada usuario con oportunidades incoherentes
        Integer cont = 0;
        List<Messaging.SingleEmailMessage> allmsg = new List<Messaging.SingleEmailMessage>();        
        for (User user : lista_Usuarios){
            system.debug('Contador='+cont);
            
            allmsg.add(composeEmail(user, et));
            cont++;
            
            if (cont == 100 || cont >= lista_Usuarios.size()) {
                system.debug('Ejecutando envio...');
                
                try {
                    Messaging.sendEmail(allmsg, false);
                    system.debug('Lista de Emails enviada correctamente.');
                } catch (Exception e) {
                    system.debug('Error enviando lista de emails.');
                    System.debug(e.getMessage());
                    errMsg += 'Batch [CRM_Notific_Op_Incoherentes] Error al enviar lista de emails. ErrMsg = ' + e.getMessage() + '<br />';
                }
                
                allmsg = new List<Messaging.SingleEmailMessage>();                
            }
        }
        system.debug('Fin ejecución proceso de notificación de incoherencias.');
    }
    
    global void finish(Database.BatchableContext BC){
        if (errMsg == '') {
            System.debug('Batch [CRM_Notific_Op_Incoherentes] ha finalizado : Todas las incoherencias han sido notificadas correctamente.');
        }
        else {
            System.debug('Batch [CRM_Notific_Op_Incoherentes] ha finalizado : Existen errores. Lista de errores. <br />' + errMsg);
        }
    }      
    
    private Messaging.SingleEmailMessage composeEmail(User usuario, EmailTemplate plantilla) {        
               
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setTemplateId(plantilla.Id);
        mail.setTargetObjectId(usuario.Id);
        mail.setWhatId(usuario.Id);        
        mail.setToAddresses( new String[] { usuario.Email } );        
        mail.setSaveAsActivity(false);
        mail.setSenderDisplayName('CRM Ayesa Support');
        
        return mail;        
    }
}