force-app/main/default/objects/Oportunidad__c/Oportunidad__c.object-meta.xml
<CustomObject>
    <label>Oportunidad</label>
    <nameField>
        <label>Tema</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Oportunidades</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Oportunidad__c/fields/Area_Tecnologia__c.field-meta.xml
<CustomField>
    <fullName>Area_Tecnologia__c</fullName>
    <inlineHelpText>Elija una o varias tecnologías que se utilizarían en el futuro PEP.</inlineHelpText>
    <label>Área Tecnología</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area_Tecnologia_Lista</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/CPV_varios__c.field-meta.xml
<CustomField>
    <fullName>CPV_varios__c</fullName>
    <inlineHelpText>CPV es un sistema de identificación y categorización de todas las actividades económicas susceptibles de ser contratadas mediante licitación o concurso público en la Unión Europea. Elija uno o varios valores.</inlineHelpText>
    <label>CPV varios</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/Fecha_estimada_de_cierre__c.field-meta.xml
<CustomField>
    <fullName>Fecha_estimada_de_cierre__c</fullName>
    <description>Fecha estimada de cierre de la oportunidad</description>
    <inlineHelpText>Estimated opportunity closing date or tender process resolution. Enter the ACTUAL date if it has already been closed (lost, awarded, etc.)</inlineHelpText>
    <label>Fecha de cierre</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/Importe_total_sin_IVA__c.field-meta.xml
<CustomField>
    <fullName>Importe_total_sin_IVA__c</fullName>
    <inlineHelpText>En el campo Importe total ofertado (sin IVA) en Euros se indicará todo el contrato (incluida la parte del posible socio) y en el Importe SAP (€) se indicará la parte del contrato correspondiente a Ayesa durante el presente ejercicio.</inlineHelpText>
    <label>Importe total ofertado (sin IVA) Euros</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/Referencia_Comercial_lookup__c.field-meta.xml
<CustomField>
    <fullName>Referencia_Comercial_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referencia Comercial</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referencia_Comercial__c.Clic_comercial__c</field>
            <operation>equals</operation>
            <valueField>$Source.Cliente__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referencia_Comercial__c</referenceTo>
    <relationshipLabel>Oportunidades relacionadas</relationshipLabel>
    <relationshipName>Oportunidades_relacionadas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/Tecnologia__c.field-meta.xml
<CustomField>
    <fullName>Tecnologia__c</fullName>
    <inlineHelpText>Elija una o varias tecnologías que se utilizarían en el futuro PEP.  Si no encuentra la que busca, abra una incidencia en https://helpdesk.ayesa.com</inlineHelpText>
    <label>Tecnología</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AP-Administración electrónica</fullName>
            </value>
            <value>
                <fullName>AP-Smart Cities</fullName>
            </value>
            <value>
                <fullName>Arquitectura Empresarial</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>Big Data</fullName>
            </value>
            <value>
                <fullName>Blockchain</fullName>
            </value>
            <value>
                <fullName>BPM</fullName>
            </value>
            <value>
                <fullName>Business Operations</fullName>
            </value>
            <value>
                <fullName>Ciberseguridad</fullName>
            </value>
            <value>
                <fullName>COE-CIBERSEGURIDAD</fullName>
            </value>
            <value>
                <fullName>COE-CIBERSEGURIDAD AUDITORIAS IT/OT</fullName>
            </value>
            <value>
                <fullName>COE-CIBERSEGURIDAD COMPLIANCE</fullName>
            </value>
            <value>
                <fullName>COE-CIBERSEGURIDAD FORMACIÓN CIBER</fullName>
            </value>
            <value>
                <fullName>COE-CIBERSEGURIDAD MSSP SOC/CERT</fullName>
            </value>
            <value>
                <fullName>COE-CIBERSEGURIDAD SECURITY RESSELING</fullName>
            </value>
            <value>
                <fullName>COE-Hybrid IT / Cloud Computing</fullName>
            </value>
            <value>
                <fullName>COE-Microsoft</fullName>
            </value>
            <value>
                <fullName>COE-Salesforce</fullName>
            </value>
            <value>
                <fullName>COE-SAP</fullName>
            </value>
            <value>
                <fullName>COE-SAP Ariba</fullName>
            </value>
            <value>
                <fullName>COE-SAP C4</fullName>
            </value>
            <value>
                <fullName>COE-SAP Concur</fullName>
            </value>
            <value>
                <fullName>COE-SAP Group Reporting</fullName>
            </value>
            <value>
                <fullName>COE-SAP RPA</fullName>
            </value>
            <value>
                <fullName>COE-SAP SAC</fullName>
            </value>
            <value>
                <fullName>COE-SAP SLCM</fullName>
            </value>
            <value>
                <fullName>COE-SAP SSFF</fullName>
            </value>
            <value>
                <fullName>COE-SAP Vistex</fullName>
            </value>
            <value>
                <fullName>COE-Smart Factory &amp; OT</fullName>
            </value>
            <value>
                <fullName>Desarrollo a Medida</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referencia_Comercial__c/Referencia_Comercial__c.object-meta.xml
<CustomObject>
    <label>Referencia Comercial</label>
    <nameField>
        <label>Referencia Comercial Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referencias Comerciales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referencia_Comercial__c/fields/Area_conocimiento_tecno__c.field-meta.xml
<CustomField>
    <fullName>Area_conocimiento_tecno__c</fullName>
    <label>Área Conocimiento Tecnológica</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AP-Administración electrónica</fullName>
            </value>
            <value>
                <fullName>AP-Smart Cities</fullName>
            </value>
            <value>
                <fullName>COE-CIBERSEGURIDAD</fullName>
            </value>
            <value>
                <fullName>COE-CIBERSEGURIDAD AUDITORIAS IT/OT</fullName>
            </value>
            <value>
                <fullName>COE-CIBERSEGURIDAD COMPLIANCE</fullName>
            </value>
            <value>
                <fullName>COE-CIBERSEGURIDAD FORMACIÓN CIBER</fullName>
            </value>
            <value>
                <fullName>COE-CIBERSEGURIDAD MSSP SOC/CERT</fullName>
            </value>
            <value>
                <fullName>COE-CIBERSEGURIDAD SECURITY RESSELING</fullName>
            </value>
            <value>
                <fullName>COE-Hybrid IT / Cloud Computing</fullName>
            </value>
            <value>
                <fullName>COE-Microsoft</fullName>
            </value>
            <value>
                <fullName>COE-Salesforce</fullName>
            </value>
            <value>
                <fullName>COE-SAP</fullName>
            </value>
            <value>
                <fullName>COE-SAP Ariba</fullName>
            </value>
            <value>
                <fullName>COE-SAP C4</fullName>
            </value>
            <value>
                <fullName>COE-SAP Concur</fullName>
            </value>
            <value>
                <fullName>COE-SAP Group Reporting</fullName>
            </value>
            <value>
                <fullName>COE-SAP RPA</fullName>
            </value>
            <value>
                <fullName>COE-SAP SAC</fullName>
            </value>
            <value>
                <fullName>COE-SAP SLCM</fullName>
            </value>
            <value>
                <fullName>COE-SAP SSFF</fullName>
            </value>
            <value>
                <fullName>COE-SAP Vistex</fullName>
            </value>
            <value>
                <fullName>COE-Smart Factory &amp; OT</fullName>
            </value>
            <value>
                <fullName>DIG-+DevOps / Agile</fullName>
            </value>
            <value>
                <fullName>DIG-BLOCKCHAIN</fullName>
            </value>
            <value>
                <fullName>DIG-DATA-Analytics-Artificial Intelligence</fullName>
            </value>
            <value>
                <fullName>DIG-DX Digital Experience</fullName>
            </value>
            <value>
                <fullName>DIG-Gestión documental</fullName>
            </value>
            <value>
                <fullName>DIG-HCM-Personas</fullName>
            </value>
            <value>
                <fullName>DIG-IBERDOK</fullName>
            </value>
            <value>
                <fullName>DIG-Learning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referencia_Comercial__c/fields/Area_Tecnologia__c.field-meta.xml
<CustomField>
    <fullName>Area_Tecnologia__c</fullName>
    <label>Área Tecnología</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area_Tecnologia_Lista</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referencia_Comercial__c/fields/Buscador_Area_Conocimiento_Tecnologica__c.field-meta.xml
<CustomField>
    <fullName>Buscador_Area_Conocimiento_Tecnologica__c</fullName>
    <label>Buscador Area Conocimiento Tecnologica</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Referencia_Comercial__c/fields/CPV_varios__c.field-meta.xml
<CustomField>
    <fullName>CPV_varios__c</fullName>
    <label>CPV varios</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Referencia_Comercial__c/fields/Fecha__c.field-meta.xml
<CustomField>
    <fullName>Fecha__c</fullName>
    <label>Fecha última oportunidad</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Referencia_Comercial__c/fields/Importe_acumulado__c.field-meta.xml
<CustomField>
    <fullName>Importe_acumulado__c</fullName>
    <label>Importe acumulado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CRM_IB_Update_ReferenciaComercial.cls
public class CRM_IB_Update_ReferenciaComercial {
    
    //Componente
    @AuraEnabled
    public static string update_referencia_comercial(String Id_ref){
        //1. Recuperamos Referencia
        Referencia_Comercial__c ref_comercial = [Select Id,Importe_acumulado__c,Fecha__c,Area_Tecnologia__c,CPV_varios__c FROM Referencia_comercial__c where id =: Id_ref limit 1];
        //2. Recuperamos oportunidades relacionadas
        List <Oportunidad__c> ops_relacionadas = [SELECT Id, Importe_total_sin_IVA__c, fecha_estimada_de_cierre__c,Tecnologia__c,CPV_varios__c,Area_Tecnologia__c FROM Oportunidad__c where Referencia_comercial_lookup__c =: Id_ref];
        System.debug('Lista de oportunidades tamaño: '+ ops_relacionadas.size());
        //3. Bucle suma de importes y máxima fecha de cierre
        Decimal suma_importe=0;
        Date max_fecha_cierre ;
        String Tecnologia_concat = '';
        String CPV_concat = '';
        
        List <String> lista_tecnologia = new List <String>();
        List <String> lista_cpv = new List <String>();
        
        for(Oportunidad__c op : ops_relacionadas){
            //1. Importes
            if(op.Importe_total_sin_IVA__c !=  null){
                suma_importe += op.Importe_total_sin_IVA__c;
            }
            System.debug('Importe acumulado: '+ suma_importe);
            
            //2.Fecha última de cierre
            if(max_fecha_cierre==null){
                max_fecha_cierre = op.Fecha_estimada_de_cierre__c;
            }
            if(max_fecha_cierre < op.Fecha_estimada_de_cierre__c){
                max_fecha_cierre = op.Fecha_estimada_de_cierre__c;
            }
            
            //3. Tecnología
            if(op.Area_Tecnologia__c != null){
                if(op.Area_Tecnologia__c.contains(';')){
                    lista_tecnologia =  op.Area_Tecnologia__c.split(';');
                }else{
                    lista_tecnologia.add(op.Area_Tecnologia__c);
                }
            }
            
            //3.5 CPV
            if(op.CPV_varios__c != null){
                if(op.CPV_varios__c.contains(';')){
                    lista_cpv =  op.CPV_varios__c.split(';');
                }else{
                    lista_cpv.add(op.CPV_varios__c);
                }
            }
            
            
        }
        
        for(String valor : lista_tecnologia){
            if(!tecnologia_concat.contains(valor)){
                tecnologia_concat = tecnologia_concat + ';' + valor;
            }
        }
        System.debug('Tecnologia :' + tecnologia_concat);
        
        for(String valor : lista_cpv){
            if(!cpv_concat.contains(valor)){
                if(cpv_concat.length()>0){
                    cpv_concat = cpv_concat + ';' + valor;
                }else{
                    cpv_concat = valor;
                }
                
            }
        }
        System.debug('CPV :' + cpv_concat);
        //4. Actualizar referencia comercial
        try{
            ref_comercial.Importe_acumulado__c = suma_importe;  
            ref_comercial.Fecha__c=  max_fecha_cierre;
            ref_comercial.Area_Tecnologia__c=tecnologia_concat;
            ref_comercial.Buscador_Area_Conocimiento_Tecnologica__c=tecnologia_concat;
            ref_comercial.CPV_varios__c=cpv_concat;
            update ref_comercial;
        }catch (DMLException e){ 
            System.debug('Error actualizar referencia comercial: ' + e.getMessage());
            // respuesta = e.getMessage(); 
            return e.getMessage(); 
            
        }
        
        return 'ok';
        
    }
    
    
    //Flujo
    @InvocableMethod 
    public static void update_referencia_comercial_flujo(List<String> Id_ref){
        
        //1. Recuperamos Referencia
        //  String Id_ref = Id_ref_list[0];
        Referencia_Comercial__c ref_comercial = [Select Id,Importe_acumulado__c,Fecha__c,Area_conocimiento_tecno__c,CPV_varios__c FROM Referencia_comercial__c where id =: Id_ref limit 1];
        //2. Recuperamos oportunidades relacionadas
        List <Oportunidad__c> ops_relacionadas = [SELECT Id, Importe_total_sin_IVA__c, fecha_estimada_de_cierre__c,Tecnologia__c,CPV_varios__c,Area_Tecnologia__c FROM Oportunidad__c where Referencia_comercial_lookup__c =: Id_ref];
        System.debug('Lista de oportunidades tamaño: '+ ops_relacionadas.size());
        //3. Bucle suma de importes y máxima fecha de cierre
        Decimal suma_importe=0;
        Date max_fecha_cierre ;
        String tecnologia_concat = '';
        String cpv_concat = '';
        
        List <String> lista_tecnologia = new List <String>();
        List <String> lista_cpv = new List <String>();
        
        for(Oportunidad__c op : ops_relacionadas){
            //1. Importes
            if(op.Importe_total_sin_IVA__c !=  null){
                suma_importe += op.Importe_total_sin_IVA__c;
            }
            System.debug('Importe acumulado: '+ suma_importe);
            
            //2.Fecha última de cierre
            if(max_fecha_cierre==null){
                max_fecha_cierre = op.Fecha_estimada_de_cierre__c;
            }
            if(max_fecha_cierre < op.Fecha_estimada_de_cierre__c){
                max_fecha_cierre = op.Fecha_estimada_de_cierre__c;
            }
            
            //3. Tecnología
            if(op.Area_Tecnologia__c != null){
                if(op.Area_Tecnologia__c.contains(';')){
                    lista_tecnologia =  op.Area_Tecnologia__c.split(';');
                }else{
                    lista_tecnologia.add(op.Area_Tecnologia__c);
                }
            }
            
            //3.5 CPV
            if(op.CPV_varios__c != null){
                if(op.CPV_varios__c.contains(';')){
                    lista_cpv =  op.CPV_varios__c.split(';');
                }else{
                    lista_cpv.add(op.CPV_varios__c);
                }
                
            }
            
        }
        
        for(String valor : lista_tecnologia){
            if(!tecnologia_concat.contains(valor)){
                tecnologia_concat = tecnologia_concat + ';' + valor;
            }
        }
        
        for(String valor : lista_cpv){
            if(!cpv_concat.contains(valor)){
                if(cpv_concat.length()>0){
                    cpv_concat = cpv_concat + ';' + valor;
                }else{
                    cpv_concat = valor;
                }
                
            }
        }
        System.debug('CPV :' + cpv_concat);
        System.debug('Tecnologia :' + tecnologia_concat);
        //4. Actualizar referencia comercial
        try{
            ref_comercial.Importe_acumulado__c = suma_importe;  
            ref_comercial.Fecha__c=  max_fecha_cierre;
            ref_comercial.Area_Tecnologia__c=tecnologia_concat;
            ref_comercial.Buscador_Area_Conocimiento_Tecnologica__c=tecnologia_concat;
            ref_comercial.CPV_varios__c=cpv_concat;
            update ref_comercial;
        }catch (DMLException e){ 
            System.debug('Error actualizar referencia comercial: ' + e.getMessage());
            // respuesta = e.getMessage(); 
            //  return e.getMessage(); 
            
        }
        
        //return 'ok';
        
    }
    
}