force-app/main/default/objects/Account/fields/Alias__c.field-meta.xml
<CustomField>
    <fullName>Alias__c</fullName>
    <label>Alias</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Organizacion__c.field-meta.xml
<CustomField>
    <fullName>Organizacion__c</fullName>
    <label>Organización</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>-</fullName>
                <isActive>false</isActive>
                <label>-</label>
            </value>
            <value>
                <fullName>BANKING</fullName>
            </value>
            <value>
                <fullName>Cambio de partner</fullName>
                <isActive>false</isActive>
                <label>Cambio de partner</label>
            </value>
            <value>
                <fullName>CLI</fullName>
                <isActive>false</isActive>
                <label>CLI</label>
            </value>
            <value>
                <fullName>Cli indirecto</fullName>
                <isActive>false</isActive>
                <label>Cli indirecto</label>
            </value>
            <value>
                <fullName>CON</fullName>
                <isActive>false</isActive>
                <label>CON</label>
            </value>
            <value>
                <fullName>CONSUMER</fullName>
            </value>
            <value>
                <fullName>DIGITAL ADMIN</fullName>
            </value>
            <value>
                <fullName>Distribuido</fullName>
                <isActive>false</isActive>
                <label>Distribuido</label>
            </value>
            <value>
                <fullName>ENERGY &amp; UTILITIES</fullName>
            </value>
            <value>
                <fullName>GRUPO IBERMATICA</fullName>
            </value>
            <value>
                <fullName>HEALTH</fullName>
            </value>
            <value>
                <fullName>ILA ARGENTINA</fullName>
            </value>
            <value>
                <fullName>INSURANCE</fullName>
            </value>
            <value>
                <fullName>INTERFLEX</fullName>
            </value>
            <value>
                <fullName>MANUFACTURING</fullName>
            </value>
            <value>
                <fullName>MICROSOFT</fullName>
            </value>
            <value>
                <fullName>N/R</fullName>
                <isActive>false</isActive>
                <label>N/R</label>
            </value>
            <value>
                <fullName>NC</fullName>
                <isActive>false</isActive>
                <label>NC</label>
            </value>
            <value>
                <fullName>ONCE GROUP</fullName>
            </value>
            <value>
                <fullName>SCADA ARGENTINA</fullName>
            </value>
            <value>
                <fullName>SCADA CHILE</fullName>
            </value>
            <value>
                <fullName>SCADA PERU</fullName>
            </value>
            <value>
                <fullName>SMART FACTORIES</fullName>
            </value>
            <value>
                <fullName>TMT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Account__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account__c</fullName>
    <externalId>true</externalId>
    <label>SAP Account #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <inlineHelpText>Área diferenciada de la actividad económica y productiva en la que se engloba la empresa.</inlineHelpText>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Admón. Pública</fullName>
            </value>
            <value>
                <fullName>Educación</fullName>
            </value>
            <value>
                <fullName>Engineering and Architecture</fullName>
                <isActive>false</isActive>
                <label>Engineering and Architecture</label>
            </value>
            <value>
                <fullName>Financiero</fullName>
                <isActive>false</isActive>
                <label>Financiero</label>
            </value>
            <value>
                <fullName>Finanzas</fullName>
            </value>
            <value>
                <fullName>Industria</fullName>
            </value>
            <value>
                <fullName>Ingeniería Industrial</fullName>
            </value>
            <value>
                <fullName>Ingeniería y Arquitectura</fullName>
            </value>
            <value>
                <fullName>Sanidad</fullName>
            </value>
            <value>
                <fullName>Sector al que pertenece</fullName>
                <isActive>false</isActive>
                <label>Sector al que pertenece</label>
            </value>
            <value>
                <fullName>Sector Público</fullName>
                <isActive>false</isActive>
                <label>Sector Público</label>
            </value>
            <value>
                <fullName>Seguros</fullName>
            </value>
            <value>
                <fullName>Servicios</fullName>
            </value>
            <value>
                <fullName>Tecnologías de la información</fullName>
                <isActive>false</isActive>
                <label>Tecnologías de la información</label>
            </value>
            <value>
                <fullName>Telco y Media</fullName>
            </value>
            <value>
                <fullName>Utilities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Subsector__c.field-meta.xml
<CustomField>
    <fullName>Subsector__c</fullName>
    <inlineHelpText>Distinct activity within the sector the company is a part of.</inlineHelpText>
    <label>Subsector</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sector__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Administración Autonómica</fullName>
            </value>
            <value>
                <fullName>Administración Central</fullName>
            </value>
            <value>
                <fullName>Administración Latam</fullName>
            </value>
            <value>
                <fullName>Administración Local</fullName>
            </value>
            <value>
                <fullName>Aeroespacial</fullName>
            </value>
            <value>
                <fullName>Agroalimentaria</fullName>
            </value>
            <value>
                <fullName>Agua</fullName>
            </value>
            <value>
                <fullName>Alimentación bebidas y tabaco</fullName>
            </value>
            <value>
                <fullName>Automoción</fullName>
            </value>
            <value>
                <fullName>Bancos</fullName>
            </value>
            <value>
                <fullName>Cajas de Ahorros</fullName>
            </value>
            <value>
                <fullName>Calzado</fullName>
            </value>
            <value>
                <fullName>Carbón</fullName>
            </value>
            <value>
                <fullName>Centros de formación en gral.</fullName>
            </value>
            <value>
                <fullName>Centros de Investigación</fullName>
            </value>
            <value>
                <fullName>Comercio Minorista</fullName>
            </value>
            <value>
                <fullName>Compañías de Banca/Seguros</fullName>
            </value>
            <value>
                <fullName>Construcción</fullName>
            </value>
            <value>
                <fullName>Construcción/Promoción</fullName>
            </value>
            <value>
                <fullName>Construcciones Mecánicas</fullName>
            </value>
            <value>
                <fullName>Construcción Maquinaria</fullName>
            </value>
            <value>
                <fullName>Consultoría</fullName>
            </value>
            <value>
                <fullName>Contact Center</fullName>
            </value>
            <value>
                <fullName>Corredurías/Mediadoras</fullName>
            </value>
            <value>
                <fullName>Distribución</fullName>
            </value>
            <value>
                <fullName>Distribución y Logística</fullName>
            </value>
            <value>
                <fullName>Educación privada</fullName>
            </value>
            <value>
                <fullName>Electricidad</fullName>
            </value>
            <value>
                <fullName>Emp. TT.II. Relac.con Finanzas</fullName>
            </value>
            <value>
                <fullName>Emp. TT.II De la Admon.Autonó.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/No_ejecutar_triggers__c/No_ejecutar_triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>No ejecutar triggers</label>
</CustomObject>

force-app/main/default/objects/No_ejecutar_triggers__c/fields/Correo_usuario__c.field-meta.xml
<CustomField>
    <fullName>Correo_usuario__c</fullName>
    <label>Correo usuario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Objetivo__c/Objetivo__c.object-meta.xml
<CustomObject>
    <label>Objetivo</label>
    <nameField>
        <label>Objetivo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objetivos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Objetivo__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad / Oferta</label>
    <referenceTo>Oportunidad__c</referenceTo>
    <relationshipLabel>Objetivos</relationshipLabel>
    <relationshipName>Objetivos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/Oportunidad__c.object-meta.xml
<CustomObject>
    <label>Oportunidad</label>
    <nameField>
        <label>Tema</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Oportunidades</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Oportunidad__c/fields/Nombre_Corto__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Corto__c</fullName>
    <label>Título Oficial</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/recordTypes/Ayesa.recordType-meta.xml
<RecordType>
    <fullName>Ayesa</fullName>
    <active>true</active>
    <description>Flujo de Ayesa</description>
    <label>Ayesa</label>
</RecordType>

force-app/main/default/objects/Oportunidad__c/recordTypes/Ibermatica_Large_Account.recordType-meta.xml
<RecordType>
    <fullName>Ibermatica_Large_Account</fullName>
    <active>true</active>
    <description>Flujo de Ibermatica Large Account</description>
    <label>Ibermatica Large Account</label>
</RecordType>

force-app/main/default/objects/Parametrica_2__c/Parametrica_2__c.object-meta.xml
<CustomObject>
    <description>Parametrica que contiene los datos de Ibermatica</description>
    <label>Parametrica Ibermática</label>
    <nameField>
        <label>Nombre de Parametrica Ibermática</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parametricas Ibermática</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parametrica_2__c/fields/Organizacion__c.field-meta.xml
<CustomField>
    <fullName>Organizacion__c</fullName>
    <label>Organización</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Subsector__c.field-meta.xml
<CustomField>
    <fullName>Subsector__c</fullName>
    <label>Subsector</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/recordTypes/Sector.recordType-meta.xml
<RecordType>
    <fullName>Sector</fullName>
    <active>true</active>
    <label>Sector</label>
</RecordType>

force-app/main/default/objects/Referencia_Comercial__c/Referencia_Comercial__c.object-meta.xml
<CustomObject>
    <label>Referencia Comercial</label>
    <nameField>
        <label>Referencia Comercial Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referencias Comerciales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referencia_Comercial__c/fields/Organizacion__c.field-meta.xml
<CustomField>
    <fullName>Organizacion__c</fullName>
    <label>Organización</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BFSI</fullName>
            </value>
            <value>
                <fullName>CONSUMER</fullName>
            </value>
            <value>
                <fullName>DIGITAL ADMIN</fullName>
            </value>
            <value>
                <fullName>ENERGY &amp; UTILITIES</fullName>
            </value>
            <value>
                <fullName>GRUPO IBERMATICA</fullName>
            </value>
            <value>
                <fullName>HEALTH</fullName>
            </value>
            <value>
                <fullName>ILA ARGENTINA</fullName>
            </value>
            <value>
                <fullName>INTERFLEX</fullName>
            </value>
            <value>
                <fullName>MANUFACTURING</fullName>
            </value>
            <value>
                <fullName>MICROSOFT</fullName>
            </value>
            <value>
                <fullName>ONCE GROUP</fullName>
            </value>
            <value>
                <fullName>SCADA ARGENTINA</fullName>
            </value>
            <value>
                <fullName>SCADA CHILE</fullName>
            </value>
            <value>
                <fullName>SCADA PERU</fullName>
            </value>
            <value>
                <fullName>SMART FACTORIES</fullName>
            </value>
            <value>
                <fullName>TMT</fullName>
            </value>
            <value>
                <fullName>Nueva Org</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CRM_IB_MulesoftAPI_Test.cls
@isTest
public class CRM_IB_MulesoftAPI_Test {
    
    @isTest public  static void callApiMule() {
        
        No_ejecutar_triggers__c saltar_trigger = new No_ejecutar_triggers__c();
        saltar_trigger.Correo_usuario__c='soporteoaci@ayesa.com';
        insert saltar_trigger;
        
     	Id recordTypeId = Schema.SObjectType.Parametrica_2__c.getRecordTypeInfosByName().get('Organización').getRecordTypeId();
        Parametrica_2__c param = new Parametrica_2__c(Name='60049219', Organizacion__c = 'DIGITAL ADMINISTRATION', RecordTypeId = recordTypeId);
        insert param; 
        
        //Cuenta
        Account Cliente= new Account(Name='Cliente prueba', SAP_Account__c='5555', Alias__c='ClientePrueba',Sector__c= 'Educación', Subsector__c ='Centros de formación en gral.'); 
        insert Cliente;
        
        //Contacto
        Contact Contacto = new Contact (FirstName='Prueba',LastName ='Prueba', AccountId= Cliente.Id);
        insert contacto;
        
        //Oportunidad
        Id recordTypeIdLarge = Schema.SObjectType.Oportunidad__c.getRecordTypeInfosByDeveloperName().get('Ibermatica_Large_Account').getRecordTypeId();
        Oportunidad__c op= new Oportunidad__c(Nombre_Corto__c='Prueba',Name='Prueba', Cliente__c=Cliente.Id, RecordTypeId=recordTypeIdLarge, Tipo_Participacion_Ayesa__c='Contratista Principal', Sociedad_Ayesa__c='IB01',
                                             Clase_de_oferta__c='Licitación Pública', DivisionPicklist__c='60049219');
      //  insert op;
       
        
        Objetivo__c obj= new Objetivo__c(Name='Objetivo', Cuenta__c = Cliente.Id);
       // insert obj;
        
        referencia_comercial__c ref = new referencia_Comercial__c(Name = 'Referencia Prueba');
        insert ref;
        String path='';
        String requestJSON='{"operacion":"A", "idsector":"54b3d401-b2b6-ed11-83ff-0003a2e4fb","denominacion":"Sector Prueba", "estado":"0", "idorgcomercial":"4235345"}';
        
        CRM_Ibermatica_Configuration__c cs = new CRM_Ibermatica_Configuration__c();
        cs.client_id__c='test';
        cs.client_secret__c='test';
        
         insert cs;
        
        
        Test.startTest();
        
        
        
        
        //String result =CRM_IB_MulesoftAPI.callApiMule(String pathEndpoint, requestJSON, String method, Id idEntidad, String interfaz)	
   /*   CRM_IB_MulesoftAPI.superPreventaComprobacion(OP.Id);
        CRM_IB_MulesoftAPI.superPreventa(OP.Id);
        CRM_IB_MulesoftAPI.superPreventaObjetivo(obj.Id);
        CRM_IB_MulesoftAPI.newFile(op.Id);
        CRM_IB_MulesoftAPI.newFile(ref.Id);
        CRM_IB_MulesoftAPI.oportunidad_documentacion(op.Id);
        CRM_IB_MulesoftAPI.oportunidad_documentacion(ref.Id);*/
        CRM_IB_MulesoftAPI.test();
        Test.stopTest();
    }
}