force-app/main/default/objects/Account/fields/Alias__c.field-meta.xml
<CustomField>
    <fullName>Alias__c</fullName>
    <label>Alias</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Account_IB__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_IB__c</fullName>
    <externalId>true</externalId>
    <label>SAP Account IB #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <inlineHelpText>Área diferenciada de la actividad económica y productiva en la que se engloba la empresa.</inlineHelpText>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Admón. Pública</fullName>
            </value>
            <value>
                <fullName>Educación</fullName>
            </value>
            <value>
                <fullName>Engineering and Architecture</fullName>
                <isActive>false</isActive>
                <label>Engineering and Architecture</label>
            </value>
            <value>
                <fullName>Financiero</fullName>
                <isActive>false</isActive>
                <label>Financiero</label>
            </value>
            <value>
                <fullName>Finanzas</fullName>
            </value>
            <value>
                <fullName>Industria</fullName>
            </value>
            <value>
                <fullName>Ingeniería Industrial</fullName>
            </value>
            <value>
                <fullName>Ingeniería y Arquitectura</fullName>
            </value>
            <value>
                <fullName>Sanidad</fullName>
            </value>
            <value>
                <fullName>Sector al que pertenece</fullName>
                <isActive>false</isActive>
                <label>Sector al que pertenece</label>
            </value>
            <value>
                <fullName>Sector Público</fullName>
                <isActive>false</isActive>
                <label>Sector Público</label>
            </value>
            <value>
                <fullName>Seguros</fullName>
            </value>
            <value>
                <fullName>Servicios</fullName>
            </value>
            <value>
                <fullName>Tecnologías de la información</fullName>
                <isActive>false</isActive>
                <label>Tecnologías de la información</label>
            </value>
            <value>
                <fullName>Telco y Media</fullName>
            </value>
            <value>
                <fullName>Utilities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Subsector__c.field-meta.xml
<CustomField>
    <fullName>Subsector__c</fullName>
    <inlineHelpText>Distinct activity within the sector the company is a part of.</inlineHelpText>
    <label>Subsector</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sector__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Administración Autonómica</fullName>
            </value>
            <value>
                <fullName>Administración Central</fullName>
            </value>
            <value>
                <fullName>Administración Latam</fullName>
            </value>
            <value>
                <fullName>Administración Local</fullName>
            </value>
            <value>
                <fullName>Aeroespacial</fullName>
            </value>
            <value>
                <fullName>Agroalimentaria</fullName>
            </value>
            <value>
                <fullName>Agua</fullName>
            </value>
            <value>
                <fullName>Alimentación bebidas y tabaco</fullName>
            </value>
            <value>
                <fullName>Automoción</fullName>
            </value>
            <value>
                <fullName>Bancos</fullName>
            </value>
            <value>
                <fullName>Cajas de Ahorros</fullName>
            </value>
            <value>
                <fullName>Calzado</fullName>
            </value>
            <value>
                <fullName>Carbón</fullName>
            </value>
            <value>
                <fullName>Centros de formación en gral.</fullName>
            </value>
            <value>
                <fullName>Centros de Investigación</fullName>
            </value>
            <value>
                <fullName>Comercio Minorista</fullName>
            </value>
            <value>
                <fullName>Compañías de Banca/Seguros</fullName>
            </value>
            <value>
                <fullName>Construcción</fullName>
            </value>
            <value>
                <fullName>Construcción/Promoción</fullName>
            </value>
            <value>
                <fullName>Construcciones Mecánicas</fullName>
            </value>
            <value>
                <fullName>Construcción Maquinaria</fullName>
            </value>
            <value>
                <fullName>Consultoría</fullName>
            </value>
            <value>
                <fullName>Contact Center</fullName>
            </value>
            <value>
                <fullName>Corredurías/Mediadoras</fullName>
            </value>
            <value>
                <fullName>Distribución</fullName>
            </value>
            <value>
                <fullName>Distribución y Logística</fullName>
            </value>
            <value>
                <fullName>Educación privada</fullName>
            </value>
            <value>
                <fullName>Electricidad</fullName>
            </value>
            <value>
                <fullName>Emp. TT.II. Relac.con Finanzas</fullName>
            </value>
            <value>
                <fullName>Emp. TT.II De la Admon.Autonó.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CRM_Ibermatica_Configuration__c/CRM_Ibermatica_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CRM Ibermatica Configuration</label>
</CustomObject>

force-app/main/default/objects/CRM_Ibermatica_Configuration__c/fields/client_id__c.field-meta.xml
<CustomField>
    <fullName>client_id__c</fullName>
    <label>client-id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_Ibermatica_Configuration__c/fields/client_secret__c.field-meta.xml
<CustomField>
    <fullName>client_secret__c</fullName>
    <label>client-secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/No_ejecutar_triggers__c/No_ejecutar_triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>No ejecutar triggers</label>
</CustomObject>

force-app/main/default/objects/No_ejecutar_triggers__c/fields/Correo_usuario__c.field-meta.xml
<CustomField>
    <fullName>Correo_usuario__c</fullName>
    <label>Correo usuario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Objetivo__c/Objetivo__c.object-meta.xml
<CustomObject>
    <label>Objetivo</label>
    <nameField>
        <label>Objetivo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objetivos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Objetivo__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad / Oferta</label>
    <referenceTo>Oportunidad__c</referenceTo>
    <relationshipLabel>Objetivos</relationshipLabel>
    <relationshipName>Objetivos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/Oportunidad__c.object-meta.xml
<CustomObject>
    <label>Oportunidad</label>
    <nameField>
        <label>Tema</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Oportunidades</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Oportunidad__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/Nombre_Corto__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Corto__c</fullName>
    <label>Título Oficial</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/Sociedad_Ayesa__c.field-meta.xml
<CustomField>
    <fullName>Sociedad_Ayesa__c</fullName>
    <description>Sociedad del grupo Ayesa que presenta la oferta</description>
    <inlineHelpText>Company from the Ayesa Group that submits the bid</inlineHelpText>
    <label>Sociedad</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0002</fullName>
                <label>0002 - AYESA ENGINEERING S.A</label>
            </value>
            <value>
                <fullName>0003</fullName>
                <label>0003 - AYESA ING. Y ARQU., S.A.</label>
            </value>
            <value>
                <fullName>0004</fullName>
                <label>0004 - ALIA GESTION S.L.</label>
            </value>
            <value>
                <fullName>0005</fullName>
                <label>0005 - AYNOVA, S.A.U.</label>
            </value>
            <value>
                <fullName>0007</fullName>
                <label>0007 - ACT SISTEMAS, S.L.U.</label>
            </value>
            <value>
                <fullName>0012</fullName>
                <label>0012 - AYESA MDE, S.A.</label>
            </value>
            <value>
                <fullName>0018</fullName>
                <label>0018 - AYESA AIR CONTROL S.L.</label>
            </value>
            <value>
                <fullName>0021</fullName>
                <label>0021 - AYESA MEXICO,S.A. de C.V.</label>
            </value>
            <value>
                <fullName>0023</fullName>
                <label>0023 - AYESA SUCURSAL POLONIA</label>
            </value>
            <value>
                <fullName>0024</fullName>
                <label>0024 - AYESA POLSKA SP. Z O.O.</label>
            </value>
            <value>
                <fullName>0025</fullName>
                <label>0025 - AYESA MAROC, S.A.R.L</label>
            </value>
            <value>
                <fullName>0027</fullName>
                <label>0027 - AYESA IMPLEMEN. TECN. S.A</label>
            </value>
            <value>
                <fullName>0030</fullName>
                <label>0030 - AYESA ALGERIE S.A.R.L.</label>
            </value>
            <value>
                <fullName>0034</fullName>
                <label>0034 - AYESA SERVICIOS S RL DECV</label>
            </value>
            <value>
                <fullName>0035</fullName>
                <label>0035 - ALIA WORLDWIDE, S.L.</label>
            </value>
            <value>
                <fullName>0036</fullName>
                <label>0036 - AYESA BRANCH OFFICE</label>
            </value>
            <value>
                <fullName>0040</fullName>
                <label>0040 - AYESA ENGINYERIA SERVEIS</label>
            </value>
            <value>
                <fullName>0045</fullName>
                <label>0045 - ATECH ADVAN. SOL.</label>
            </value>
            <value>
                <fullName>0047</fullName>
                <label>0047 - ATECH BPO, S.L.</label>
            </value>
            <value>
                <fullName>0048</fullName>
                <label>0048 - UNITEC</label>
            </value>
            <value>
                <fullName>0049</fullName>
                <label>0049 - INSOTECH INTERNATIONAL</label>
            </value>
            <value>
                <fullName>0050</fullName>
                <label>0050 - AYESA PERÚ</label>
            </value>
            <value>
                <fullName>0053</fullName>
                <label>0053 - AYESA INDIA PRIVATE LIMIT</label>
            </value>
            <value>
                <fullName>0054</fullName>
                <label>0054 - AYESA COLOMBIA SAS</label>
            </value>
            <value>
                <fullName>0056</fullName>
                <label>0056 - AYESA PANAMÁ</label>
            </value>
            <value>
                <fullName>0057</fullName>
                <label>0057 - AAT PANAMÁ RUC</label>
            </value>
            <value>
                <fullName>0058</fullName>
                <label>0058 - AYESA PANAMÁ RUC</label>
            </value>
            <value>
                <fullName>0059</fullName>
                <label>0059 - AYESA COLOMBIA SUCURSAL</label>
            </value>
            <value>
                <fullName>0060</fullName>
                <label>0060 - AAT ECUADOR</label>
            </value>
            <value>
                <fullName>0061</fullName>
                <label>0061 - AYESA ECUADOR</label>
            </value>
            <value>
                <fullName>0170</fullName>
                <label>0170 - AYESA IBERMÁTICA, S.A.U.</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Oportunidad__c/recordTypes/Ibermatica_Large_Account.recordType-meta.xml
<RecordType>
    <fullName>Ibermatica_Large_Account</fullName>
    <active>true</active>
    <description>Flujo de Ibermatica Large Account</description>
    <label>Ibermatica Large Account</label>
</RecordType>

force-app/main/default/objects/Parametrica_2__c/Parametrica_2__c.object-meta.xml
<CustomObject>
    <description>Parametrica que contiene los datos de Ibermatica</description>
    <label>Parametrica Ibermática</label>
    <nameField>
        <label>Nombre de Parametrica Ibermática</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parametricas Ibermática</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parametrica_2__c/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Subsector__c.field-meta.xml
<CustomField>
    <fullName>Subsector__c</fullName>
    <label>Subsector</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CRM_IB_AltaModOppSUPER_Test.cls
@isTest
public class CRM_IB_AltaModOppSUPER_Test {
	
    @testSetup static void setup() {
        No_ejecutar_triggers__c saltar_trigger = new No_ejecutar_triggers__c();
        saltar_trigger.Correo_usuario__c='';
        insert saltar_trigger;
        Account cuenta= new Account(Name='Cliente prueba', SAP_Account_IB__c='5555',Sector__c='Admón. Pública', Subsector__c='Administración Latam', Alias__c='ClientePrueba');
        insert cuenta;   
        
        CRM_Ibermatica_Configuration__c cs = new CRM_Ibermatica_Configuration__c();
        cs.client_id__c='test';
        cs.client_secret__c='test';
        insert cs;
        
        Id recordTypeId = Schema.SObjectType.Parametrica_2__c.getRecordTypeInfosByName().get('Organización').getRecordTypeId();
        Parametrica_2__c param = new Parametrica_2__c(Name='60049219', RecordTypeId = recordTypeId);
        insert param;    
    }
    
    @isTest public static void altaModOportunidadOK(){

        Account cuenta = [SELECT Id FROM Account WHERE Name='Cliente prueba' LIMIT 1];
        
        Id recordTypeId = Schema.SObjectType.Oportunidad__c.getRecordTypeInfosByDeveloperName().get('Ibermatica_Large_Account').getRecordTypeId();
        Oportunidad__c op= new Oportunidad__c(Nombre_Corto__c='Prueba',Name='Prueba', Cliente__c=cuenta.Id, RecordTypeId=recordTypeId, Tipo_Participacion_Ayesa__c='Contratista Principal', Sociedad_Ayesa__c='0170',
                                             Clase_de_oferta__c='Licitación Pública');
        insert op;
        
    	List<Id> lIds = new List<Id>();
		lIds.add(op.Id);
		
        Test.setMock(HttpCalloutMock.class, new CRM_IB_AltaModOppSUPERMock());
        CRM_IB_AltaModOppSUPER.altaModOppSUPER(lIds);
    }
    
   	@isTest public static void altaModExtensionOK(){
			
        //TODO    
    } 
    
    
    @isTest public static void altaModObjetivoOK(){

		Account cuenta = [SELECT Id FROM Account WHERE Name='Cliente prueba' LIMIT 1];
        
		Objetivo__c obj = new Objetivo__c(Name='Objetivo Prueba', CurrencyIsoCode='EUR', Cuenta__c=cuenta.Id, Desc_objetivo__c='Prueba', Fecha_ini__c= date.newInstance(2017, 11, 11), 
                                          Fecha_max__c=date.newInstance(2018,11,11), Estado__c='V', Tipo_de_Negocio__c='Nuevo Cliente',Oferta__c='BPS');
        
        insert obj;
        
    	List<Id> lIds = new List<Id>();
		lIds.add(obj.Id);
		
        Test.setMock(HttpCalloutMock.class, new CRM_IB_AltaModOppSUPERMock());
        CRM_IB_AltaModOppSUPER.altaModOppSUPER(lIds);
    }
}