force-app/main/default/objects/Account/fields/Alias__c.field-meta.xml
<CustomField>
    <fullName>Alias__c</fullName>
    <label>Alias</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <label>País</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afganistán</fullName>
                <isActive>false</isActive>
                <label>Afganistán</label>
            </value>
            <value>
                <fullName>DE</fullName>
                <label>Alemania</label>
            </value>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>SA</fullName>
                <label>Arabia Saudí</label>
            </value>
            <value>
                <fullName>DZ</fullName>
                <label>Argelia</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaiyán</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrein</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Bélgica</label>
            </value>
            <value>
                <fullName>BY</fullName>
                <label>Bielorrusia</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brasil</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>Canadá</label>
            </value>
            <value>
                <fullName>CL</fullName>
                <label>Chile</label>
            </value>
            <value>
                <fullName>CN</fullName>
                <label>China</label>
            </value>
            <value>
                <fullName>CO</fullName>
                <label>Colombia</label>
            </value>
            <value>
                <fullName>Corea</fullName>
            </value>
            <value>
                <fullName>Corea del Sur</fullName>
                <isActive>false</isActive>
                <label>Corea del Sur</label>
            </value>
            <value>
                <fullName>CI</fullName>
                <label>Costa de Marfil</label>
            </value>
            <value>
                <fullName>CR</fullName>
                <label>Costa Rica</label>
            </value>
            <value>
                <fullName>HR</fullName>
                <label>Croacia</label>
            </value>
            <value>
                <fullName>CU</fullName>
                <label>Cuba</label>
            </value>
            <value>
                <fullName>DK</fullName>
                <label>Dinamarca</label>
            </value>
            <value>
                <fullName>Dominica</fullName>
                <isActive>false</isActive>
                <label>Dominica</label>
            </value>
            <value>
                <fullName>E.A.U.</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
                <label>España</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Account__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account__c</fullName>
    <externalId>true</externalId>
    <label>SAP Account #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <inlineHelpText>Área diferenciada de la actividad económica y productiva en la que se engloba la empresa.</inlineHelpText>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Admón. Pública</fullName>
            </value>
            <value>
                <fullName>Educación</fullName>
            </value>
            <value>
                <fullName>Engineering and Architecture</fullName>
                <isActive>false</isActive>
                <label>Engineering and Architecture</label>
            </value>
            <value>
                <fullName>Financiero</fullName>
                <isActive>false</isActive>
                <label>Financiero</label>
            </value>
            <value>
                <fullName>Finanzas</fullName>
            </value>
            <value>
                <fullName>Industria</fullName>
            </value>
            <value>
                <fullName>Ingeniería Industrial</fullName>
            </value>
            <value>
                <fullName>Ingeniería y Arquitectura</fullName>
            </value>
            <value>
                <fullName>Sanidad</fullName>
            </value>
            <value>
                <fullName>Sector al que pertenece</fullName>
                <isActive>false</isActive>
                <label>Sector al que pertenece</label>
            </value>
            <value>
                <fullName>Sector Público</fullName>
                <isActive>false</isActive>
                <label>Sector Público</label>
            </value>
            <value>
                <fullName>Seguros</fullName>
            </value>
            <value>
                <fullName>Servicios</fullName>
            </value>
            <value>
                <fullName>Tecnologías de la información</fullName>
                <isActive>false</isActive>
                <label>Tecnologías de la información</label>
            </value>
            <value>
                <fullName>Telco y Media</fullName>
            </value>
            <value>
                <fullName>Utilities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sector_text__c.field-meta.xml
<CustomField>
    <fullName>Sector_text__c</fullName>
    <label>Sector IB</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Subsector__c.field-meta.xml
<CustomField>
    <fullName>Subsector__c</fullName>
    <inlineHelpText>Distinct activity within the sector the company is a part of.</inlineHelpText>
    <label>Subsector</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sector__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Administración Autonómica</fullName>
            </value>
            <value>
                <fullName>Administración Central</fullName>
            </value>
            <value>
                <fullName>Administración Latam</fullName>
            </value>
            <value>
                <fullName>Administración Local</fullName>
            </value>
            <value>
                <fullName>Aeroespacial</fullName>
            </value>
            <value>
                <fullName>Agroalimentaria</fullName>
            </value>
            <value>
                <fullName>Agua</fullName>
            </value>
            <value>
                <fullName>Alimentación bebidas y tabaco</fullName>
            </value>
            <value>
                <fullName>Automoción</fullName>
            </value>
            <value>
                <fullName>Bancos</fullName>
            </value>
            <value>
                <fullName>Cajas de Ahorros</fullName>
            </value>
            <value>
                <fullName>Calzado</fullName>
            </value>
            <value>
                <fullName>Carbón</fullName>
            </value>
            <value>
                <fullName>Centros de formación en gral.</fullName>
            </value>
            <value>
                <fullName>Centros de Investigación</fullName>
            </value>
            <value>
                <fullName>Comercio Minorista</fullName>
            </value>
            <value>
                <fullName>Compañías de Banca/Seguros</fullName>
            </value>
            <value>
                <fullName>Construcción</fullName>
            </value>
            <value>
                <fullName>Construcción/Promoción</fullName>
            </value>
            <value>
                <fullName>Construcciones Mecánicas</fullName>
            </value>
            <value>
                <fullName>Construcción Maquinaria</fullName>
            </value>
            <value>
                <fullName>Consultoría</fullName>
            </value>
            <value>
                <fullName>Contact Center</fullName>
            </value>
            <value>
                <fullName>Corredurías/Mediadoras</fullName>
            </value>
            <value>
                <fullName>Distribución</fullName>
            </value>
            <value>
                <fullName>Distribución y Logística</fullName>
            </value>
            <value>
                <fullName>Educación privada</fullName>
            </value>
            <value>
                <fullName>Electricidad</fullName>
            </value>
            <value>
                <fullName>Emp. TT.II. Relac.con Finanzas</fullName>
            </value>
            <value>
                <fullName>Emp. TT.II De la Admon.Autonó.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Subsector_texto__c.field-meta.xml
<CustomField>
    <fullName>Subsector_texto__c</fullName>
    <label>Subsector IB</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/No_ejecutar_triggers__c/No_ejecutar_triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>No ejecutar triggers</label>
</CustomObject>

force-app/main/default/objects/No_ejecutar_triggers__c/fields/Correo_usuario__c.field-meta.xml
<CustomField>
    <fullName>Correo_usuario__c</fullName>
    <label>Correo usuario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/Parametrica_2__c.object-meta.xml
<CustomObject>
    <description>Parametrica que contiene los datos de Ibermatica</description>
    <label>Parametrica Ibermática</label>
    <nameField>
        <label>Nombre de Parametrica Ibermática</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parametricas Ibermática</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parametrica_2__c/fields/Codigo_Externo__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Externo__c</fullName>
    <label>Codigo Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Denominacion__c.field-meta.xml
<CustomField>
    <fullName>Denominacion__c</fullName>
    <label>Denominacion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pais</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Parametrica_2__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Paises</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Parametrica_2__c</referenceTo>
    <relationshipLabel>Parametricas Ibermática (Pais)</relationshipLabel>
    <relationshipName>Pais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Subsector__c.field-meta.xml
<CustomField>
    <fullName>Subsector__c</fullName>
    <label>Subsector</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/recordTypes/Paises.recordType-meta.xml
<RecordType>
    <fullName>Paises</fullName>
    <active>true</active>
    <label>Paises</label>
</RecordType>

force-app/main/default/objects/Parametrica_2__c/recordTypes/Provincias.recordType-meta.xml
<RecordType>
    <fullName>Provincias</fullName>
    <active>true</active>
    <label>Provincias</label>
</RecordType>

force-app/main/default/classes/CRM_IB_Account_Address_Test.cls
@isTest
public class CRM_IB_Account_Address_Test {
    @isTest
    public static void allTest(){
        No_ejecutar_triggers__c saltar_trigger = new No_ejecutar_triggers__c();
        saltar_trigger.Correo_usuario__c='';
        insert saltar_trigger;
    //Cuenta
        Account Cliente= new Account(Name='Cliente prueba', SAP_Account__c='5555',Sector__c='Admón. Pública', Subsector__c='Administración Latam',Sector_text__c='Admón. Pública', Subsector_texto__c='Administración Latam', Alias__c='ClientePrueba');
        insert Cliente;
     //Pais
         Id RT_Pais = Schema.SObjectType.Parametrica_2__c.getRecordTypeInfosByName().get('Paises').getRecordTypeId();
        Id RT_Provincia = Schema.SObjectType.Parametrica_2__c.getRecordTypeInfosByName().get('Provincias').getRecordTypeId();
        
        Parametrica_2__c Pais = new Parametrica_2__c (Name ='Pais', Denominacion__c ='España', Codigo_Externo__c ='ES', RecordTypeId=RT_Pais);
        insert Pais;
        Parametrica_2__c Provincia = new Parametrica_2__c (Name ='Provincia', Denominacion__c ='Sevilla', Codigo_Externo__c ='01', Pais__c=Pais.Id,RecordTypeId=RT_Provincia);
        insert Provincia;
        String test1 = CRM_IB_Account_Address_controller.countryProvinceMap(Cliente.Id);
        
        List <String> test2 = CRM_IB_Account_Address_controller.provinceOptions('España');
            
        String test3 = CRM_IB_Account_Address_controller.saveAccountCountry('España', 'Sevilla', 'Sevilla', 'Calle Sierpes', '41018', Cliente.Id);
        
    }

}