force-app/main/default/objects/Account/fields/Alias__c.field-meta.xml
<CustomField>
    <fullName>Alias__c</fullName>
    <label>Alias</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Divisa__c.field-meta.xml
<CustomField>
    <fullName>Divisa__c</fullName>
    <description>Tiene que tener los mismo registros que el campo divisa de la entidad Oportunidad.</description>
    <label>Divisa</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Balboa</fullName>
            </value>
            <value>
                <fullName>Dolar</fullName>
            </value>
            <value>
                <fullName>Euro</fullName>
            </value>
            <value>
                <fullName>Nuevo Sol</fullName>
            </value>
            <value>
                <fullName>Peso(CLP)</fullName>
            </value>
            <value>
                <fullName>Peso (COP)</fullName>
            </value>
            <value>
                <fullName>Peso(MXN)</fullName>
            </value>
            <value>
                <fullName>Pound Sterling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Account__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account__c</fullName>
    <externalId>true</externalId>
    <label>SAP Account #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <inlineHelpText>Área diferenciada de la actividad económica y productiva en la que se engloba la empresa.</inlineHelpText>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Admón. Pública</fullName>
            </value>
            <value>
                <fullName>Educación</fullName>
            </value>
            <value>
                <fullName>Engineering and Architecture</fullName>
                <isActive>false</isActive>
                <label>Engineering and Architecture</label>
            </value>
            <value>
                <fullName>Financiero</fullName>
                <isActive>false</isActive>
                <label>Financiero</label>
            </value>
            <value>
                <fullName>Finanzas</fullName>
            </value>
            <value>
                <fullName>Industria</fullName>
            </value>
            <value>
                <fullName>Ingeniería Industrial</fullName>
            </value>
            <value>
                <fullName>Ingeniería y Arquitectura</fullName>
            </value>
            <value>
                <fullName>Sanidad</fullName>
            </value>
            <value>
                <fullName>Sector al que pertenece</fullName>
                <isActive>false</isActive>
                <label>Sector al que pertenece</label>
            </value>
            <value>
                <fullName>Sector Público</fullName>
                <isActive>false</isActive>
                <label>Sector Público</label>
            </value>
            <value>
                <fullName>Seguros</fullName>
            </value>
            <value>
                <fullName>Servicios</fullName>
            </value>
            <value>
                <fullName>Tecnologías de la información</fullName>
                <isActive>false</isActive>
                <label>Tecnologías de la información</label>
            </value>
            <value>
                <fullName>Telco y Media</fullName>
            </value>
            <value>
                <fullName>Utilities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Subsector__c.field-meta.xml
<CustomField>
    <fullName>Subsector__c</fullName>
    <inlineHelpText>Distinct activity within the sector the company is a part of.</inlineHelpText>
    <label>Subsector</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sector__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Administración Autonómica</fullName>
            </value>
            <value>
                <fullName>Administración Central</fullName>
            </value>
            <value>
                <fullName>Administración Latam</fullName>
            </value>
            <value>
                <fullName>Administración Local</fullName>
            </value>
            <value>
                <fullName>Aeroespacial</fullName>
            </value>
            <value>
                <fullName>Agroalimentaria</fullName>
            </value>
            <value>
                <fullName>Agua</fullName>
            </value>
            <value>
                <fullName>Alimentación bebidas y tabaco</fullName>
            </value>
            <value>
                <fullName>Automoción</fullName>
            </value>
            <value>
                <fullName>Bancos</fullName>
            </value>
            <value>
                <fullName>Cajas de Ahorros</fullName>
            </value>
            <value>
                <fullName>Calzado</fullName>
            </value>
            <value>
                <fullName>Carbón</fullName>
            </value>
            <value>
                <fullName>Centros de formación en gral.</fullName>
            </value>
            <value>
                <fullName>Centros de Investigación</fullName>
            </value>
            <value>
                <fullName>Comercio Minorista</fullName>
            </value>
            <value>
                <fullName>Compañías de Banca/Seguros</fullName>
            </value>
            <value>
                <fullName>Construcción</fullName>
            </value>
            <value>
                <fullName>Construcción/Promoción</fullName>
            </value>
            <value>
                <fullName>Construcciones Mecánicas</fullName>
            </value>
            <value>
                <fullName>Construcción Maquinaria</fullName>
            </value>
            <value>
                <fullName>Consultoría</fullName>
            </value>
            <value>
                <fullName>Contact Center</fullName>
            </value>
            <value>
                <fullName>Corredurías/Mediadoras</fullName>
            </value>
            <value>
                <fullName>Distribución</fullName>
            </value>
            <value>
                <fullName>Distribución y Logística</fullName>
            </value>
            <value>
                <fullName>Educación privada</fullName>
            </value>
            <value>
                <fullName>Electricidad</fullName>
            </value>
            <value>
                <fullName>Emp. TT.II. Relac.con Finanzas</fullName>
            </value>
            <value>
                <fullName>Emp. TT.II De la Admon.Autonó.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CRM_Ibermatica_Configuration__c/CRM_Ibermatica_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CRM Ibermatica Configuration</label>
</CustomObject>

force-app/main/default/objects/CRM_Ibermatica_Configuration__c/fields/client_id__c.field-meta.xml
<CustomField>
    <fullName>client_id__c</fullName>
    <label>client-id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_Ibermatica_Configuration__c/fields/client_secret__c.field-meta.xml
<CustomField>
    <fullName>client_secret__c</fullName>
    <label>client-secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_Ibermatica_Configuration__c/fields/URL_Consulta_New_File__c.field-meta.xml
<CustomField>
    <fullName>URL_Consulta_New_File__c</fullName>
    <label>URL Consulta New File</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_Ibermatica_Configuration__c/fields/URL_Existe_Doc_New_File__c.field-meta.xml
<CustomField>
    <fullName>URL_Existe_Doc_New_File__c</fullName>
    <label>URL Existe Doc New File</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_Ibermatica_Configuration__c/fields/URL_Preventa__c.field-meta.xml
<CustomField>
    <fullName>URL_Preventa__c</fullName>
    <label>URL Preventa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/No_ejecutar_triggers__c/No_ejecutar_triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>No ejecutar triggers</label>
</CustomObject>

force-app/main/default/objects/No_ejecutar_triggers__c/fields/Correo_usuario__c.field-meta.xml
<CustomField>
    <fullName>Correo_usuario__c</fullName>
    <label>Correo usuario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Objetivo__c/Objetivo__c.object-meta.xml
<CustomObject>
    <label>Objetivo</label>
    <nameField>
        <label>Objetivo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objetivos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Objetivo__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Objetivos</relationshipLabel>
    <relationshipName>Objetivos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Objetivo__c/fields/Desc_objetivo__c.field-meta.xml
<CustomField>
    <fullName>Desc_objetivo__c</fullName>
    <label>Descripción objetivo</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Objetivo__c/fields/Divisa__c.field-meta.xml
<CustomField>
    <fullName>Divisa__c</fullName>
    <label>Divisa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CLP</fullName>
                <label>Peso chileno</label>
            </value>
            <value>
                <fullName>PLN</fullName>
                <label>Esloti (PLN)</label>
            </value>
            <value>
                <fullName>ARS</fullName>
                <label>Peso Argentino</label>
            </value>
            <value>
                <fullName>PAB</fullName>
                <label>Balboa</label>
            </value>
            <value>
                <fullName>EUR</fullName>
                <default>true</default>
                <label>Euro</label>
            </value>
            <value>
                <fullName>COP</fullName>
                <label>Peso colombiano</label>
            </value>
            <value>
                <fullName>GBP</fullName>
                <label>Libra</label>
            </value>
            <value>
                <fullName>MXN</fullName>
                <label>Peso mexicano</label>
            </value>
            <value>
                <fullName>BHD</fullName>
                <label>Dinar Bahreini</label>
            </value>
            <value>
                <fullName>AED</fullName>
                <label>Arab Emirates Dirham (AED)</label>
            </value>
            <value>
                <fullName>SAR</fullName>
                <label>Saudi Riyal</label>
            </value>
            <value>
                <fullName>BRL</fullName>
                <label>Real brasileño</label>
            </value>
            <value>
                <fullName>PEN</fullName>
                <label>Sol</label>
            </value>
            <value>
                <fullName>USD</fullName>
                <label>Dolar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Objetivo__c/fields/Fecha_ini__c.field-meta.xml
<CustomField>
    <fullName>Fecha_ini__c</fullName>
    <label>Fecha Inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Objetivo__c/fields/Fecha_max__c.field-meta.xml
<CustomField>
    <fullName>Fecha_max__c</fullName>
    <label>Fecha Max</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Objetivo__c/fields/Oferta__c.field-meta.xml
<CustomField>
    <fullName>Oferta__c</fullName>
    <label>Oferta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BPS</fullName>
            </value>
            <value>
                <fullName>Cybersecurity</fullName>
            </value>
            <value>
                <fullName>DAA</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Digital-Latam</fullName>
            </value>
            <value>
                <fullName>Hybrid IT</fullName>
            </value>
            <value>
                <fullName>ITO</fullName>
            </value>
            <value>
                <fullName>Microsoft</fullName>
            </value>
            <value>
                <fullName>SAP</fullName>
            </value>
            <value>
                <fullName>Smart Factories</fullName>
            </value>
            <value>
                <fullName>SW Devep.</fullName>
            </value>
            <value>
                <fullName>Saleforce</fullName>
            </value>
            <value>
                <fullName>Oferta Base</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ObjetivoTrigger_Test.cls
@isTest
public class ObjetivoTrigger_Test {
    
    @testSetup static void setup() {
        
        No_ejecutar_triggers__c saltar_trigger = new No_ejecutar_triggers__c();
        saltar_trigger.Correo_usuario__c='';
        insert saltar_trigger;
        Account cuenta= new Account(Name='Cliente prueba', SAP_Account__c='5555', Alias__c='ClientePrueba',Sector__c= 'Educación', Subsector__c ='Centros de formación en gral.');
        insert cuenta;
        insert new CRM_Ibermatica_Configuration__c(client_id__c = '12345', client_secret__c='453345',URL_Consulta_New_File__c='http://test.com', URL_Existe_Doc_New_File__c='http://test.com',URL_Preventa__c='http://test.com');
    }
        
    @isTest
    public static void testObjetivoIbermatica() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new CRM_IB_AltaModOppSUPERMock());
        Account cuenta = [SELECT Id FROM Account WHERE Name='Cliente prueba' LIMIT 1];
        
        Objetivo__c obj = new Objetivo__c(Name='Prueba', Cuenta__c=cuenta.Id, Desc_objetivo__c='Desc Objetivo', Fecha_ini__c=Date.newInstance(2023, 1, 1), Fecha_max__c=Date.newInstance(2024, 1, 1), Divisa__c = 'USD');
        insert obj;
        
        obj.Divisa__c = 'EUR';
        update obj;
        delete obj;
        Test.stopTest();
    } 
}
//'Oferta__c',