force-app/main/default/objects/Account/fields/Alias__c.field-meta.xml
<CustomField>
    <fullName>Alias__c</fullName>
    <label>Alias</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Account_IB__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_IB__c</fullName>
    <externalId>true</externalId>
    <label>SAP Account IB #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sector_text__c.field-meta.xml
<CustomField>
    <fullName>Sector_text__c</fullName>
    <label>Sector IB</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Subsector_texto__c.field-meta.xml
<CustomField>
    <fullName>Subsector_texto__c</fullName>
    <label>Subsector IB</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_Ibermatica_Configuration__c/CRM_Ibermatica_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CRM Ibermatica Configuration</label>
</CustomObject>

force-app/main/default/objects/CRM_Ibermatica_Configuration__c/fields/client_id__c.field-meta.xml
<CustomField>
    <fullName>client_id__c</fullName>
    <label>client-id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_Ibermatica_Configuration__c/fields/client_secret__c.field-meta.xml
<CustomField>
    <fullName>client_secret__c</fullName>
    <label>client-secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_Ibermatica_Configuration__c/fields/URL_Consulta_New_File__c.field-meta.xml
<CustomField>
    <fullName>URL_Consulta_New_File__c</fullName>
    <label>URL Consulta New File</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_Ibermatica_Configuration__c/fields/URL_Existe_Doc_New_File__c.field-meta.xml
<CustomField>
    <fullName>URL_Existe_Doc_New_File__c</fullName>
    <label>URL Existe Doc New File</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_Ibermatica_Configuration__c/fields/URL_Preventa__c.field-meta.xml
<CustomField>
    <fullName>URL_Preventa__c</fullName>
    <label>URL Preventa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/No_ejecutar_triggers__c/No_ejecutar_triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>No ejecutar triggers</label>
</CustomObject>

force-app/main/default/objects/No_ejecutar_triggers__c/fields/Correo_usuario__c.field-meta.xml
<CustomField>
    <fullName>Correo_usuario__c</fullName>
    <label>Correo usuario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/Oportunidad__c.object-meta.xml
<CustomObject>
    <label>Oportunidad</label>
    <nameField>
        <label>Tema</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Oportunidades</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Oportunidad__c/fields/Clase_de_oferta__c.field-meta.xml
<CustomField>
    <fullName>Clase_de_oferta__c</fullName>
    <label>Clase de oferta</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>-</fullName>
                <isActive>false</isActive>
                <label>-</label>
            </value>
            <value>
                <fullName>Acuerdo Marco</fullName>
                <isActive>false</isActive>
                <label>Acuerdo Marco / SDA</label>
            </value>
            <value>
                <fullName>Acuerdo Marco Privado</fullName>
                <label>Acuerdo Marco / SDA Privado</label>
            </value>
            <value>
                <fullName>Acuerdo Marco Público</fullName>
                <label>Acuerdo Marco / SDA Público</label>
            </value>
            <value>
                <fullName>Ampliación de Contrato</fullName>
            </value>
            <value>
                <fullName>Información Previa</fullName>
            </value>
            <value>
                <fullName>Invitación Acuerdo Marco</fullName>
                <label>Invitación Acuerdo Marco / SDA</label>
            </value>
            <value>
                <fullName>Invitación Pública</fullName>
            </value>
            <value>
                <fullName>Licitación Pública</fullName>
            </value>
            <value>
                <fullName>Oferta interco</fullName>
            </value>
            <value>
                <fullName>Petición EOI / Pre-Calificación</fullName>
            </value>
            <value>
                <fullName>Privada</fullName>
            </value>
            <value>
                <fullName>Pública</fullName>
            </value>
            <value>
                <fullName>Registro Proveedores</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/Nombre_Corto__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Corto__c</fullName>
    <label>Título Oficial</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/Sociedad_Ayesa__c.field-meta.xml
<CustomField>
    <fullName>Sociedad_Ayesa__c</fullName>
    <description>Sociedad del grupo Ayesa que presenta la oferta</description>
    <inlineHelpText>Company from the Ayesa Group that submits the bid</inlineHelpText>
    <label>Sociedad</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0002</fullName>
                <label>0002 - AYESA ENGINEERING S.A</label>
            </value>
            <value>
                <fullName>0003</fullName>
                <label>0003 - AYESA ING. Y ARQU., S.A.</label>
            </value>
            <value>
                <fullName>0004</fullName>
                <label>0004 - ALIA GESTION S.L.</label>
            </value>
            <value>
                <fullName>0005</fullName>
                <label>0005 - AYNOVA, S.A.U.</label>
            </value>
            <value>
                <fullName>0007</fullName>
                <label>0007 - ACT SISTEMAS, S.L.U.</label>
            </value>
            <value>
                <fullName>0012</fullName>
                <label>0012 - AYESA MDE, S.A.</label>
            </value>
            <value>
                <fullName>0018</fullName>
                <label>0018 - AYESA AIR CONTROL S.L.</label>
            </value>
            <value>
                <fullName>0021</fullName>
                <label>0021 - AYESA MEXICO,S.A. de C.V.</label>
            </value>
            <value>
                <fullName>0023</fullName>
                <label>0023 - AYESA SUCURSAL POLONIA</label>
            </value>
            <value>
                <fullName>0024</fullName>
                <label>0024 - AYESA POLSKA SP. Z O.O.</label>
            </value>
            <value>
                <fullName>0025</fullName>
                <label>0025 - AYESA MAROC, S.A.R.L</label>
            </value>
            <value>
                <fullName>0027</fullName>
                <label>0027 - AYESA IMPLEMEN. TECN. S.A</label>
            </value>
            <value>
                <fullName>0030</fullName>
                <label>0030 - AYESA ALGERIE S.A.R.L.</label>
            </value>
            <value>
                <fullName>0034</fullName>
                <label>0034 - AYESA SERVICIOS S RL DECV</label>
            </value>
            <value>
                <fullName>0035</fullName>
                <label>0035 - ALIA WORLDWIDE, S.L.</label>
            </value>
            <value>
                <fullName>0036</fullName>
                <label>0036 - AYESA BRANCH OFFICE</label>
            </value>
            <value>
                <fullName>0040</fullName>
                <label>0040 - AYESA ENGINYERIA SERVEIS</label>
            </value>
            <value>
                <fullName>0045</fullName>
                <label>0045 - ATECH ADVAN. SOL.</label>
            </value>
            <value>
                <fullName>0047</fullName>
                <label>0047 - ATECH BPO, S.L.</label>
            </value>
            <value>
                <fullName>0048</fullName>
                <label>0048 - UNITEC</label>
            </value>
            <value>
                <fullName>0049</fullName>
                <label>0049 - INSOTECH INTERNATIONAL</label>
            </value>
            <value>
                <fullName>0050</fullName>
                <label>0050 - AYESA PERÚ</label>
            </value>
            <value>
                <fullName>0053</fullName>
                <label>0053 - AYESA INDIA PRIVATE LIMIT</label>
            </value>
            <value>
                <fullName>0054</fullName>
                <label>0054 - AYESA COLOMBIA SAS</label>
            </value>
            <value>
                <fullName>0056</fullName>
                <label>0056 - AYESA PANAMÁ</label>
            </value>
            <value>
                <fullName>0057</fullName>
                <label>0057 - AAT PANAMÁ RUC</label>
            </value>
            <value>
                <fullName>0058</fullName>
                <label>0058 - AYESA PANAMÁ RUC</label>
            </value>
            <value>
                <fullName>0059</fullName>
                <label>0059 - AYESA COLOMBIA SUCURSAL</label>
            </value>
            <value>
                <fullName>0060</fullName>
                <label>0060 - AAT ECUADOR</label>
            </value>
            <value>
                <fullName>0061</fullName>
                <label>0061 - AYESA ECUADOR</label>
            </value>
            <value>
                <fullName>0170</fullName>
                <label>0170 - AYESA IBERMÁTICA, S.A.U.</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Oportunidad__c/recordTypes/Ibermatica_Large_Account.recordType-meta.xml
<RecordType>
    <fullName>Ibermatica_Large_Account</fullName>
    <active>true</active>
    <description>Flujo de Ibermatica Large Account</description>
    <label>Ibermatica Large Account</label>
</RecordType>

force-app/main/default/objects/Referencia_Comercial__c/Referencia_Comercial__c.object-meta.xml
<CustomObject>
    <label>Referencia Comercial</label>
    <nameField>
        <label>Referencia Comercial Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referencias Comerciales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CRM_IB_ExisteDocNewFile_Test.cls
@isTest
public class CRM_IB_ExisteDocNewFile_Test {
	
    @testSetup 
    static void setup() {
        No_ejecutar_triggers__c saltar_trigger = new No_ejecutar_triggers__c();
        saltar_trigger.Correo_usuario__c='';
        insert saltar_trigger;
        Account cuenta= new Account(Name='Cliente prueba', SAP_Account_IB__c='5555',Sector_text__c='Sector Público', Subsector_texto__c='Administración Latam', Alias__c='ClientePrueba');
        insert cuenta;   
        
        insert new CRM_Ibermatica_Configuration__c(client_id__c = '12345', client_secret__c='453345',URL_Consulta_New_File__c='http://test.com', URL_Existe_Doc_New_File__c='http://test.com',URL_Preventa__c='http://test.com');
        

        
        Id recordTypeId = Schema.SObjectType.Oportunidad__c.getRecordTypeInfosByDeveloperName().get('Ibermatica_Large_Account').getRecordTypeId();
        Oportunidad__c op= new Oportunidad__c(Nombre_Corto__c='Prueba',Name='Prueba', Cliente__c=cuenta.Id, RecordTypeId=recordTypeId, Tipo_Participacion_Ayesa__c='Contratista Principal', Sociedad_Ayesa__c='0170',
                                             Clase_de_oferta__c='Licitación Pública');
        insert op;
        
        Referencia_Comercial__c rc = new Referencia_Comercial__c(Name='Ref. Com. Prueba');
        insert rc;
    }
    
    
    @isTest 
    public static void existeDocOpp() {
        System.debug('Inicio existeDocOpp');
        Oportunidad__c op = [SELECT Id FROM Oportunidad__c WHERE Name='Prueba' LIMIT 1];
		
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new CRM_IB_ExisteDocNewFileMock());
        CRM_IB_ExisteDocNewFile.existeDocNewFile(op.Id, '1,2','or');
       CRM_IB_Consulta_Doc_Controller.consulta_doc_New_File(op.Id);
        
        Test.stopTest();
        System.debug('Fin existeDocOpp');
        
    }
    
    
   	@isTest 
    public static void existeDocRefCom() {       
        System.debug('Inicio existeDocRefCom');
        Referencia_Comercial__c rc = [SELECT Id FROM Referencia_Comercial__c WHERE Name='Ref. Com. Prueba' LIMIT 1];
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new CRM_IB_ExisteDocNewFileMock());
        CRM_IB_ExisteDocNewFile.existeDocNewFile(rc.Id, '6','or');
        CRM_IB_Consulta_Doc_Controller.consulta_doc_New_File(rc.Id);
        Test.stopTest();
        System.debug('Fin existeDocRefCom');
    }
    
}