force-app/main/default/objects/Account/fields/Alias__c.field-meta.xml
<CustomField>
    <fullName>Alias__c</fullName>
    <label>Alias</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Account__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account__c</fullName>
    <externalId>true</externalId>
    <label>SAP Account #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <inlineHelpText>Área diferenciada de la actividad económica y productiva en la que se engloba la empresa.</inlineHelpText>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Admón. Pública</fullName>
            </value>
            <value>
                <fullName>Educación</fullName>
            </value>
            <value>
                <fullName>Engineering and Architecture</fullName>
                <isActive>false</isActive>
                <label>Engineering and Architecture</label>
            </value>
            <value>
                <fullName>Financiero</fullName>
                <isActive>false</isActive>
                <label>Financiero</label>
            </value>
            <value>
                <fullName>Finanzas</fullName>
            </value>
            <value>
                <fullName>Industria</fullName>
            </value>
            <value>
                <fullName>Ingeniería Industrial</fullName>
            </value>
            <value>
                <fullName>Ingeniería y Arquitectura</fullName>
            </value>
            <value>
                <fullName>Sanidad</fullName>
            </value>
            <value>
                <fullName>Sector al que pertenece</fullName>
                <isActive>false</isActive>
                <label>Sector al que pertenece</label>
            </value>
            <value>
                <fullName>Sector Público</fullName>
                <isActive>false</isActive>
                <label>Sector Público</label>
            </value>
            <value>
                <fullName>Seguros</fullName>
            </value>
            <value>
                <fullName>Servicios</fullName>
            </value>
            <value>
                <fullName>Tecnologías de la información</fullName>
                <isActive>false</isActive>
                <label>Tecnologías de la información</label>
            </value>
            <value>
                <fullName>Telco y Media</fullName>
            </value>
            <value>
                <fullName>Utilities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sector_text__c.field-meta.xml
<CustomField>
    <fullName>Sector_text__c</fullName>
    <label>Sector IB</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Subsector__c.field-meta.xml
<CustomField>
    <fullName>Subsector__c</fullName>
    <inlineHelpText>Distinct activity within the sector the company is a part of.</inlineHelpText>
    <label>Subsector</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sector__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Administración Autonómica</fullName>
            </value>
            <value>
                <fullName>Administración Central</fullName>
            </value>
            <value>
                <fullName>Administración Latam</fullName>
            </value>
            <value>
                <fullName>Administración Local</fullName>
            </value>
            <value>
                <fullName>Aeroespacial</fullName>
            </value>
            <value>
                <fullName>Agroalimentaria</fullName>
            </value>
            <value>
                <fullName>Agua</fullName>
            </value>
            <value>
                <fullName>Alimentación bebidas y tabaco</fullName>
            </value>
            <value>
                <fullName>Automoción</fullName>
            </value>
            <value>
                <fullName>Bancos</fullName>
            </value>
            <value>
                <fullName>Cajas de Ahorros</fullName>
            </value>
            <value>
                <fullName>Calzado</fullName>
            </value>
            <value>
                <fullName>Carbón</fullName>
            </value>
            <value>
                <fullName>Centros de formación en gral.</fullName>
            </value>
            <value>
                <fullName>Centros de Investigación</fullName>
            </value>
            <value>
                <fullName>Comercio Minorista</fullName>
            </value>
            <value>
                <fullName>Compañías de Banca/Seguros</fullName>
            </value>
            <value>
                <fullName>Construcción</fullName>
            </value>
            <value>
                <fullName>Construcción/Promoción</fullName>
            </value>
            <value>
                <fullName>Construcciones Mecánicas</fullName>
            </value>
            <value>
                <fullName>Construcción Maquinaria</fullName>
            </value>
            <value>
                <fullName>Consultoría</fullName>
            </value>
            <value>
                <fullName>Contact Center</fullName>
            </value>
            <value>
                <fullName>Corredurías/Mediadoras</fullName>
            </value>
            <value>
                <fullName>Distribución</fullName>
            </value>
            <value>
                <fullName>Distribución y Logística</fullName>
            </value>
            <value>
                <fullName>Educación privada</fullName>
            </value>
            <value>
                <fullName>Electricidad</fullName>
            </value>
            <value>
                <fullName>Emp. TT.II. Relac.con Finanzas</fullName>
            </value>
            <value>
                <fullName>Emp. TT.II De la Admon.Autonó.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Subsector_texto__c.field-meta.xml
<CustomField>
    <fullName>Subsector_texto__c</fullName>
    <label>Subsector IB</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/No_ejecutar_triggers__c/No_ejecutar_triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>No ejecutar triggers</label>
</CustomObject>

force-app/main/default/objects/No_ejecutar_triggers__c/fields/Correo_usuario__c.field-meta.xml
<CustomField>
    <fullName>Correo_usuario__c</fullName>
    <label>Correo usuario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/Oportunidad__c.object-meta.xml
<CustomObject>
    <label>Oportunidad</label>
    <nameField>
        <label>Tema</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Oportunidades</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Oportunidad__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/Desglose_importes__c.field-meta.xml
<CustomField>
    <fullName>Desglose_importes__c</fullName>
    <label>Desglose importes</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/Fecha_SP__c.field-meta.xml
<CustomField>
    <fullName>Fecha_SP__c</fullName>
    <label>Fecha Siguiente Paso</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/Importe_total_sin_IVA__c.field-meta.xml
<CustomField>
    <fullName>Importe_total_sin_IVA__c</fullName>
    <inlineHelpText>En el campo Importe total ofertado (sin IVA) en Euros se indicará todo el contrato (incluida la parte del posible socio) y en el Importe SAP (€) se indicará la parte del contrato correspondiente a Ayesa durante el presente ejercicio.</inlineHelpText>
    <label>Importe total ofertado (sin IVA) Euros</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/Tipo_de_Negocio__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Negocio__c</fullName>
    <label>Tipo de Negocio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automatic Extension</fullName>
            </value>
            <value>
                <fullName>Recurrent Extension</fullName>
            </value>
            <value>
                <fullName>Previous contract multiyear/multistage</fullName>
            </value>
            <value>
                <fullName>Previous exclusive framework agreement</fullName>
            </value>
            <value>
                <fullName>Previous framework agreement with competitors</fullName>
            </value>
            <value>
                <fullName>New extension or variation</fullName>
            </value>
            <value>
                <fullName>New exclusive framework agreement</fullName>
            </value>
            <value>
                <fullName>New framework agreement with competitors</fullName>
            </value>
            <value>
                <fullName>New contract</fullName>
            </value>
            <value>
                <fullName>New contract being incumbent</fullName>
            </value>
            <value>
                <fullName>New contract multiyear/multistage</fullName>
            </value>
            <value>
                <fullName>Nuevo Cliente</fullName>
                <isActive>false</isActive>
                <label>Nuevo Cliente</label>
            </value>
            <value>
                <fullName>Nuevo Negocio</fullName>
                <isActive>false</isActive>
                <label>Nuevo Negocio</label>
            </value>
            <value>
                <fullName>Prórrogas</fullName>
                <isActive>false</isActive>
                <label>Prórrogas</label>
            </value>
            <value>
                <fullName>Renegociaciones</fullName>
                <isActive>false</isActive>
                <label>Renegociaciones</label>
            </value>
            <value>
                <fullName>Renovación de Contrato con Competidores</fullName>
                <isActive>false</isActive>
                <label>Renovación de Contrato con Competidores</label>
            </value>
            <value>
                <fullName>Renovación de Contrato sin Competidores</fullName>
                <isActive>false</isActive>
                <label>Renovación de Contrato sin Competidores</label>
            </value>
            <value>
                <fullName>Variación de negocio existente</fullName>
                <isActive>false</isActive>
                <label>Variación de negocio existente</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/VALIDACIONDEF__c.field-meta.xml
<CustomField>
    <fullName>VALIDACIONDEF__c</fullName>
    <label>Validación económica DEF</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Sí</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>No</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Pdte. Validar</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Sin validar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CRM_IB_OCP_Test.cls
@isTest
public class CRM_IB_OCP_Test {

    @isTest
    public static void correos_OCP(){
        No_ejecutar_triggers__c saltar_trigger = new No_ejecutar_triggers__c();
        saltar_trigger.Correo_usuario__c='';
        insert saltar_trigger;
        
         //Cuenta
        Account Cliente= new Account(Name='Cliente prueba', SAP_Account__c='5555',Sector__c='Admón. Pública', Subsector__c='Administración Latam', Alias__c='ClientePrueba',Sector_text__c='Admón. Pública', Subsector_texto__c='Administración Latam');
        insert Cliente;
        
        //Oportunidad
        Id recordTypeSME = Schema.SObjectType.Oportunidad__c.getRecordTypeInfosByName().get('Ibermatica SME').getRecordTypeId();
        List<Oportunidad__c> listaOps = new List<Oportunidad__c>();
        Oportunidad__c op= new Oportunidad__c(Name='Prueba', Cliente__c=Cliente.Id, Fecha_SP__c = System.TODAY(), Tipo_de_Negocio__c='New contract',VALIDACIONDEF__c='No',
                                              RecordTypeId= recordTypeSME, Importe_limite_OCP__c=500, Desglose_importes__c ='No',Importe_total_sin_IVA__c=1, Modificar_importes__c=true );
        
        Oportunidad__c op2= new Oportunidad__c(Name='Prueba2', Cliente__c=Cliente.Id, Fecha_SP__c = System.TODAY(), Tipo_de_Negocio__c='New contract',VALIDACIONDEF__c='Sí',
                                              RecordTypeId= recordTypeSME, Importe_limite_OCP__c=500, Desglose_importes__c ='No',Importe_total_sin_IVA__c=1, Modificar_importes__c=true );
        listaOps.add(op);
        listaOps.add(op2);
        
        insert listaOps;

        CRM_IB_OCP.avisosOCP(op,op2);
        
        op.VALIDACIONDEF__c='Sí';
        op2.VALIDACIONDEF__c='No';
        update listaOps;
        CRM_IB_OCP.avisosOCP(op,op2);

        op.VALIDACIONDEF__c='Sí';
        op2.VALIDACIONDEF__c='Pdte. validar';
        update listaOps;
        CRM_IB_OCP.avisosOCP(op,op2);
        
        op.VALIDACIONDEF__c='Sí';
        op2.VALIDACIONDEF__c='Sin Validar';
        update listaOps;
        CRM_IB_OCP.avisosOCP(op,op2);
       
    }
}