force-app/main/default/objects/Account/fields/BLoqueada__c.field-meta.xml
<CustomField>
    <fullName>BLoqueada__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Esta cuenta esta bloqueada por lo que no se podrán realizar gestiones sobre la misma.</description>
    <label>Bloqueada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Motivo_bloqueo__c.field-meta.xml
<CustomField>
    <fullName>Motivo_bloqueo__c</fullName>
    <label>Motivo bloqueo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Control_Integracion__c/Control_Integracion__c.object-meta.xml
<CustomObject>
    <label>Control de Integracion</label>
    <nameField>
        <label>Nombre de Control de Integraciones</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Controles de Integraciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Control_Integracion__c/fields/Error_Code__c.field-meta.xml
<CustomField>
    <fullName>Error_Code__c</fullName>
    <label>Error Code</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Control_Integracion__c/fields/Interfaz__c.field-meta.xml
<CustomField>
    <fullName>Interfaz__c</fullName>
    <label>Interfaz</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Control_Integracion__c/fields/Metodo__c.field-meta.xml
<CustomField>
    <fullName>Metodo__c</fullName>
    <label>Metodo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Control_Integracion__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Control_Integracion__c/fields/Servicio__c.field-meta.xml
<CustomField>
    <fullName>Servicio__c</fullName>
    <label>Servicio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CRM_IB_BloqueoClienteWS.cls
/**
* @author Ayesa
* @since 24-05-2023
* @desc Creacion APEX Rest integracion CR-IB 
* Bloque de Clientes
*/
@RestResource(urlMapping='/BloqueoCliente/*')
global with sharing class CRM_IB_BloqueoClienteWS {
    
    global class Response{
        webservice String errorCode;
        webservice String errorMessage;
        webservice String accountId;
    }
    @HttpPut
    global static Response bloqueoCliente(String clienteId, String motivoBloqueo){
        
        System.debug('CRM_IB_BloqueoClienteWS clienteId: ' + clienteId);
        
        Response res = new Response();
        List<Account> acc = [SELECT id,name,BLoqueada__c,Motivo_bloqueo__c 
                             FROM Account WHERE Id=:clienteId LIMIT 1];
        
        Control_Integracion__c controlInt = new Control_Integracion__c();
        controlInt.Request__c = clienteId;
        controlInt.Metodo__c = 'PATCH';
        controlInt.Interfaz__c = 'BloqueoCliente';
        controlInt.Servicio__c = '/BloqueoCliente/*';  
        
        System.debug('CRM_IB_BloqueoClienteWS acc: ' + acc);
        
        if(!acc.isEmpty()){
            acc.get(0).BLoqueada__c = true;
            acc.get(0).Motivo_bloqueo__c = motivoBloqueo;
            controlInt.Status_Code__c = 201;  
            controlInt.Error_Code__c = '00';
            controlInt.Error_Message__c = 'OK.';
            
            res.errorCode = '00';
            res.errorMessage = 'Bloqueo OK.';
            res.accountId = clienteId;           
            try{
                update acc;
                insert controlInt;               
            }catch(DMLException ex){
                controlInt.Status_Code__c = 400;  
                controlInt.Error_Code__c = '98';
                controlInt.Error_Message__c = 'KO. ' + ex.getMessage();
            }            
        }else{
            res.errorCode = '99';
            res.errorMessage = 'KO. No existe el Cliente';
            res.accountId = clienteId;
            
            controlInt.Status_Code__c = 400; 
            controlInt.Error_Code__c = '99';
            controlInt.Error_Message__c = 'Cambio de estado KO.No existe la Oportunidad';            
        }
                
        return res;
    }
}