force-app/main/default/objects/Account/fields/Codigo_Pais__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Pais__c</fullName>
    <label>Codigo País</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Codigo_provincia__c.field-meta.xml
<CustomField>
    <fullName>Codigo_provincia__c</fullName>
    <label>Codigo provincia</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <label>País</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afganistán</fullName>
                <isActive>false</isActive>
                <label>Afganistán</label>
            </value>
            <value>
                <fullName>DE</fullName>
                <label>Alemania</label>
            </value>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>SA</fullName>
                <label>Arabia Saudí</label>
            </value>
            <value>
                <fullName>DZ</fullName>
                <label>Argelia</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaiyán</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrein</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Bélgica</label>
            </value>
            <value>
                <fullName>BY</fullName>
                <label>Bielorrusia</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brasil</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>Canadá</label>
            </value>
            <value>
                <fullName>CL</fullName>
                <label>Chile</label>
            </value>
            <value>
                <fullName>CN</fullName>
                <label>China</label>
            </value>
            <value>
                <fullName>CO</fullName>
                <label>Colombia</label>
            </value>
            <value>
                <fullName>Corea</fullName>
            </value>
            <value>
                <fullName>Corea del Sur</fullName>
                <isActive>false</isActive>
                <label>Corea del Sur</label>
            </value>
            <value>
                <fullName>CI</fullName>
                <label>Costa de Marfil</label>
            </value>
            <value>
                <fullName>CR</fullName>
                <label>Costa Rica</label>
            </value>
            <value>
                <fullName>HR</fullName>
                <label>Croacia</label>
            </value>
            <value>
                <fullName>CU</fullName>
                <label>Cuba</label>
            </value>
            <value>
                <fullName>DK</fullName>
                <label>Dinamarca</label>
            </value>
            <value>
                <fullName>Dominica</fullName>
                <isActive>false</isActive>
                <label>Dominica</label>
            </value>
            <value>
                <fullName>E.A.U.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/Parametrica_2__c.object-meta.xml
<CustomObject>
    <description>Parametrica que contiene los datos de Ibermatica</description>
    <label>Parametrica Ibermática</label>
    <nameField>
        <label>Nombre de Parametrica Ibermática</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parametricas Ibermática</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parametrica_2__c/fields/Codigo_Externo__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Externo__c</fullName>
    <label>Codigo Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Denominacion__c.field-meta.xml
<CustomField>
    <fullName>Denominacion__c</fullName>
    <label>Denominacion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>Activo</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>Inactivo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pais</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Parametrica_2__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Paises</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Parametrica_2__c</referenceTo>
    <relationshipLabel>Parametricas Ibermática (Pais)</relationshipLabel>
    <relationshipName>Pais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/recordTypes/Paises.recordType-meta.xml
<RecordType>
    <fullName>Paises</fullName>
    <active>true</active>
    <label>Paises</label>
</RecordType>

force-app/main/default/objects/Parametrica_2__c/recordTypes/Provincias.recordType-meta.xml
<RecordType>
    <fullName>Provincias</fullName>
    <active>true</active>
    <label>Provincias</label>
</RecordType>

force-app/main/default/classes/CRM_IB_Account_Address_controller.cls
public class CRM_IB_Account_Address_controller {
    
    @AuraEnabled
    public static String countryProvinceMap(String IdAccount){
        
        String result = '';
        
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        //Recuperamos valores de gestor de produccion
        List <Parametrica_2__c> paises = [SELECT Id,Name, Denominacion__c, Codigo_Externo__c,RecordType.Name
                                          FROM Parametrica_2__c 
                                          Where RecordType.Name ='Paises' and Estado__c ='1' order by Denominacion__c];
        
        List<String> map_paises = new  List<String>();
        
        List<String> map_provincia = new  List<String>();
        List <Parametrica_2__c> provincia = new List <Parametrica_2__c>();
        
        for (Parametrica_2__c p: paises){
            if(p.RecordType.Name == 'Paises' && !map_paises.contains(p.Denominacion__c) ){
                map_paises.add(p.Denominacion__c);
            }
        }
        
        gen.writeObjectField('map_paises', map_paises);
        
        
        //Recuperamos valores iniciales de la Cuenta
        Account acct = [SELECT Id,Name, BillingCountry, BillingState, BillingCity, BillingPostalCode, BillingStreet
                        FROM Account
                        WHERE Id =: IdAccount LIMIT 1 ];
        gen.writeObjectField('account', acct);
        
        if(acct.BillingState != null){
             provincia = [SELECT Id,Name, Denominacion__c, Codigo_Externo__c,RecordType.Name
                                             FROM Parametrica_2__c 
                                             Where RecordType.Name ='Provincias' and Estado__c ='1'   and Pais__r.Denominacion__c =:acct.BillingCountry order by Denominacion__c];
            
            
        
        for (Parametrica_2__c p: provincia){
            if(p.RecordType.Name == 'Provincias' && !map_provincia.contains(p.Denominacion__c) ){
                map_provincia.add(p.Denominacion__c);
            }
        }
        }

        
        gen.writeObjectField('map_provincias', map_provincia);
        gen.writeEndObject();
        
        result = gen.getAsString();
        // return valoresGP;
        return result;
    }
    
    @AuraEnabled
    
    public static List <String> provinceOptions(String Pais){
        
        System.debug('Pais: '+ Pais);
        
        List <Parametrica_2__c> provincia = [SELECT Id,Name, Denominacion__c, Codigo_Externo__c,RecordType.Name
                                             FROM Parametrica_2__c 
                                             Where RecordType.Name ='Provincias' and Estado__c ='1'   and Pais__r.Denominacion__c =:Pais order by Denominacion__c];
        System.debug('provincias: ' + provincia);
        List<String> map_provincia = new  List<String>();
        
        for (Parametrica_2__c p: provincia){
            if(p.RecordType.Name == 'Provincias' && !map_provincia.contains(p.Denominacion__c) ){
                map_provincia.add(p.Denominacion__c);
            }
        }
        
        System.debug('map_provincia: '+ map_provincia);
        return Map_provincia;
    }
    
    @AuraEnabled
    
    public static String saveAccountCountry(String Pais, String Provincia, String Ciudad, String Calle, String Codigo_Postal, String IdAccount){
        
        Parametrica_2__c pais_provincia = [SELECT Id,Name, Denominacion__c, Codigo_Externo__c,RecordType.Name, Pais__R.Codigo_Externo__c

                                           FROM Parametrica_2__c 
                                           Where RecordType.Name ='Provincias' and Estado__c ='1'   and Pais__r.Denominacion__c =:Pais and Denominacion__c =: Provincia order by Denominacion__c LIMIT 1];
        
        Account acct = [Select Id, Name, BillingCountry, BillingState, Codigo_Pais__c, 	Codigo_provincia__c
                        FROM Account
                        Where Id =: IdAccount];
        acct.BillingCountry = Pais;
        acct.BillingState =Provincia;
        acct.BillingCity = Ciudad;
        acct.BillingStreet = Calle;
        acct.BillingPostalCode = Codigo_Postal;
        acct.Codigo_Pais__c = pais_provincia.Pais__r.Codigo_Externo__c;
        acct.Codigo_provincia__c=pais_provincia.Codigo_Externo__c;
        try{
            
            update acct;
            
        } catch(DMLException e){ 
            System.debug('Error al actualizar dirección: ' + e.getMessage());
            return e.getMessage();            
        }	
        system.debug('Actualizado');
        return 'Actualizado';
        
       
    }
    
    
}