force-app/main/default/objects/Account/fields/Contacto_Principal__c.field-meta.xml
<CustomField>
    <fullName>Contacto_Principal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contacto Principal</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ATC</fullName>
                <default>true</default>
                <label>ATC</label>
            </value>
            <value>
                <fullName>ATD</fullName>
            </value>
            <value>
                <fullName>INGENIERIA_CIVIL</fullName>
                <label>INGENIERÍA CIVIL Y ARQUITECTURA</label>
            </value>
            <value>
                <fullName>INGENIERIA_INDUSTRIAL</fullName>
                <label>INGENIERÍA INDUSTRIAL</label>
            </value>
            <value>
                <fullName>M2C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contacto_Principal__c.field-meta.xml
<CustomField>
    <fullName>Contacto_Principal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contacto Principal</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>El contacto no está relacionado con la cuenta elegida</errorMessage>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Cliente__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades_Aux</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/IT_DS.recordType-meta.xml
<RecordType>
    <fullName>IT_DS</fullName>
    <active>true</active>
    <businessProcess>IT%26DS</businessProcess>
    <label>IT&amp;DS</label>
</RecordType>

force-app/main/default/objects/Parametrica_2__c/Parametrica_2__c.object-meta.xml
<CustomObject>
    <description>Parametrica que contiene los datos de Ibermatica</description>
    <label>Parametrica Ibermática</label>
    <nameField>
        <label>Nombre de Parametrica Ibermática</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parametricas Ibermática</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parametrica_2__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Centro_resp_Super__c.field-meta.xml
<CustomField>
    <fullName>Centro_resp_Super__c</fullName>
    <label>Centro resp. Super</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Codigo_CR__c.field-meta.xml
<CustomField>
    <fullName>Codigo_CR__c</fullName>
    <label>Codigo CR</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/CR_Importe_OCP__c.field-meta.xml
<CustomField>
    <fullName>CR_Importe_OCP__c</fullName>
    <label>CR Importe OCP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Desglose_importes__c.field-meta.xml
<CustomField>
    <fullName>Desglose_importes__c</fullName>
    <inlineHelpText>Opciones: Sí / No</inlineHelpText>
    <label>Desglose importes</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>Activo</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>Inactivo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Horizontal__c.field-meta.xml
<CustomField>
    <fullName>Horizontal__c</fullName>
    <label>Horizontal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica__c/Parametrica__c.object-meta.xml
<CustomObject>
    <description>Paramátrica con Lista de Valores</description>
    <label>Paramétrica</label>
    <nameField>
        <label>Código</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paramétricas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parametrica__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <description>Correspondencia con Area jerarquía antigua (antes 2021)</description>
    <label>Area</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica__c/fields/Codigo_Mercado__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Mercado__c</fullName>
    <description>Código API de los 8 valores de Mercado</description>
    <label>Codigo Mercado</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica__c/fields/Division2__c.field-meta.xml
<CustomField>
    <fullName>Division2__c</fullName>
    <description>Campo con la división de Latinoamérica (Sector Público y Privado)</description>
    <label>División</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <description>Correspondencia con división antigua jerarquía (anterior 2021)</description>
    <label>División</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica__c/fields/Mercado1__c.field-meta.xml
<CustomField>
    <fullName>Mercado1__c</fullName>
    <description>Nivel 1 de la estructura mercado</description>
    <label>Mercado1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica__c/fields/Mercado2__c.field-meta.xml
<CustomField>
    <fullName>Mercado2__c</fullName>
    <description>Nivel 2 de la estructura mercado</description>
    <label>Mercado2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica__c/fields/Mercado3__c.field-meta.xml
<CustomField>
    <fullName>Mercado3__c</fullName>
    <description>Nivel 3 de la estructura mercado</description>
    <label>Mercado3</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica__c/fields/Mercado4__c.field-meta.xml
<CustomField>
    <fullName>Mercado4__c</fullName>
    <description>Nivel 4 de la estructura mercado</description>
    <label>Mercado4</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <label>Valor</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestDataFactory_Test.cls
@IsTest
public class TestDataFactory_Test {

    @TestSetup
    static void setup() {

    }

    @IsTest
    static void testCreateClientes() {
        List<Account> clientes = TestDataFactory.createClientes(2);
        System.assertEquals(2, clientes.size(), 'Debe crear 2 clientes');
        for (Account a : clientes) {
            System.assertNotEquals(null, a.Id, 'El cliente debe tener Id tras insert');
            System.assert(a.Name.startsWith('TestCliente'), 'Nombre de cliente esperado');
        }
    }

    @IsTest
    static void testCreateOpportunity() {
        Opportunity opp = TestDataFactory.createOpportunity('Cualificación', 'Digital impact', 'IT_DS');
        System.assertNotEquals(null, opp.Id, 'Opportunity debe tener Id tras insert');
        System.assertEquals('Opp-Test', opp.Name, 'El nombre de la Opportunity debe ser Opp-Test');
        System.assertNotEquals(null, opp.AccountId, 'Debe tener AccountId asignado');
        System.assertNotEquals(null, opp.Contacto_Principal__c, 'Debe tener Contacto_Principal__c asignado');
    }

    @IsTest
    static void testCreateParam() {
        Parametrica__c valor =new Parametrica__c(Codigo_Mercado__c='60029427',Mercado4__c='ENERGY & UTILITIES',Mercado1__c='',Mercado2__c='',Mercado3__c='',
                                                 Tipo__c='No', Valor__c='No',Area__c='ATC', Division__c ='Utilities', Division2__c='Utilities' );
        Parametrica__c cr = TestDataFactory.createParam(
            new Map<String,Object>{
                'Name' => 'CR-Test',
                    'Codigo_Mercado__c' => '60029427',
                    'Mercado4__c' => 'ENERGY & UTILITIES',
                    'Tipo__c' => 'No',
                    'Valor__c' => 'No',
                    'Area__c' => 'ATC',
                    'Division__c' => 'Utilities',
                    'Division2__c' => 'Utilities'
                    });

    }

    @IsTest
    static void testCreateParam2() {
        Parametrica_2__c cr = TestDataFactory.createParam2(
            'Centro Responsabilidad',
            new Map<String,Object>{
                					'Name' => 'CR-Test',
                    'Centro_resp_Super__c' => 'CENTRO PRUEBA',
                    'Codigo_CR__c'         => '015',
                    'Horizontal__c'        => 'Digital impact',
                    'Desglose_importes__c' => 'No',
                    'CR_Importe_OCP__c'    => 1000,
                    'Estado__c'            => '1'
                    });
    }

    @IsTest
    static void testGetOpportunity() {
        Opportunity opp = TestDataFactory.createOpportunity('Cualificación', 'Digital impact', 'IT_DS');
        Opportunity fetchedOpp = TestDataFactory.getOpportunity(opp.Id);
        System.assertNotEquals(null, fetchedOpp, 'Debe devolver la Opportunity por Id');
        System.assertEquals(opp.Id, fetchedOpp.Id, 'Ids deben coincidir');
    }
}