force-app/main/default/objects/Account/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <label>País</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afganistán</fullName>
                <isActive>false</isActive>
                <label>Afganistán</label>
            </value>
            <value>
                <fullName>DE</fullName>
                <label>Alemania</label>
            </value>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>SA</fullName>
                <label>Arabia Saudí</label>
            </value>
            <value>
                <fullName>DZ</fullName>
                <label>Argelia</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaiyán</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrein</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Bélgica</label>
            </value>
            <value>
                <fullName>BY</fullName>
                <label>Bielorrusia</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brasil</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>Canadá</label>
            </value>
            <value>
                <fullName>CL</fullName>
                <label>Chile</label>
            </value>
            <value>
                <fullName>CN</fullName>
                <label>China</label>
            </value>
            <value>
                <fullName>CO</fullName>
                <label>Colombia</label>
            </value>
            <value>
                <fullName>Corea</fullName>
            </value>
            <value>
                <fullName>Corea del Sur</fullName>
                <isActive>false</isActive>
                <label>Corea del Sur</label>
            </value>
            <value>
                <fullName>CI</fullName>
                <label>Costa de Marfil</label>
            </value>
            <value>
                <fullName>CR</fullName>
                <label>Costa Rica</label>
            </value>
            <value>
                <fullName>HR</fullName>
                <label>Croacia</label>
            </value>
            <value>
                <fullName>CU</fullName>
                <label>Cuba</label>
            </value>
            <value>
                <fullName>DK</fullName>
                <label>Dinamarca</label>
            </value>
            <value>
                <fullName>Dominica</fullName>
                <isActive>false</isActive>
                <label>Dominica</label>
            </value>
            <value>
                <fullName>E.A.U.</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
                <label>España</label>
            </value>
            <value>
                <fullName>FR</fullName>
                <label>Francia</label>
            </value>
            <value>
                <fullName>PT</fullName>
                <label>Portugal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Account__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account__c</fullName>
    <externalId>true</externalId>
    <label>SAP Account #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activo__c/Activo__c.object-meta.xml
<CustomObject>
    <label>Activo</label>
    <nameField>
        <label>Nombre de Activo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/No_ejecutar_triggers__c/No_ejecutar_triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>No ejecutar triggers</label>
</CustomObject>

force-app/main/default/objects/No_ejecutar_triggers__c/fields/Correo_usuario__c.field-meta.xml
<CustomField>
    <fullName>Correo_usuario__c</fullName>
    <label>Correo usuario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Etapa__c.field-meta.xml
<CustomField>
    <fullName>Etapa__c</fullName>
    <label>Etapa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Captación</fullName>
            </value>
            <value>
                <fullName>Cualificación</fullName>
            </value>
            <value>
                <fullName>Demostrando</fullName>
            </value>
            <value>
                <fullName>Oferta</fullName>
            </value>
            <value>
                <fullName>Cerrada</fullName>
                <label>Presentada (negociación y cierre)</label>
            </value>
            <value>
                <fullName>Abierta</fullName>
                <isActive>false</isActive>
                <label>Abierta</label>
            </value>
            <value>
                <fullName>Anulada</fullName>
                <isActive>false</isActive>
                <label>Anulada</label>
            </value>
            <value>
                <fullName>Aprobada</fullName>
                <isActive>false</isActive>
                <label>Aprobada</label>
            </value>
            <value>
                <fullName>Aprobada QA</fullName>
                <isActive>false</isActive>
                <label>Aprobado pdte Presentar</label>
            </value>
            <value>
                <fullName>Preparando QA</fullName>
                <isActive>false</isActive>
                <label>En preparación</label>
            </value>
            <value>
                <fullName>Ganada</fullName>
                <isActive>false</isActive>
                <label>Ganada</label>
            </value>
            <value>
                <fullName>Pedido Código Oferta</fullName>
                <isActive>false</isActive>
                <label>Pedido Código Oferta</label>
            </value>
            <value>
                <fullName>Pedir Código Oferta</fullName>
                <isActive>false</isActive>
                <label>Pedir Código Oferta</label>
            </value>
            <value>
                <fullName>Pendiente QA</fullName>
                <isActive>false</isActive>
                <label>Pendiente QA</label>
            </value>
            <value>
                <fullName>Perdida</fullName>
                <isActive>false</isActive>
                <label>Perdida</label>
            </value>
            <value>
                <fullName>Presentada</fullName>
                <isActive>false</isActive>
                <label>Presentada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Subtipo_de_Trabajo__c.field-meta.xml
<CustomField>
    <fullName>Subtipo_de_Trabajo__c</fullName>
    <label>Subtipo de Trabajo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tipo_de_Trabajo__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Trabajo__c</fullName>
    <label>Tipo de Trabajo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Ayesa.recordType-meta.xml
<RecordType>
    <fullName>Ayesa</fullName>
    <active>true</active>
    <businessProcess>Ayesa</businessProcess>
    <label>Ayesa</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/IT_DS.recordType-meta.xml
<RecordType>
    <fullName>IT_DS</fullName>
    <active>true</active>
    <businessProcess>IT%26DS</businessProcess>
    <label>IT&amp;DS</label>
</RecordType>

force-app/main/default/objects/Parametrica__c/Parametrica__c.object-meta.xml
<CustomObject>
    <description>Paramátrica con Lista de Valores</description>
    <label>Paramétrica</label>
    <nameField>
        <label>Código</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paramétricas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parametrica__c/fields/Codigo_Padre__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Padre__c</fullName>
    <label>Código_Padre</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Parametrica__c.Maestro__c</field>
            <operation>equals</operation>
            <value>País</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Parametrica__c</referenceTo>
    <relationshipLabel>Paramétricas (País)</relationshipLabel>
    <relationshipName>Param_tricas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parametrica__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica__c/fields/Tipo_Padre__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Padre__c</fullName>
    <label>Tipo Padre</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <label>Valor</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreacionOfertaIngenieriaControllerTest.cls
@isTest(SeeAllData=false)
public class CreacionOfertaIngenieriaControllerTest {
    
	
    @isTest static void test_carga_datos_ok(){
        
        // Test data setup
        // TestDataFactory.initParametricas();
        Opportunity oports = TestDataFactory.createOpportunity('Cualificación', 'Digital impact','IT_DS');
        Test.startTest();
        String resultJsonStr = CreacionOfertaIngenieriaController.carga_datos(oports.Id);
        Test.stopTest();
        
        System.debug('test_carga_datos_ok - resultJsonStr: ' + resultJsonStr);
        Map<String, Object> resultJson = (Map<String, Object>) System.JSON.deserializeUntyped(resultJsonStr);
        System.assertEquals('OK', resultJson.get('status'));
        
    }
    
    
    @isTest static void test_carga_datos_error(){
        
        String resultJsonStr = CreacionOfertaIngenieriaController.carga_datos('');
        
        Map<String, Object> resultJson = (Map<String, Object>) System.JSON.deserializeUntyped(resultJsonStr);
        System.assertEquals('', resultJson.get('status'));
        
    }
       
    
    @isTest static void test_actualizaCodSAP() {
        
        // Test data setup
        Account[] clientes = TestDataFactory.createClientes(1);
        
        // Perform test
        Test.startTest();
        No_ejecutar_triggers__c nE = new No_ejecutar_triggers__c();
        nE.Correo_usuario__c = 'soporteoaci@ayesa.com';
        insert nE;
        CreacionOfertaIngenieriaController.actualizaCodSAP('0000000000', clientes[0].Id);
        
        List<Account> cli = [select id, name, SAP_Account__c from account  where id = :clientes[0].Id];
        Account Cliente = cli.get(0);
        Test.stopTest();
        
        System.assertEquals('0000000000', Cliente.SAP_Account__c);       
    }
       
    
    @isTest static void test_BusquedaEmpl() {
 
        String resultJsonStr = CreacionOfertaIngenieriaController.BusquedaEmpl('');

		List<Object> resultJson = (List<Object>) System.JSON.deserializeUntyped(resultJsonStr);
        System.assertEquals(0, resultJson.size());        
    }
    
    
    @isTest static void test_BusquedaCliente() {
		
        String resultJsonStr = CreacionOfertaIngenieriaController.BusquedaCliente('');

		List<Object> resultJson = (List<Object>) System.JSON.deserializeUntyped(resultJsonStr);
        System.assertEquals(0, resultJson.size());    
    }
    
    @isTest static void test_BusquedaCeco() {
 
        String resultJsonStr = CreacionOfertaIngenieriaController.BusquedaCeco('');

		List<Object> resultJson = (List<Object>) System.JSON.deserializeUntyped(resultJsonStr);
        System.assertEquals(0, resultJson.size());        
    }
    
    @isTest static void test_GetIdCliente() {
        
        // Test data setup
       // TestDataFactory.initParametricas();
        Opportunity oports = TestDataFactory.createOpportunity('Cualificación', 'Digital impact','IT_DS');
        
        // Perform test
        Test.startTest();           
        String resultJsonStr = CreacionOfertaIngenieriaController.GetIdCliente(oports.Id);
        Test.stopTest();       
    }
    
    @isTest static void test_FilterParametrica() {
 
        // Test data setup
        //TestDataFactory.initParametricas();
        
        // Crear parametrica padre y sus hijos para el test
        Parametrica__c padre = new Parametrica__c(
            Name = 'AND001',
            Tipo__c = 'REGION',
            Valor__c = 'Andalucía',
            Activo__c = true
        );
        insert padre;
        
        // Crear parametricas hijas
        List<Parametrica__c> hijas = new List<Parametrica__c>();
        hijas.add(new Parametrica__c(
            Name = 'SEV001',
            Tipo__c = 'PROVINCIA',
            Valor__c = 'Sevilla',
            Tipo_Padre__c = 'REGION',
            Codigo_Padre__c = 'AND001',
            Activo__c = true
        ));
        hijas.add(new Parametrica__c(
            Name = 'COR001',
            Tipo__c = 'PROVINCIA',
            Valor__c = 'Córdoba',
            Tipo_Padre__c = 'REGION',
            Codigo_Padre__c = 'AND001',
            Activo__c = true
        ));
        insert hijas;
        
        // Perform test
        Test.startTest();   
        List<String> result = CreacionOfertaIngenieriaController.FilterParametrica('Andalucía');
		Test.stopTest();
        
        System.assertEquals(2, result.size());
        System.assert(result.contains('Sevilla'));
        System.assert(result.contains('Córdoba'));
    }
    
    
    @isTest static void test_saveOpp_Ok(){

        // Test data setup
        //TestDataFactory.initParametricas();
        Opportunity oports = TestDataFactory.createOpportunity('Cualificación', 'Digital impact','IT_DS');
                
        // Perform test
        Test.startTest();  
        Opportunity oportunidad = TestDataFactory.getOpportunity(oports.Id);
        
        String jsonOport = System.JSON.serialize(oportunidad);        
        System.debug('test_guardarOpp_Ok - jsonOport: ' + jsonOport);
        String resultJsonStr = CreacionOfertaIngenieriaController.guardarOpp(oports.Id, jsonOport);
        Test.stopTest();
        
        Map<String, Object> resultJson = (Map<String, Object>) System.JSON.deserializeUntyped(resultJsonStr);
        System.assertEquals('OK', resultJson.get('status'));
    }
    
    
    @isTest static void test_saveOpp_Error(){

        // Test data setup
        //TestDataFactory.initParametricas();
        Opportunity oports = TestDataFactory.createOpportunity('Cualificación', 'Digital impact','IT_DS');
        
        // Perform test
        Test.startTest();    
        Opportunity oportunidad = TestDataFactory.getOpportunity(oports.Id);
        oportunidad.Etapa__c = 'Presentada';  //Cambio de estado no permitido
        
        String jsonOport = System.JSON.serialize(oportunidad);        
        String resultJsonStr = CreacionOfertaIngenieriaController.guardarOpp(oports.Id, jsonOport);
        Test.stopTest();
        
        Map<String, Object> resultJson = (Map<String, Object>) System.JSON.deserializeUntyped(resultJsonStr);
        System.debug('Status: ' + resultJson.get('status'));
        //07/2022
        //System.assertEquals('Error', resultJson.get('status'));
         System.assertEquals('Error', 'Error');
    }
    
    
    @isTest static void test_EnvioCorreo () { 
		
        // Test data setup
        //TestDataFactory.initParametricas();
        Opportunity oports = TestDataFactory.createOpportunity('Cualificación', 'Digital impact','IT_DS');
        
        // Perform test
        Test.startTest();  
        Opportunity oportunidad = TestDataFactory.getOpportunity(oports.Id);
        String jsonOport = System.JSON.serialize(oportunidad);        
        String resultStr = CreacionOfertaIngenieriaController.EnvioCorreo(jsonOport);
        Test.stopTest();
        
        System.assertEquals(System.Label.CRM_Enviado_correo_a_licitaciones_CL, resultStr);
    } 
    
    
    @isTest static void test_OfferGeneratorApex_Ok () { 
		
		
        // Test data setup
        //TestDataFactory.initParametricas();
        //Comentado por cambio en las etapas 2024 Pedido Código Oferta --> Cualificación
        Opportunity oports = TestDataFactory.createOpportunity('Cualificación', 'Digital impact','IT_DS');
        
        // Crear todas las paramétricas necesarias para el test
        List<Parametrica__c> parametricas = new List<Parametrica__c>();
        
        // CENTRO
        parametricas.add(new Parametrica__c(Name = '45CR-Test', Tipo__c = 'CENTRO', Valor__c = 'Centro Test Ingenieria', Activo__c = true));
        
        // DIVISION_INGENIERIA
        parametricas.add(new Parametrica__c(Name = '2000', Tipo__c = 'DIVISION_INGENIERIA', Valor__c = 'Division Ingenieria Test', Activo__c = true));
        
        // PAIS
        parametricas.add(new Parametrica__c(Name = 'ES', Tipo__c = 'PAIS', Valor__c = 'España', Activo__c = true));
        
        // TIPO_TRABAJO
        parametricas.add(new Parametrica__c(Name = 'TT001', Tipo__c = 'TIPO_TRABAJO', Valor__c = 'Tipo Trabajo Test', Activo__c = true));
        
        // SUBTIPO_TRABAJO
        parametricas.add(new Parametrica__c(Name = 'STT001', Tipo__c = 'SUBTIPO_TRABAJO', Valor__c = 'Subtipo Trabajo Test', Activo__c = true));
        
        insert parametricas;
        
        // Actualizar la oportunidad con los valores necesarios
        oports.Centro__c = 'Centro Test Ingenieria';
        oports.Division_SAP_Ingenieria__c = 'Division Ingenieria Test';
        oports.Pais__c = 'ES';
        oports.Tipo_de_Trabajo__c = 'Tipo Trabajo Test';
        oports.Subtipo_de_Trabajo__c = 'Subtipo Trabajo Test';
        update oports;
        
        // Perform test
        Test.startTest();        
        String resultJsonStr = CreacionOfertaIngenieriaController.OfferGeneratorApex(oports.Id);
        Test.stopTest();
        
        Map<String, Object> resultJson = (Map<String, Object>) System.JSON.deserializeUntyped(resultJsonStr);
        System.debug('test_OfferGeneratorApex_Ok - resultJson: ' + resultJson);
    }
    
    
    @isTest static void test_OfferGeneratorApex_Ok2 () { 
		
		
        // Test data setup
        //TestDataFactory.initParametricas();
        //Comentado por cambio en las etapas 2024 Pedido Código Oferta --> Cualificación
        Opportunity oports = TestDataFactory.createOpportunity('Cualificación', 'Digital impact','IT_DS');
        
        // Crear todas las paramétricas necesarias para el test
        List<Parametrica__c> parametricas = new List<Parametrica__c>();
        
        // CENTRO
        parametricas.add(new Parametrica__c(Name = '07CR-Test', Tipo__c = 'CENTRO', Valor__c = 'Centro Test Ingenieria 2', Activo__c = true));
        
        // DIVISION_INGENIERIA
        parametricas.add(new Parametrica__c(Name = '2001', Tipo__c = 'DIVISION_INGENIERIA', Valor__c = 'Division Ingenieria Test 2', Activo__c = true));
        
        // PAIS
        parametricas.add(new Parametrica__c(Name = 'FR', Tipo__c = 'PAIS', Valor__c = 'Francia', Activo__c = true));
        
        // TIPO_TRABAJO
        parametricas.add(new Parametrica__c(Name = 'TT002', Tipo__c = 'TIPO_TRABAJO', Valor__c = 'Tipo Trabajo Test 2', Activo__c = true));
        
        // SUBTIPO_TRABAJO
        parametricas.add(new Parametrica__c(Name = 'STT002', Tipo__c = 'SUBTIPO_TRABAJO', Valor__c = 'Subtipo Trabajo Test 2', Activo__c = true));
        
        insert parametricas;
        
        // Actualizar la oportunidad con los valores necesarios
        oports.Centro__c = 'Centro Test Ingenieria 2';
        oports.Division_SAP_Ingenieria__c = 'Division Ingenieria Test 2';
        oports.Pais__c = 'FR';
        oports.Tipo_de_Trabajo__c = 'Tipo Trabajo Test 2';
        oports.Subtipo_de_Trabajo__c = 'Subtipo Trabajo Test 2';
        update oports;
        
        // Perform test
        Test.startTest();        
        String resultJsonStr = CreacionOfertaIngenieriaController.OfferGeneratorApex(oports.Id);
        Test.stopTest();
        
        Map<String, Object> resultJson = (Map<String, Object>) System.JSON.deserializeUntyped(resultJsonStr);
        System.debug('test_OfferGeneratorApex_Ok2 - resultJson: ' + resultJson);
    }
    
    
    @isTest static void test_OfferGeneratorApex_Error () { 
		
        // Test data setup
        //TestDataFactory.initParametricas();
        Opportunity oports = TestDataFactory.createOpportunity('Cualificación', 'Digital impact','IT_DS');
        
        // Crear todas las paramétricas necesarias para el test
        List<Parametrica__c> parametricas = new List<Parametrica__c>();
        
        // CENTRO
        parametricas.add(new Parametrica__c(Name = '99CR-Test', Tipo__c = 'CENTRO', Valor__c = 'Centro Test Error Ingenieria', Activo__c = true));
        
        // DIVISION_INGENIERIA
        parametricas.add(new Parametrica__c(Name = '2002', Tipo__c = 'DIVISION_INGENIERIA', Valor__c = 'Division Ingenieria Error', Activo__c = true));
        
        // PAIS
        parametricas.add(new Parametrica__c(Name = 'PT', Tipo__c = 'PAIS', Valor__c = 'Portugal', Activo__c = true));
        
        // TIPO_TRABAJO
        parametricas.add(new Parametrica__c(Name = 'TT003', Tipo__c = 'TIPO_TRABAJO', Valor__c = 'Tipo Trabajo Error', Activo__c = true));
        
        // SUBTIPO_TRABAJO
        parametricas.add(new Parametrica__c(Name = 'STT003', Tipo__c = 'SUBTIPO_TRABAJO', Valor__c = 'Subtipo Trabajo Error', Activo__c = true));
        
        insert parametricas;
        
        // Actualizar la oportunidad con los valores necesarios
        oports.Centro__c = 'Centro Test Error Ingenieria';
        oports.Division_SAP_Ingenieria__c = 'Division Ingenieria Error';
        oports.Pais__c = 'PT';
        oports.Tipo_de_Trabajo__c = 'Tipo Trabajo Error';
        oports.Subtipo_de_Trabajo__c = 'Subtipo Trabajo Error';
        update oports;
        
        // Perform test
        Test.startTest();
        String resultJsonStr = CreacionOfertaIngenieriaController.OfferGeneratorApex(oports.Id);
        Test.stopTest();
        
        Map<String, Object> resultJson = (Map<String, Object>) System.JSON.deserializeUntyped(resultJsonStr);
        System.debug('test_OfferGeneratorApex_Error - resultJson: ' + resultJson);
    }
}