force-app/main/default/objects/Account/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <inlineHelpText>Área diferenciada de la actividad económica y productiva en la que se engloba la empresa.</inlineHelpText>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Admón. Pública</fullName>
            </value>
            <value>
                <fullName>Educación</fullName>
            </value>
            <value>
                <fullName>Engineering and Architecture</fullName>
                <isActive>false</isActive>
                <label>Engineering and Architecture</label>
            </value>
            <value>
                <fullName>Financiero</fullName>
                <isActive>false</isActive>
                <label>Financiero</label>
            </value>
            <value>
                <fullName>Finanzas</fullName>
            </value>
            <value>
                <fullName>Industria</fullName>
            </value>
            <value>
                <fullName>Ingeniería Industrial</fullName>
            </value>
            <value>
                <fullName>Ingeniería y Arquitectura</fullName>
            </value>
            <value>
                <fullName>Sanidad</fullName>
            </value>
            <value>
                <fullName>Sector al que pertenece</fullName>
                <isActive>false</isActive>
                <label>Sector al que pertenece</label>
            </value>
            <value>
                <fullName>Sector Público</fullName>
                <isActive>false</isActive>
                <label>Sector Público</label>
            </value>
            <value>
                <fullName>Seguros</fullName>
            </value>
            <value>
                <fullName>Servicios</fullName>
            </value>
            <value>
                <fullName>Tecnologías de la información</fullName>
                <isActive>false</isActive>
                <label>Tecnologías de la información</label>
            </value>
            <value>
                <fullName>Telco y Media</fullName>
            </value>
            <value>
                <fullName>Utilities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CRM_Ibermatica_Configuration__c/CRM_Ibermatica_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CRM Ibermatica Configuration</label>
</CustomObject>

force-app/main/default/objects/CRM_Ibermatica_Configuration__c/fields/client_id__c.field-meta.xml
<CustomField>
    <fullName>client_id__c</fullName>
    <label>client-id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_Ibermatica_Configuration__c/fields/client_secret__c.field-meta.xml
<CustomField>
    <fullName>client_secret__c</fullName>
    <label>client-secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_Ibermatica_Configuration__c/fields/URL_Consulta_New_File__c.field-meta.xml
<CustomField>
    <fullName>URL_Consulta_New_File__c</fullName>
    <label>URL Consulta New File</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_Ibermatica_Configuration__c/fields/URL_Existe_Doc_New_File__c.field-meta.xml
<CustomField>
    <fullName>URL_Existe_Doc_New_File__c</fullName>
    <label>URL Existe Doc New File</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_Ibermatica_Configuration__c/fields/URL_Preventa__c.field-meta.xml
<CustomField>
    <fullName>URL_Preventa__c</fullName>
    <label>URL Preventa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/No_ejecutar_triggers__c/No_ejecutar_triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>No ejecutar triggers</label>
</CustomObject>

force-app/main/default/objects/No_ejecutar_triggers__c/fields/Correo_usuario__c.field-meta.xml
<CustomField>
    <fullName>Correo_usuario__c</fullName>
    <label>Correo usuario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Objetivo__c/Objetivo__c.object-meta.xml
<CustomObject>
    <label>Objetivo</label>
    <nameField>
        <label>Objetivo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objetivos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Objetivo__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad/Oferta</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Objetivos</relationshipLabel>
    <relationshipName>Objetivos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/Parametrica_2__c.object-meta.xml
<CustomObject>
    <description>Parametrica que contiene los datos de Ibermatica</description>
    <label>Parametrica Ibermática</label>
    <nameField>
        <label>Nombre de Parametrica Ibermática</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parametricas Ibermática</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parametrica_2__c/fields/Organizacion_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Organizacion_Comercial__c</fullName>
    <label>Organización Comercial</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica__c/Parametrica__c.object-meta.xml
<CustomObject>
    <description>Paramátrica con Lista de Valores</description>
    <label>Paramétrica</label>
    <nameField>
        <label>Código</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paramétricas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parametrica__c/fields/Maestro__c.field-meta.xml
<CustomField>
    <fullName>Maestro__c</fullName>
    <label>Maestro</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Asesoría Jurídica</fullName>
            </value>
            <value>
                <fullName>Authorised Officer</fullName>
            </value>
            <value>
                <fullName>Business Unit</fullName>
            </value>
            <value>
                <fullName>CCO</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CMO</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>CSO</fullName>
            </value>
            <value>
                <fullName>Delivery Center</fullName>
            </value>
            <value>
                <fullName>Dir. Financiera Corporativa</fullName>
            </value>
            <value>
                <fullName>Dir. Intenacional</fullName>
            </value>
            <value>
                <fullName>Director Q&amp;A</fullName>
            </value>
            <value>
                <fullName>División</fullName>
            </value>
            <value>
                <fullName>Línea de Sevicios</fullName>
            </value>
            <value>
                <fullName>Mercado</fullName>
            </value>
            <value>
                <fullName>País</fullName>
            </value>
            <value>
                <fullName>Resp. Preventa</fullName>
            </value>
            <value>
                <fullName>Sociedad</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parametrica__c/fields/Mercado_lookup__c.field-meta.xml
<CustomField>
    <fullName>Mercado_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mercado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Parametrica__c.Maestro__c</field>
            <operation>equals</operation>
            <value>Mercado</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Parametrica__c</referenceTo>
    <relationshipLabel>Paramétricas</relationshipLabel>
    <relationshipName>Mercado_lookup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parametrica__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <label>Valor</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tarea_aprobacion__c/Tarea_aprobacion__c.object-meta.xml
<CustomObject>
    <label>Tarea de aprobación</label>
    <nameField>
        <label>Nombre de Tarea de aprobación</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tareas de aprobación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tarea_aprobacion__c/fields/Decision__c.field-meta.xml
<CustomField>
    <fullName>Decision__c</fullName>
    <label>Decisión</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>En proceso</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tarea_aprobacion__c/fields/Fecha_solicitud__c.field-meta.xml
<CustomField>
    <fullName>Fecha_solicitud__c</fullName>
    <label>Fecha solicitud</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tarea_aprobacion__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Tareas de aprobación</relationshipLabel>
    <relationshipName>Tareas_de_aprobaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tarea_aprobacion__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Preliminar</fullName>
            </value>
            <value>
                <fullName>Oferta</fullName>
            </value>
            <value>
                <fullName>Socios</fullName>
            </value>
            <value>
                <fullName>Subcontratas</fullName>
                <label>Subcontratacion</label>
            </value>
            <value>
                <fullName>Borrador Acuerdo Socios</fullName>
            </value>
            <value>
                <fullName>Oferta QA Técnico</fullName>
            </value>
            <value>
                <fullName>Oferta QA Económico</fullName>
            </value>
            <value>
                <fullName>Aprobación Preventa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Tarea_aprobacion_Test.cls
@isTest
public class Tarea_aprobacion_Test {
    @testSetup static void setup() {
        No_ejecutar_triggers__c saltar_trigger = new No_ejecutar_triggers__c();
        saltar_trigger.Correo_usuario__c='soporteoaci@ayesa.com.invalid';
        insert saltar_trigger;
        
        insert new CRM_Ibermatica_Configuration__c(
            client_id__c = '12345',
            client_secret__c='453345',
            URL_Consulta_New_File__c='http://test.com',
            URL_Existe_Doc_New_File__c='http://test.com',
            URL_Preventa__c='http://test.com'
        );
        
        Parametrica__c  mercado = new Parametrica__c(
            Name ='DIGITAL ADMINISTRATION & HEALTH',
            Valor__c ='60029413',
            Maestro__c ='Mercado',
            Tipo__c='Valor'
        );
        insert mercado;
        Parametrica__c  division = new Parametrica__c(
            Name ='DIGITAL ADMINISTRATION & HEALTH',
            Valor__c ='60049219',
            Maestro__c ='División',
            Tipo__c='Valor',
            Mercado_lookup__c =mercado.Id
        );
        insert division;
        
        Parametrica_2__c org = new Parametrica_2__c (
            Name ='60049219',
            Organizacion_Comercial__c='DIGITAL ADMINISTRATION'
        );
        insert org;   
    }

    @isTest
    public static void Aprobacion_Oferta(){
        // Crear Opportunity de prueba usando TestDataFactory
        Opportunity op = TestDataFactory.createOpportunity('Cualificación', 'Digital impact','IT_DS');

        // Crear tareas de aprobación vinculadas a la Opportunity
        List<Tarea_aprobacion__c> tareas_insert = new List<Tarea_aprobacion__c>(); 
        tareas_insert.add(new Tarea_aprobacion__c(Name='Prelim 1', Fecha_solicitud__c = Date.today(), Decision__c ='En proceso', Tipo__c = 'Preliminar', Opportunity__c = op.Id));
        tareas_insert.add(new Tarea_aprobacion__c(Name='Prelim 2', Fecha_solicitud__c = Date.today(), Decision__c ='En proceso', Tipo__c = 'Preliminar', Opportunity__c = op.Id));
        tareas_insert.add(new Tarea_aprobacion__c(Name='Oferta 1', Fecha_solicitud__c = Date.today(), Decision__c ='En proceso', Tipo__c = 'Oferta', Opportunity__c = op.Id));
        tareas_insert.add(new Tarea_aprobacion__c(Name='Oferta 2', Fecha_solicitud__c = Date.today(), Decision__c ='En proceso', Tipo__c = 'Oferta', Opportunity__c = op.Id));
        insert tareas_insert;

        Test.startTest();
        // Cambiar decisiones para disparar lógica AFTER UPDATE del trigger
        tareas_insert[0].Decision__c = 'Aprobado';
        tareas_insert[1].Decision__c = 'Rechazado';
        tareas_insert[2].Decision__c = 'Aprobado';
        tareas_insert[3].Decision__c = 'Rechazado';
        update tareas_insert;
        Test.stopTest();

        // Comprobaciones: validar que las tareas han quedado con las decisiones esperadas
        List<Tarea_aprobacion__c> tareasAfter = [
            SELECT Id, Tipo__c, Decision__c
            FROM Tarea_aprobacion__c
            WHERE Opportunity__c = :op.Id
        ];
        Integer countOfertaAprobado = 0;
        Integer countOfertaRechazado = 0;
        Integer countPrelimAprobado = 0;
        Integer countPrelimRechazado = 0;
        for (Tarea_aprobacion__c t : tareasAfter) {
            if (t.Tipo__c == 'Oferta') {
                if (t.Decision__c == 'Aprobado') countOfertaAprobado++;
                if (t.Decision__c == 'Rechazado') countOfertaRechazado++;
            }
            if (t.Tipo__c == 'Preliminar') {
                if (t.Decision__c == 'Aprobado') countPrelimAprobado++;
                if (t.Decision__c == 'Rechazado') countPrelimRechazado++;
            }
        }
        System.assertEquals(1, countOfertaAprobado, 'Debe haber 1 oferta aprobada');
        System.assertEquals(1, countOfertaRechazado, 'Debe haber 1 oferta rechazada');
        System.assertEquals(1, countPrelimAprobado, 'Debe haber 1 preliminar aprobada');
        System.assertEquals(1, countPrelimRechazado, 'Debe haber 1 preliminar rechazada');

        // Nota: no se comprueba Decision_* en Opportunity porque el trigger evita actualizar Opportunity en Test.isRunningTest() en el código actual.
    }

    @isTest
    public static void AprobacionPorObjetivo() {
        // Crear cuenta y objetivo de prueba
        Account cuenta = new Account(
            Name = 'Cliente objetivo test',
            Sector__c = 'Industria',
            Subsector__c = 'Fabricantes varios'
        );
        insert cuenta;

        Objetivo__c objetivo = new Objetivo__c(
            Name = 'Objetivo Test',
            Cuenta__c = cuenta.Id
        );
        insert objetivo;

        // Crear dos tareas vinculadas al mismo objetivo; la más reciente cambiará la decisión
        Tarea_aprobacion__c t1 = new Tarea_aprobacion__c(
            Name = 'Tarea 1',
            Fecha_solicitud__c = Date.today(),
            Decision__c = 'En proceso',
            Tipo__c = 'Preliminar',
            Objetivo__c = objetivo.Id
        );
        Tarea_aprobacion__c t2 = new Tarea_aprobacion__c(
            Name = 'Tarea 2',
            Fecha_solicitud__c = Date.today().addDays(-1),
            Decision__c = 'En proceso',
            Tipo__c = 'Preliminar',
            Objetivo__c = objetivo.Id
        );
        insert new List<Tarea_aprobacion__c>{ t1, t2 };

        Test.startTest();
        // Actualizamos la más reciente a 'Aprobado' y la trigger debe propagar la decisión a la anterior en estado "En proceso"
        t1.Decision__c = 'Aprobado';
        update t1;
        Test.stopTest();

        Tarea_aprobacion__c t2After = [SELECT Id, Decision__c FROM Tarea_aprobacion__c WHERE Id = :t2.Id LIMIT 1];
        System.assertEquals('Aprobado', t2After.Decision__c, 'La decisión del tarea anterior debe haberse propagado a Aprobado');
    }
}