force-app/main/default/objects/Account/fields/SIC__c.field-meta.xml
<CustomField>
    <fullName>SIC__c</fullName>
    <label>SIC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/Parametrica_2__c.object-meta.xml
<CustomObject>
    <description>Parametrica que contiene los datos de Ibermatica</description>
    <label>Parametrica Ibermática</label>
    <nameField>
        <label>Nombre de Parametrica Ibermática</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parametricas Ibermática</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parametrica_2__c/fields/Campanya__c.field-meta.xml
<CustomField>
    <fullName>Campanya__c</fullName>
    <label>Campaña</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Centro_Res_Super_lookup__c.field-meta.xml
<CustomField>
    <fullName>Centro_Res_Super_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centro Responsabilidad Super</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Parametrica_2__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Centro Responsabilidad</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Parametrica_2__c</referenceTo>
    <relationshipLabel>Parametricas Ibermática (Centro Responsabilidad Super)</relationshipLabel>
    <relationshipName>CR_lookup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Centro_resp_Super__c.field-meta.xml
<CustomField>
    <fullName>Centro_resp_Super__c</fullName>
    <label>Centro resp. Super</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/CNAE__c.field-meta.xml
<CustomField>
    <fullName>CNAE__c</fullName>
    <label>CNAE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Codigo_CNAE__c.field-meta.xml
<CustomField>
    <fullName>Codigo_CNAE__c</fullName>
    <label>Codigo CNAE</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Codigo_CR__c.field-meta.xml
<CustomField>
    <fullName>Codigo_CR__c</fullName>
    <label>Codigo CR</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Codigo_Gestor_Produccion__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Gestor_Produccion__c</fullName>
    <label>Codigo Gestor Produccion</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Codigo_SIC__c.field-meta.xml
<CustomField>
    <fullName>Codigo_SIC__c</fullName>
    <label>Codigo SIC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Desglose_importes__c.field-meta.xml
<CustomField>
    <fullName>Desglose_importes__c</fullName>
    <inlineHelpText>Opciones: Sí / No</inlineHelpText>
    <label>Desglose importes</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>Activo</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>Inactivo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Gestor_de_produccion__c.field-meta.xml
<CustomField>
    <fullName>Gestor_de_produccion__c</fullName>
    <label>Gestor de produccion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Gestor_de_produccion_lookup__c.field-meta.xml
<CustomField>
    <fullName>Gestor_de_produccion_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gestor de produccion</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Parametrica_2__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Gestor Produccion</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Parametrica_2__c</referenceTo>
    <relationshipLabel>Parametricas Ibermática (Gestor de produccion)</relationshipLabel>
    <relationshipName>Gestor_de_produccion_lookup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/SIC__c.field-meta.xml
<CustomField>
    <fullName>SIC__c</fullName>
    <label>SIC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/recordTypes/CNAE.recordType-meta.xml
<RecordType>
    <fullName>CNAE</fullName>
    <active>true</active>
    <label>CNAE</label>
</RecordType>

force-app/main/default/objects/Parametrica_2__c/recordTypes/Gestor_Produccion.recordType-meta.xml
<RecordType>
    <fullName>Gestor_Produccion</fullName>
    <active>true</active>
    <label>Gestor Produccion</label>
</RecordType>

force-app/main/default/objects/Parametrica_2__c/recordTypes/SIC.recordType-meta.xml
<RecordType>
    <fullName>SIC</fullName>
    <active>true</active>
    <label>SIC</label>
</RecordType>

force-app/main/default/classes/CRM_IB_Controller_Test.cls
@isTest
public class CRM_IB_Controller_Test {
    
    @isTest
    public static void All_Test(){
        
        List<Account> cuenta = TestDataFactory.createClientes(1);
        
        Test.startTest();
        CRM_IB_Controller.saveAccount_CNAE('1234',cuenta[0].Id);
        
        CRM_IB_Controller.saveAccount_SIC('1234',cuenta[0].Id);
        
    }
    @isTest
    public static void valoresCnae(){
        
        List<Account> cuenta = TestDataFactory.createClientes(1);
        List <Parametrica_2__c> parametricas_insert = new List <Parametrica_2__c>();
        List <Parametrica_2__c> parametricas_insert_2 = new List <Parametrica_2__c>();
        
        Id RT_CR = Schema.SObjectType.Parametrica_2__c.getRecordTypeInfosByName().get('Centro Responsabilidad').getRecordTypeId();
        Id RT_GP = Schema.SObjectType.Parametrica_2__c.getRecordTypeInfosByName().get('Gestor Produccion').getRecordTypeId();
        Id RT_CR_GP = Schema.SObjectType.Parametrica_2__c.getRecordTypeInfosByName().get('Gestor Produccion - Centro Responsabilidad').getRecordTypeId();
        Id RT_CNAE = Schema.SObjectType.Parametrica_2__c.getRecordTypeInfosByName().get('CNAE').getRecordTypeId();
        Id RT_SIC = Schema.SObjectType.Parametrica_2__c.getRecordTypeInfosByName().get('SIC').getRecordTypeId();

        Parametrica_2__c paramGP = new Parametrica_2__c (Name ='Prueba',Codigo_Gestor_Produccion__c ='313', Gestor_de_produccion__c ='Usuario prueba',Tipo__c ='Gestor_Produccion', RecordTypeId =RT_GP, Estado__c='1');
        Parametrica_2__c paramCR = new Parametrica_2__c (Name ='Prueba GP',  Centro_resp_Super__c='Centro prueba',Codigo_CR__c='015',Desglose_importes__c='Sí', RecordTypeId =RT_CR,Estado__c='1');

        parametricas_insert.add(paramGP);
        parametricas_insert.add(paramCR);

        Parametrica_2__c paramCNAE = new Parametrica_2__c (Name ='Prueba CNAE',Tipo__c ='CNAE',Codigo_CNAE__c ='111', CNAE__c='CNAE valor',RecordTypeId=RT_CNAE,Estado__c='1');
        parametricas_insert.add(paramCNAE);

        Parametrica_2__c paramSIC = new Parametrica_2__c (Name ='Prueba SIC',Tipo__c ='SIC',Codigo_SIC__c =111, SIC__c='SIC valor', RecordTypeId=RT_SIC,Estado__c='1');
        parametricas_insert.add(paramSIC);
       
        Parametrica_2__c paramCampanya= new Parametrica_2__c (Name ='Prueba Campaña',Tipo__c ='Campaña',Campanya__c='Campaña Prueba',Estado__c='1');
        parametricas_insert.add(paramCampanya);
        
        insert parametricas_insert;
        Parametrica_2__c paramCR_GP = new Parametrica_2__c (Name ='Prueba CR y GP', Centro_Res_Super_lookup__c= paramCR.Id, Gestor_de_produccion_lookup__c= paramGP.Id, RecordTypeId = RT_CR_GP,Estado__c='1');
        parametricas_insert_2.add(paramCR_GP);
        
        insert parametricas_insert_2;
        
        Test.startTest();
 
        String result11= CRM_IB_Controller.valoresCNAESIC(cuenta[0].id);
        
        Test.stopTest();
    }
}