force-app/main/default/objects/Account/fields/SIC__c.field-meta.xml
<CustomField>
    <fullName>SIC__c</fullName>
    <label>SIC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/Parametrica_2__c.object-meta.xml
<CustomObject>
    <description>Parametrica que contiene los datos de Ibermatica</description>
    <label>Parametrica Ibermática</label>
    <nameField>
        <label>Nombre de Parametrica Ibermática</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parametricas Ibermática</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parametrica_2__c/fields/CNAE__c.field-meta.xml
<CustomField>
    <fullName>CNAE__c</fullName>
    <label>CNAE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Codigo_CNAE__c.field-meta.xml
<CustomField>
    <fullName>Codigo_CNAE__c</fullName>
    <label>Codigo CNAE</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Codigo_CNAE_num__c.field-meta.xml
<CustomField>
    <fullName>Codigo_CNAE_num__c</fullName>
    <label>Codigo CNAE num</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Codigo_SIC__c.field-meta.xml
<CustomField>
    <fullName>Codigo_SIC__c</fullName>
    <label>Codigo SIC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/SIC__c.field-meta.xml
<CustomField>
    <fullName>SIC__c</fullName>
    <label>SIC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/recordTypes/CNAE.recordType-meta.xml
<RecordType>
    <fullName>CNAE</fullName>
    <active>true</active>
    <label>CNAE</label>
</RecordType>

force-app/main/default/objects/Parametrica_2__c/recordTypes/SIC.recordType-meta.xml
<RecordType>
    <fullName>SIC</fullName>
    <active>true</active>
    <label>SIC</label>
</RecordType>

force-app/main/default/classes/CRM_IB_Controller.cls
public class CRM_IB_Controller {
    
    
    @AuraEnabled
    public static String saveAccount_CNAE(String CNAE, String Id_account){
        
        System.debug('Id account: ' + Id_account);
        System.debug('Id CNAE: ' + CNAE);
        Account acc = [SELECT Id,Name FROM Account where Id =: Id_account];
        
        
        //Parametrica_2__c valores_CNAE = [SELECT Id, name, Codigo_CNAE__c, CNAE__c, Tipo__c, RecordType.name from Parametrica_2__c where tipo__c = 'CNAE' and CNAE__c =: CNAE Limit 1];
        
        
        acc.CNAE__c = CNAE;
        try{
            
            update acc;
            
        } catch(DMLException e){ 
            System.debug('Error CNAE Account: ' + e.getMessage());
            return e.getMessage();            
        }	
        system.debug('Actualizado');
        return 'Actualizado';
        
    }
    
    @AuraEnabled
    public static String saveAccount_SIC(String SIC, String Id_account){
        
        System.debug('Id account: ' + Id_account);
        System.debug('Id SIC: ' + SIC);
        Account acc = [SELECT Id,Name FROM Account where Id =: Id_account];
        
        
        //Parametrica_2__c valores_CNAE = [SELECT Id, name, Codigo_CNAE__c, CNAE__c, Tipo__c, RecordType.name from Parametrica_2__c where tipo__c = 'CNAE' and CNAE__c =: CNAE Limit 1];
        
        
        acc.SIC__c = SIC;
        try{
            
            update acc;
            
        } catch(DMLException e){ 
            System.debug('Error SIC Account: ' + e.getMessage());
            return e.getMessage();            
        }	
        system.debug('Actualizado');
        return 'Actualizado';
        
    }
    @AuraEnabled
    public static String valoresCNAESIC(String Id_Account){
        String result = '';
        
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        List <Parametrica_2__c> valores_CNAE= [SELECT Id, name, Codigo_CNAE__c, Codigo_CNAE_num__c,CNAE__c, Tipo__c, RecordType.Name
                                               from Parametrica_2__c 
                                               where RecordType.Name = 'CNAE' order by Codigo_CNAE_num__c];
        List <Parametrica_2__c> valores_SIC= [SELECT Id, name, Codigo_SIC__c, SIC__c, Tipo__c, RecordType.name
                                              from Parametrica_2__c 
                                              where RecordType.Name = 'SIC' order by Codigo_SIC__c];
        List <String> valoresCNAE = new List<String>();
        List <String> valoresSIC = new List<String>();
        
        for (Parametrica_2__c param: valores_CNAE){
            if(param.RecordType.Name == 'CNAE' && !valoresCNAE.contains(param.Codigo_CNAE_num__c +' - '+param.CNAE__c)){
                valoresCNAE.add(param.Codigo_CNAE_num__c +' - '+param.CNAE__c);
            }
        }
        
        for (Parametrica_2__c param: valores_SIC){
            if(param.RecordType.Name == 'SIC' && !valoresCNAE.contains(param.Codigo_SIC__c +' - '+param.SIC__c)){
                valoresSIC.add(param.Codigo_SIC__c +' - '+param.SIC__c);
            }
        }
        
        Account acc = [SELECT Id,Name, CNAE__c, SIC__c FROM Account where Id =: Id_Account];
        System.debug('Cuenta recuperada '+ acc.Name + 'Y su valor CNAE ' + acc.CNAE__c  );
        
        gen.writeObjectField('CNAE', valoresCNAE);
        gen.writeObjectField('SIC', valoresSIC);
        gen.writeObjectField('Account', acc);
        
        gen.writeEndObject();
        
        result = gen.getAsString();
        
        return result;
    }
}