force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <description>Gestión de Tickets</description>
    <label>Ticket</label>
    <nameField>
        <label>Nombre del Ticket</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Acumulado_Abierto__c.field-meta.xml
<CustomField>
    <fullName>Acumulado_Abierto__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Se informa al cambiar el estado a bloqueado con PB “Control Caso Bloqueado”</description>
    <label>Acumulado Abierto</label>
    <precision>11</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nuevo</fullName>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>Asignado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Pdt Terceros</fullName>
            </value>
            <value>
                <fullName>Resuelto</fullName>
            </value>
            <value>
                <fullName>Cerrado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Fecha_Abierta__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Abierta__c</fullName>
    <description>Se informa mediante un PB con la fecha NOW al crearse/modificarse un caso a diferente de “Bloqueado”. El PB “Ticket Bloqueado” se encarga de limpiar la Fecha Bloqueo.</description>
    <label>Fecha Abierta</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Modulo__c.field-meta.xml
<CustomField>
    <fullName>Modulo__c</fullName>
    <label>Módulo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Modulo</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Prioridad__c.field-meta.xml
<CustomField>
    <fullName>Prioridad__c</fullName>
    <label>Prioridad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Baja</fullName>
                <default>true</default>
                <label>Baja</label>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Alta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/SLA__c.field-meta.xml
<CustomField>
    <fullName>SLA__c</fullName>
    <label>SLA</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Petición</fullName>
                <default>true</default>
                <label>Petición</label>
            </value>
            <value>
                <fullName>Duda</fullName>
            </value>
            <value>
                <fullName>Incidencia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Modulo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BASIS</fullName>
    </customValue>
    <customValue>
        <fullName>BILLING</fullName>
    </customValue>
    <customValue>
        <fullName>BO</fullName>
    </customValue>
    <customValue>
        <fullName>BW</fullName>
    </customValue>
    <customValue>
        <fullName>CRM</fullName>
    </customValue>
    <customValue>
        <fullName>DM</fullName>
    </customValue>
    <customValue>
        <fullName>ERP</fullName>
    </customValue>
    <customValue>
        <fullName>FICA</fullName>
    </customValue>
    <customValue>
        <fullName>MCF</fullName>
    </customValue>
    <customValue>
        <fullName>Otros</fullName>
    </customValue>
    <customValue>
        <fullName>PO</fullName>
    </customValue>
    <customValue>
        <fullName>SD</fullName>
    </customValue>
    <customValue>
        <fullName>WM</fullName>
    </customValue>
    <masterLabel>Módulo</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SendEmail_Test.cls
@isTest (SeeAllData = false)
public class SendEmail_Test {
    
    @testSetup static void setup() { 
        Id currentUserId = UserInfo.getUserId();
        User currentUser = [SELECT Id, Name, Alias, Email FROM User WHERE Id = :currentUserId];
        Profile p = [SELECT Id FROM Profile LIMIT 1];
        
        User u = new User(
            Alias = 'testuser',
            Email = 'testuser@example.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Test',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = p.Id,
            TimeZoneSidKey = 'America/New_York',
            Username = 'testuser+' + DateTime.now().getTime() + '@example.com'
        );
        
        insert u;
        DateTime ahora = DateTime.newInstance(2024, 6, 5, 10, 0, 0); // Fecha laboral válida
        System.runAs(u) {
            Ticket__c ticket = new Ticket__c (
                Name = 'Test2',
                Estado__c = 'Nuevo',
                Acumulado_Abierto__c = 9,
                Modulo__c = 'FICA',
                SLA__c = 9.5,
                Tipo__c = 'Incidencia',
                Prioridad__c = 'Baja',
                Fecha_Abierta__c = ahora
            );
            insert ticket;
            ticket.Estado__c = 'Asignado';
            update ticket;
        }  
    }
    
    static TestMethod void enviarmail(){
        Test.startTest(); 
        Datetime dt = Datetime.now().addMinutes(1); 
        String CRON_EXP = '0 '+ dt.minute() + ' * ' + dt.day() + ' ' + dt.month() + ' ? ' + dt.year();
        String jobId = System.schedule('Sample_Heading', CRON_EXP, new SendEmail() );
        Test.stopTest();
        
    }
}