force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <description>Gestión de Tickets</description>
    <label>Ticket</label>
    <nameField>
        <label>Nombre del Ticket</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Codigo_del_ticket__c.field-meta.xml
<CustomField>
    <fullName>Codigo_del_ticket__c</fullName>
    <displayFormat>TCK-{000000}</displayFormat>
    <label>Código del ticket</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripción</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nuevo</fullName>
                <default>true</default>
                <label>Nuevo</label>
            </value>
            <value>
                <fullName>Asignado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Pdt Terceros</fullName>
            </value>
            <value>
                <fullName>Resuelto</fullName>
            </value>
            <value>
                <fullName>Cerrado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Horas_Abierto_Total__c.field-meta.xml
<CustomField>
    <fullName>Horas_Abierto_Total__c</fullName>
    <formula>IF (ISBLANK(datevalue(Fecha_Abierta__c)), Acumulado_Abierto__c, 

Horas_Abierto__c 

+ Acumulado_Abierto__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Horas Abierto Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Prioridad__c.field-meta.xml
<CustomField>
    <fullName>Prioridad__c</fullName>
    <label>Prioridad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Baja</fullName>
                <default>true</default>
                <label>Baja</label>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Alta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/SLA__c.field-meta.xml
<CustomField>
    <fullName>SLA__c</fullName>
    <label>SLA</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Petición</fullName>
                <default>true</default>
                <label>Petición</label>
            </value>
            <value>
                <fullName>Duda</fullName>
            </value>
            <value>
                <fullName>Incidencia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SendEmail.cls
global class SendEmail implements Schedulable{
    
    global void execute(SchedulableContext SC) {
        
        EmailTemplate templateId = [select id, Subject, HtmlValue, Body from EmailTemplate where Name= 'Cumplimiento SLA' limit 1];
        List<String> sendTo = new List<String>();
        
        Ticket__c[] tickets = [Select id, SLA__c, Horas_Abierto_Total__c, Owner.email, Owner.Name, Codigo_del_ticket__c, Name, Tipo__c, Prioridad__c,Descripcion__c from Ticket__c where Estado__c = 'Asignado' and Tipo__c = 'Incidencia'];     
        
        for (Integer i=0; i<tickets.size(); i++){
            if ( Test.isRunningTest() || tickets[i].SLA__c - tickets[i].Horas_Abierto_Total__c <=1){
                
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                String fullRecordURL = URL.getOrgDomainUrl().toExternalForm() + '/' + tickets[i].Id;
                string propietario = tickets[i].Owner.email;
                string asignados = tickets[i].Owner.id;
                
                String subject = templateId.Subject;
                subject = subject.replace('{!Ticket__c.Codigo_del_ticket__c', tickets[i].Codigo_del_ticket__c);                
                
                String plainBody = templateId.Body;
                plainBody = plainBody.replace('{!Ticket__c.Codigo_del_ticket__c', tickets[i].Codigo_del_ticket__c);
                plainBody = plainBody.replace('{!Ticket__c.OwnerFullName}', tickets[i].Owner.Name);
                plainBody = plainBody.replace('{!Ticket__c.Name}', tickets[i].Name);
                plainBody = plainBody.replace('{!Ticket__c.Link}', fullRecordURL);
                
                sendTo.add(propietario);
                
                mail.setToAddresses(sendTo);
                integer indice = sendTo.size() - 1;
                mail.setTemplateId(templateId.Id);
                mail.setTargetObjectId(asignados);
                mail.setSaveAsActivity(false);
                mail.setSubject(subject);
                mail.setPlainTextBody(plainBody);
                mail.setSenderDisplayName('Quito Support');
                
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
                sendTo.remove(indice);
            }
        }
        
    }
    
}