force-app/main/default/objects/Historico_estado_proyecto__c/Historico_estado_proyecto__c.object-meta.xml
<CustomObject>
    <label>Historico estado proyecto</label>
    <nameField>
        <label>Nombre de Historico</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Historico estado proyecto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Historico_estado_proyecto__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código de Proyecto</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_estado_proyecto__c/fields/Fecha_Datos_Economicos__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Datos_Economicos__c</fullName>
    <label>Fecha Datos Economicos</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Historico_estado_proyecto__c/fields/Fecha_insercion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_insercion__c</fullName>
    <label>Fecha Inserción</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Historico_estado_proyecto__c/fields/Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Histórico proyecto</relationshipLabel>
    <relationshipName>Historico_estado_proyecto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proyecto__c/Proyecto__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre del Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proyecto__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Código de Proyecto</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Proyecto__c/fields/Fecha_Datos_Economicos__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Datos_Economicos__c</fullName>
    <label>Fecha Datos Económicos</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/GC_Autom_Historicos_Proyecto_Test.cls
@isTest
public with sharing class GC_Autom_Historicos_Proyecto_Test {
    
    @TestSetup
    static void makeData(){
        Test.startTest();
        List <Proyecto__c> proyectos = new List <Proyecto__c>();
        List <Historico_Estado_proyecto__c> historicos = new List <Historico_estado_proyecto__c>();
        for(Integer i=100;i<=250;i++){
            Proyecto__c p= new Proyecto__c();
            p.Name='Project Test';
            p.Codigo__c ='P99/9'+i;
            proyectos.add(p); 
            
            Historico_estado_proyecto__c myNewHistorico = new Historico_estado_proyecto__c();
            
            myNewHistorico.Fecha_Insercion__c=Datetime.now();
            myNewHistorico.Name= p.Codigo__c+' - '+string.valueof(date.today());
            myNewHistorico.Fecha_Datos_Economicos__c=Date.today().addMonths(-3);
             myNewHistorico.Proyecto__c=p.Id;
            historicos.add(myNewHistorico);
        }
        insert proyectos;
        insert historicos;
        
        Test.stopTest();
    }
    
    @isTest
    public static void test1(){
        
        Test.startTest();
        
        GC_Automatizacion_Historicos_Proyecto sch = new GC_Automatizacion_Historicos_Proyecto();
        ID batchprocessid = Database.executeBatch(sch);
        
        Test.stopTest();
    }
    
    
}