force-app/main/default/objects/Control_Integracion__c/Control_Integracion__c.object-meta.xml
<CustomObject>
    <label>Control de Integracion</label>
    <nameField>
        <label>Nombre de Control de Integraciones</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Controles de Integraciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Control_Integracion__c/fields/Error_Code__c.field-meta.xml
<CustomField>
    <fullName>Error_Code__c</fullName>
    <label>Error Code</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Control_Integracion__c/fields/Interfaz__c.field-meta.xml
<CustomField>
    <fullName>Interfaz__c</fullName>
    <label>Interfaz</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Control_Integracion__c/fields/Metodo__c.field-meta.xml
<CustomField>
    <fullName>Metodo__c</fullName>
    <label>Metodo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Control_Integracion__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Control_Integracion__c/fields/Servicio__c.field-meta.xml
<CustomField>
    <fullName>Servicio__c</fullName>
    <label>Servicio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_Ibermatica_Configuration__c/CRM_Ibermatica_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CRM Ibermatica Configuration</label>
</CustomObject>

force-app/main/default/objects/CRM_Ibermatica_Configuration__c/fields/URL_Existe_Doc_New_File__c.field-meta.xml
<CustomField>
    <fullName>URL_Existe_Doc_New_File__c</fullName>
    <label>URL Existe Doc New File</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/Oportunidad__c.object-meta.xml
<CustomObject>
    <label>Oportunidad</label>
    <nameField>
        <label>Tema</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Oportunidades</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Referencia_Comercial__c/Referencia_Comercial__c.object-meta.xml
<CustomObject>
    <label>Referencia Comercial</label>
    <nameField>
        <label>Referencia Comercial Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referencias Comerciales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CRM_IB_ExisteDocNewFile.cls
public class CRM_IB_ExisteDocNewFile {

	// Metodo que consulta en NewFile si estan publicados los documentos en base al operador
	// idObj: id del Objeto al que pertenece el documento
	//docs: Lista de documentos (codigos), separados por coma (',')
	// operador: (and/or) para consultar si existen todos o alguno de los documentos
    public static Boolean existeDocNewFile(Id idObj, String docs, String operador) {
        System.debug('existeDocNewFile: ' + idObj);
		Boolean existeDoc = false;
               
        //Monto endpoint
        String objType = idObj.getSObjectType().getDescribe().getName();
        String urlParams = '';
        if ('Oportunidad__c' == objType) {
            System.debug('Metodo consulta oportunidad');
			urlParams = '?ct=1&cc=' +  idObj + '&dt=' + docs + '&cp=' + operador;
           
		} else if ('Referencia_Comercial__c' == objType) {
            System.debug('Metodo consulta referencia');
			urlParams = '?ct=2&cc=' +  idObj + '&dt=' + docs + '&cp=' + operador;
          
		}
        
        CRM_Ibermatica_Configuration__c cs = CRM_Ibermatica_Configuration__c.getInstance();
        String endpoint = cs.URL_Existe_Doc_New_File__c + urlParams;
        
        Control_Integracion__c controlInt = new Control_Integracion__c();
        controlInt.Metodo__c = 'GET';
        controlInt.Interfaz__c = 'ExisteDocNewFile';
        controlInt.Servicio__c = endpoint;  
        
        Http http = new Http();
        HttpRequest request = new HttpRequest();
		request.setEndpoint(endpoint);       

        request.setMethod('GET');
        request.setHeader('Accept' , 'application/json');
        request.setHeader('Content-Type', 'application/json');
        
        System.debug('endpoint: ' + endpoint);
        
        try {
        	System.debug('ANTES RESPONSE');
            HttpResponse response = http.send(request);
            System.debug('DESPUES RESPONSE');        
            if (response != null) {
                System.debug('Response Status: ' + response.getStatusCode());
                String responseBody = response.getBody();  
                
                if (response.getStatusCode() == 200) {
                    System.debug('Response: ' + responseBody);
                    
                    Map<String,Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
                    String respuesta = (String)responseMap.get('respuesta');
                    
                    if ('si'.equals(respuesta)) {
                        existeDoc = true;
                    }
                    
                    controlInt.Response__c = responseBody;
                    controlInt.Status_Code__c = response.getStatusCode();       
                    controlInt.Error_Code__c = '00';
                    controlInt.Error_Message__c = 'OK';
            
                } else {
                    String json = response.getBody();
                    Map<String,Object> responseMap = (Map<String, Object>) System.JSON.deserializeUntyped(json);
                    System.debug('Response: ' + responseMap);
                    controlInt.Status_Code__c = response.getStatusCode();
                    controlInt.Response__c = responseBody;
                }
            } else {
                System.debug('Response null');
                controlInt.Error_Code__c = '99';
                controlInt.Error_Message__c = 'KO';
            }            
        } catch (CalloutException e) {
        	controlInt.Error_Code__c = '99';
            controlInt.Error_Message__c = e.getmessage();         
        }
        
        insert controlInt;
        System.debug('ExisteDoc:' + existeDoc);       
        return existeDoc;
    }
}