force-app/main/default/objects/Control_Integracion__c/Control_Integracion__c.object-meta.xml
<CustomObject>
    <label>Control de Integracion</label>
    <nameField>
        <label>Nombre de Control de Integraciones</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Controles de Integraciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Control_Integracion__c/fields/Error_Code__c.field-meta.xml
<CustomField>
    <fullName>Error_Code__c</fullName>
    <label>Error Code</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Control_Integracion__c/fields/Interfaz__c.field-meta.xml
<CustomField>
    <fullName>Interfaz__c</fullName>
    <label>Interfaz</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Control_Integracion__c/fields/Metodo__c.field-meta.xml
<CustomField>
    <fullName>Metodo__c</fullName>
    <label>Metodo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Control_Integracion__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Control_Integracion__c/fields/Servicio__c.field-meta.xml
<CustomField>
    <fullName>Servicio__c</fullName>
    <label>Servicio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Oportunidad__c/Oportunidad__c.object-meta.xml
<CustomObject>
    <label>Oportunidad</label>
    <nameField>
        <label>Tema</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Oportunidades</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Oportunidad__c/fields/Etapa__c.field-meta.xml
<CustomField>
    <fullName>Etapa__c</fullName>
    <label>Etapa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Captación</fullName>
            </value>
            <value>
                <fullName>Cualificación</fullName>
            </value>
            <value>
                <fullName>Demostrando</fullName>
            </value>
            <value>
                <fullName>Oferta</fullName>
            </value>
            <value>
                <fullName>Cerrada</fullName>
                <label>Presentada (negociación y cierre)</label>
            </value>
            <value>
                <fullName>Abierta</fullName>
                <isActive>false</isActive>
                <label>Abierta</label>
            </value>
            <value>
                <fullName>Anulada</fullName>
                <isActive>false</isActive>
                <label>Anulada</label>
            </value>
            <value>
                <fullName>Aprobada</fullName>
                <isActive>false</isActive>
                <label>Aprobada</label>
            </value>
            <value>
                <fullName>Aprobada QA</fullName>
                <isActive>false</isActive>
                <label>Aprobado pdte Presentar</label>
            </value>
            <value>
                <fullName>Preparando QA</fullName>
                <isActive>false</isActive>
                <label>En preparación</label>
            </value>
            <value>
                <fullName>Ganada</fullName>
                <isActive>false</isActive>
                <label>Ganada</label>
            </value>
            <value>
                <fullName>Pedido Código Oferta</fullName>
                <isActive>false</isActive>
                <label>Pedido Código Oferta</label>
            </value>
            <value>
                <fullName>Pedir Código Oferta</fullName>
                <isActive>false</isActive>
                <label>Pedir Código Oferta</label>
            </value>
            <value>
                <fullName>Pendiente QA</fullName>
                <isActive>false</isActive>
                <label>Pendiente QA</label>
            </value>
            <value>
                <fullName>Perdida</fullName>
                <isActive>false</isActive>
                <label>Perdida</label>
            </value>
            <value>
                <fullName>Presentada</fullName>
                <isActive>false</isActive>
                <label>Presentada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Oportunidad__c/fields/Etapa_Fase__c.field-meta.xml
<CustomField>
    <fullName>Etapa_Fase__c</fullName>
    <description>Etapa para el flujo de SME</description>
    <label>Etapa Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Captación</fullName>
            </value>
            <value>
                <fullName>Cualificación</fullName>
            </value>
            <value>
                <fullName>Demostrando</fullName>
            </value>
            <value>
                <fullName>Oferta</fullName>
            </value>
            <value>
                <fullName>Cerrada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Oportunidad__c/recordTypes/Ayesa.recordType-meta.xml
<RecordType>
    <fullName>Ayesa</fullName>
    <active>true</active>
    <description>Flujo de Ayesa</description>
    <label>Ayesa</label>
</RecordType>

force-app/main/default/objects/Oportunidad__c/recordTypes/Ibermatica_SME.recordType-meta.xml
<RecordType>
    <fullName>Ibermatica_SME</fullName>
    <active>true</active>
    <description>Flujo de Ibermatica SME</description>
    <label>Ibermatica SME</label>
</RecordType>

force-app/main/default/classes/CRM_IB_CambiarEstadoOppWS.cls
/**
* @author Ayesa
* @since 24-05-2023
* @desc Creacion APEX Rest integracion CR-IB 
* Cambiar el estado de la Oportunidad
*/
@RestResource(urlMapping='/CambiarEstadoOportunidad/*')
global with sharing class CRM_IB_CambiarEstadoOppWS {
    
    global class Response{
        webservice String errorCode;
        webservice String errorMessage;
        webservice String oportunidadId;
    }
    @HttpPut
    global static Response cambiarEstadoOpp(String oportunidadId){
        
        System.debug('CRM_IB_CambiarEstadoOppWS oportunidadId: ' + oportunidadId);
        
        List<Oportunidad__c> opp = [SELECT id,name,RecordType.Developername,Etapa__c 
                                    FROM Oportunidad__c WHERE Id=:oportunidadId LIMIT 1];
        
        Control_Integracion__c controlInt = new Control_Integracion__c();
        controlInt.Request__c = oportunidadId;
        controlInt.Metodo__c = 'PATCH';
        controlInt.Interfaz__c = 'ElaborarOferta';
        controlInt.Servicio__c = '/CambiarEstadoOportunidad/*';  
        
        Response res = new Response();  
        
        
        System.debug('CRM_IB_CambiarEstadoOppWS opp: ' + opp);
        
        if(!opp.isEmpty()){
            if(opp.get(0).RecordType.Developername == 'Ibermatica_SME'){
                System.debug('CRM_IB_CambiarEstadoOppWS opp: ' + opp.get(0).RecordType.Developername);
                opp.get(0).Etapa__c = 'Oferta';
                opp.get(0).Etapa_Fase__c = 'Oferta';
            }else{
                System.debug('CRM_IB_CambiarEstadoOppWS opp: ' + opp.get(0).RecordType.Developername);
                opp.get(0).Etapa__c = 'Presentada';
            }
            res.errorCode = '00';
            res.errorMessage = 'Cambio de estado OK.';
            res.oportunidadId = oportunidadId;
            
            controlInt.Status_Code__c = 201;  
            controlInt.Error_Code__c = '00';
            controlInt.Error_Message__c = 'OK';
            try{
                update opp;
                insert controlInt;
            }catch(DMLException ex){
                controlInt.Status_Code__c = 400;  
                controlInt.Error_Code__c = '98';
                controlInt.Error_Message__c = 'KO. ' + ex.getMessage();
            }
            
        }else{           
            res.errorCode = '99';
            res.errorMessage = 'KO.No existe la Oportunidad';
            res.oportunidadId = oportunidadId;
            
            controlInt.Status_Code__c = 400; 
            controlInt.Error_Code__c = '99';
            controlInt.Error_Message__c = 'Cambio de estado KO.No existe la Oportunidad';
            insert controlInt;         
        }
        
        return res;
    }
}