force-app/main/default/objects/Action__c/Action__c.object-meta.xml
<CustomObject>
    <label>Acción</label>
    <nameField>
        <label>Acción</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Acciones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Descripción</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>Fecha de compromiso</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Responsable__c.field-meta.xml
<CustomField>
    <fullName>Responsable__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Acciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abierta</fullName>
                <default>true</default>
                <label>Abierta</label>
            </value>
            <value>
                <fullName>En proceso</fullName>
            </value>
            <value>
                <fullName>Cerrada</fullName>
            </value>
            <value>
                <fullName>Validada</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action__c/fields/Task_LK__c.field-meta.xml
<CustomField>
    <fullName>Task_LK__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Task</label>
    <referenceTo>SSC__c</referenceTo>
    <relationshipLabel>Action Plan</relationshipLabel>
    <relationshipName>Actions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country_Relatioship__c/Country_Relatioship__c.object-meta.xml
<CustomObject>
    <label>Configuración País</label>
    <nameField>
        <label>País</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuración Paises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country_Relatioship__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Código del País</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country_Relatioship__c/fields/Country_Manager__c.field-meta.xml
<CustomField>
    <fullName>Country_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Countries_Relatioship</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSC__c/SSC__c.object-meta.xml
<CustomObject>
    <label>Seguimiento Soporte Corporativo</label>
    <nameField>
        <displayFormat>SSC-{00000}</displayFormat>
        <label>Task Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seguimientos Soporte Corporativo</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SSC__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País</label>
    <referenceTo>Country_Relatioship__c</referenceTo>
    <relationshipLabel>Seguimientos Soporte Corporativo</relationshipLabel>
    <relationshipName>Seguimientos_Soporte_Corporativo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSC__c/fields/Country_Manager__c.field-meta.xml
<CustomField>
    <fullName>Country_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Seguimientos_Soporte_Corporativo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSC__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abierto</fullName>
                <default>true</default>
                <label>Abierto</label>
            </value>
            <value>
                <fullName>En proceso</fullName>
            </value>
            <value>
                <fullName>Cerrado</fullName>
            </value>
            <value>
                <fullName>Validado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSC__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Asunto</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SSC_ActionsControllerTEST.cls
@isTest
public class SSC_ActionsControllerTEST {
    
   @isTest static void getActionsTest() {
        
        date myDate = date.today();
        Id userId = UserInfo.getUserId();
        Country_Relatioship__c countryRel = new Country_Relatioship__c(Name='Colombia', Country_Code__c ='CO', Country_Manager__c = userId);
        insert countryRel;
        
        SSC__c ssc = new SSC__c(Country__c = countryRel.Id, Subject__c = 'Subject SSC Task 1', Status__c = 'Abierto');
        insert ssc;
        
        
        Action__c acc1= new Action__c(Name='Test One', EndDate__c=myDate, Status__c='Abierta', Description__c='test text', Responsable__c = userId,Task_LK__c = ssc.Id);
        Action__c acc2= new Action__c(Name='Test Two', EndDate__c=myDate, Status__c='Abierta', Description__c='test text', Responsable__c = userId,Task_LK__c = ssc.Id);
        Action__c acc3= new Action__c(Name='Test Three', EndDate__c=myDate, Status__c='Abierta', Description__c='test text', Responsable__c = userId,Task_LK__c = ssc.Id);
        Action__c acc4= new Action__c(Name='Test Four', EndDate__c=myDate, Status__c='Abierta', Description__c='test text', Responsable__c = userId,Task_LK__c = ssc.Id);
        
        
        Test.startTest();
        
        insert acc1;
        acc1.Status__c = 'Cerrada';
        Database.SaveResult resultUpdate1 = Database.update(acc1, false);
        
        insert acc2;
        acc2.Status__c = 'Cerrada';
        Database.SaveResult resultUpdate2 = Database.update(acc2, false);
        
        insert acc3;
        insert acc4;
        
        List<Action__c> testList = SSC_ActionsController.getActions('Cerrada');
        System.assertEquals(testList[0].Status__c, 'Cerrada');  
        
        testList = SSC_ActionsController.getActions('Abierta');
        System.assertEquals(testList[0].Status__c, 'Abierta');
        
        testList = SSC_ActionsController.getActions('');
        System.assertEquals(testList.size(), 2);
        
        Test.stopTest();

    }
}