force-app/main/default/objects/Action__c/Action__c.object-meta.xml
<CustomObject>
    <label>Acción</label>
    <nameField>
        <label>Acción</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Acciones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Descripción</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>Fecha de compromiso</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Responsable__c.field-meta.xml
<CustomField>
    <fullName>Responsable__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Acciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abierta</fullName>
                <default>true</default>
                <label>Abierta</label>
            </value>
            <value>
                <fullName>En proceso</fullName>
            </value>
            <value>
                <fullName>Cerrada</fullName>
            </value>
            <value>
                <fullName>Validada</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action__c/fields/Task_LK__c.field-meta.xml
<CustomField>
    <fullName>Task_LK__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Task</label>
    <referenceTo>SSC__c</referenceTo>
    <relationshipLabel>Action Plan</relationshipLabel>
    <relationshipName>Actions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country_Relatioship__c/Country_Relatioship__c.object-meta.xml
<CustomObject>
    <label>Configuración País</label>
    <nameField>
        <label>País</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuración Paises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country_Relatioship__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Código del País</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country_Relatioship__c/fields/Country_Manager__c.field-meta.xml
<CustomField>
    <fullName>Country_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Countries_Relatioship</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSC__c/SSC__c.object-meta.xml
<CustomObject>
    <label>Seguimiento Soporte Corporativo</label>
    <nameField>
        <displayFormat>SSC-{00000}</displayFormat>
        <label>Task Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seguimientos Soporte Corporativo</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SSC__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País</label>
    <referenceTo>Country_Relatioship__c</referenceTo>
    <relationshipLabel>Seguimientos Soporte Corporativo</relationshipLabel>
    <relationshipName>Seguimientos_Soporte_Corporativo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSC__c/fields/Country_Manager__c.field-meta.xml
<CustomField>
    <fullName>Country_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Seguimientos_Soporte_Corporativo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SSC__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abierto</fullName>
                <default>true</default>
                <label>Abierto</label>
            </value>
            <value>
                <fullName>En proceso</fullName>
            </value>
            <value>
                <fullName>Cerrado</fullName>
            </value>
            <value>
                <fullName>Validado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SSC__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Asunto</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/updateStatusSSCTest.cls
@isTest
private class updateStatusSSCTest {
    
    @isTest static void TestAfterInsertOrUpdateAction() {
        // Test data setup
        // Create an action with an SCC Task, and then try to insert and update it
        Id userId = UserInfo.getUserId();
        Country_Relatioship__c countryRel = new Country_Relatioship__c(Name='Colombia', Country_Code__c ='CO', Country_Manager__c = userId);
        insert countryRel;
        
        SSC__c ssc = new SSC__c(Country__c = countryRel.Id, Subject__c = 'Subject SSC Task 1', Status__c = 'Abierto');
        insert ssc;

        Action__c acc1 = new Action__c(Name = 'Action 1', Description__c = 'Description 1', EndDate__c = Date.today(), Status__c = 'Abierta', Responsable__c = userId,Task_LK__c = ssc.Id);
        Action__c acc2 = new Action__c(Name = 'Action 2', Description__c = 'Description 2', EndDate__c = Date.today()+30, Status__c = 'Abierta', Responsable__c = userId,Task_LK__c = ssc.Id);
        Action__c acc3 = new Action__c(Name = 'Action 3', Description__c = 'Description 3', EndDate__c = Date.today()+60, Status__c = 'Abierta', Responsable__c = userId,Task_LK__c = ssc.Id);

        // Perform test
        Test.startTest();
        //insert acc1
        insert acc1;
        
        //update acc1
        acc1.Status__c = 'En proceso';
        Database.SaveResult resultUpdate1 = Database.update(acc1, false);
        
        //insert and delete acc2
        insert acc2;
        Database.DeleteResult result1 = Database.delete(acc2.Id, false);
        
        //update acc1
        acc1.Status__c = 'Cerrada';
        Database.SaveResult resultUpdate2 = Database.update(acc1, false);
        
        //insert acc3
        insert acc3;
        
        //delete acc3
        Database.DeleteResult result2 = Database.delete(acc3.Id, false);
        
        //update acc1
        acc1.Status__c = 'Validada';
        Database.SaveResult resultUpdate3 = Database.update(acc1, false);
        
        Test.stopTest();
        
        SSC__c resultSSC = [select Status__c from SSC__c where Id = :ssc.Id];
        System.assertEquals('Validado', resultSSC.Status__c);
        
    }
    
}