force-app/main/default/objects/Action__c/Action__c.object-meta.xml
<CustomObject>
    <label>Acción</label>
    <nameField>
        <label>Acción</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Acciones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Action__c/fields/DaysToEndDate__c.field-meta.xml
<CustomField>
    <fullName>DaysToEndDate__c</fullName>
    <formula>EndDate__c  - TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days to EndDate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>Fecha de compromiso</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Responsable__c.field-meta.xml
<CustomField>
    <fullName>Responsable__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Acciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abierta</fullName>
                <default>true</default>
                <label>Abierta</label>
            </value>
            <value>
                <fullName>En proceso</fullName>
            </value>
            <value>
                <fullName>Cerrada</fullName>
            </value>
            <value>
                <fullName>Validada</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SSC_ActionsController.cls
public class SSC_ActionsController {
@AuraEnabled
    
    public static List<Action__c> getActions(String status) {
        List <Action__c> listActions= new List<Action__c> ();
        String idUser =UserInfo.getUserId();
        
        if(status == 'Cerrada') {
            listActions = [SELECT Id, Name, EndDate__c, Status__c, DaysToEndDate__c FROM Action__c WHERE Status__c ='Cerrada' AND Responsable__c=:idUser ORDER BY EndDate__c ASC NULLS LAST];
        } else {
            listActions = [SELECT Id, Name, EndDate__c, Status__c, DaysToEndDate__c FROM Action__c WHERE Responsable__c=:idUser AND Status__c !='Cerrada' AND Status__c !='Validada' AND Status__c !='Cancelada' ORDER BY EndDate__c ASC NULLS LAST];
        }        
        System.debug('Value is =' + status);
        return listActions;
    }
}