force-app/main/default/objects/Parametrica_2__c/Parametrica_2__c.object-meta.xml
<CustomObject>
    <description>Parametrica que contiene los datos de Ibermatica</description>
    <label>Parametrica Ibermática</label>
    <nameField>
        <label>Nombre de Parametrica Ibermática</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parametricas Ibermática</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parametrica_2__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Area_Conocimiento_Tecnologica__c.field-meta.xml
<CustomField>
    <fullName>Area_Conocimiento_Tecnologica__c</fullName>
    <label>Área Conocimiento Tecnológica</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/CCI__c.field-meta.xml
<CustomField>
    <fullName>CCI__c</fullName>
    <label>CCI</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Centro_resp_Super__c.field-meta.xml
<CustomField>
    <fullName>Centro_resp_Super__c</fullName>
    <label>Centro resp. Super</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Codigo_CR__c.field-meta.xml
<CustomField>
    <fullName>Codigo_CR__c</fullName>
    <label>Codigo CR</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Codigo_Gestor_Produccion__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Gestor_Produccion__c</fullName>
    <label>Codigo Gestor Produccion</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Codigo_SIC__c.field-meta.xml
<CustomField>
    <fullName>Codigo_SIC__c</fullName>
    <label>Codigo SIC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>Activo</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>Inactivo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Gestor_de_produccion__c.field-meta.xml
<CustomField>
    <fullName>Gestor_de_produccion__c</fullName>
    <label>Gestor de produccion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Organizacion__c.field-meta.xml
<CustomField>
    <fullName>Organizacion__c</fullName>
    <label>Organización</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Organizacion_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Organizacion_Comercial__c</fullName>
    <label>Organización Comercial</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <label>Producto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Sector_lookup__c.field-meta.xml
<CustomField>
    <fullName>Sector_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sector</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Parametrica_2__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Sector</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Parametrica_2__c</referenceTo>
    <relationshipLabel>Parametricas Ibermática</relationshipLabel>
    <relationshipName>Sector_lookup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/SIC__c.field-meta.xml
<CustomField>
    <fullName>SIC__c</fullName>
    <label>SIC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Solucion__c.field-meta.xml
<CustomField>
    <fullName>Solucion__c</fullName>
    <label>Solucion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Subsector__c.field-meta.xml
<CustomField>
    <fullName>Subsector__c</fullName>
    <label>Subsector</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/recordTypes/Area_Conocimiento_Tecnologico.recordType-meta.xml
<RecordType>
    <fullName>Area_Conocimiento_Tecnologico</fullName>
    <active>true</active>
    <label>Area Conocimiento Tecnológico</label>
</RecordType>

force-app/main/default/objects/Parametrica_2__c/recordTypes/CCI.recordType-meta.xml
<RecordType>
    <fullName>CCI</fullName>
    <active>true</active>
    <label>CCI</label>
</RecordType>

force-app/main/default/objects/Parametrica_2__c/recordTypes/Organizacion.recordType-meta.xml
<RecordType>
    <fullName>Organizacion</fullName>
    <active>true</active>
    <label>Organización</label>
</RecordType>

force-app/main/default/objects/Parametrica_2__c/recordTypes/Sector.recordType-meta.xml
<RecordType>
    <fullName>Sector</fullName>
    <active>true</active>
    <label>Sector</label>
</RecordType>

force-app/main/default/objects/Parametrica_2__c/recordTypes/Subsector.recordType-meta.xml
<RecordType>
    <fullName>Subsector</fullName>
    <active>true</active>
    <label>Subsector</label>
</RecordType>

force-app/main/default/classes/CRM_IB_MaestroController.cls
/**
* @author Ayesa
* @since 24-05-2023
* @desc Creacion APEX Controladora Maestros
* Controladora Maestros
*/
public class CRM_IB_MaestroController {
    @AuraEnabled
    public static String cargarOpp(Id idMaestro){
        String result;        
        List<Parametrica_2__c> lMaestros = [SELECT id,RecordType.DeveloperName,Codigo_Gestor_Produccion__c, Gestor_de_produccion__c, Centro_resp_Super__c, Organizacion__c,Codigo_CR__c, Tipo__c, Area__c,
                                            Solucion__c, Producto__c, SIC__c, Codigo_SIC__c, Sector__c, Subsector__c,  CCI__c, Sector_lookup__c, Organizacion_Comercial__c, Estado__c, 
                                            Area_Conocimiento_Tecnologica__c, Orden__c
                                          FROM Parametrica_2__c WHERE Id =:idMaestro LIMIT 1];
               
		if(!lMaestros.isEmpty()) {
			Parametrica_2__c maestro = lMaestros.get(0);
			
			System.debug('cargarOpp: ' + maestro.RecordType.developerName);
			
            String endpoint = 'callout:MULE_API_Maestros/'; 
            
			switch on maestro.RecordType.developerName {
			
				when 'Area_Conocimiento_Tecnologico' {					
					String request = '{' 
									 + '"idArea": "' + maestro.Id + '",' 
					                 + '"denominacion": "' + maestro.Area_Conocimiento_Tecnologica__c + '",' 
									 + '"estado": "' + maestro.Estado__c + '"'
									 + '}';
					
					result = CRM_IB_MulesoftAPI.callApiMule(endpoint + 'areas-con-tecnologico', request, 'POST', null, 'MaestroAreasConTecnologico');					
				}
				when 'Sector' {
					String request = '{' 
									 + '"idSector": "' + maestro.Id + '",'
					                 + '"denominacion": "' + maestro.Sector__c + '",'
									 + '"estado": "' + maestro.Estado__c + '"'
									 + '}';
									 
					result = CRM_IB_MulesoftAPI.callApiMule(endpoint + 'sectores', request, 'POST', null, 'MaestroSectores');                     
				}
				when 'Subsector' {
					String request = '{' +
									 + '"idSegmento": "' + maestro.Id + '",'
					                 + '"denominacion": "' + maestro.Subsector__c + '",'
									 + '"idSector": "' + maestro.Sector_lookup__c + '",'
									 + '"estado": "' + maestro.Estado__c + '"'
									 + '}';
									 
					result = CRM_IB_MulesoftAPI.callApiMule(endpoint + 'segmentos', request, 'POST', null, 'MaestroSegmentos');                                    
				}
				when 'Organizacion' {
					String request = '{' +
									 + '"idOrgComercial": "' + maestro.Id + '",'
					                 + '"denominacion": "' + maestro.Organizacion_Comercial__c + '",'
									 + '"estado": "' + maestro.Estado__c + '",'
									 + '"orden": ' + maestro.Orden__c
									 + '}';
					
					result = CRM_IB_MulesoftAPI.callApiMule(endpoint + 'org-comerciales', request, 'POST', null, 'MaestroOrgComerciales');                                    
				}
				when 'CCI' {
					String request = '{' +
									 + '"idNLO": "' + maestro.Id + '",'
					                 + '"denominacion": "' + maestro.CCI__c + '",'
									 + '"estado": "' + maestro.Estado__c + '",'
									 + '"orden": ' + maestro.Orden__c
									 + '}';
					
					result = CRM_IB_MulesoftAPI.callApiMule(endpoint + 'nlos', request, 'POST', null, 'MaestroCCIs');                                    
				}
                when else {
                    return 'El registro no es un Maestro SUPER.';
                }
			}
            
            return result;
			
		} else {
			return 'Registro de maestro no encontrado';
		}
    }
    
    @AuraEnabled
    public static String actualizarOpp(Id idMaestro){
        String result;        
        List<Parametrica_2__c> lMaestros = [SELECT id,RecordType.DeveloperName,Codigo_Gestor_Produccion__c, Gestor_de_produccion__c, Centro_resp_Super__c, Organizacion__c,Codigo_CR__c, Tipo__c, Area__c,
                                            Solucion__c, Producto__c, SIC__c, Codigo_SIC__c, Sector__c, Subsector__c,  CCI__c, Sector_lookup__c, Organizacion_Comercial__c, Estado__c, 
                                            Area_Conocimiento_Tecnologica__c, Orden__c
                                            FROM Parametrica_2__c WHERE Id =:idMaestro LIMIT 1];
        
		if(!lMaestros.isEmpty()) {
			Parametrica_2__c maestro = lMaestros.get(0);
			
			System.debug('actualizarOpp: ' + maestro.RecordType.developerName);

        	String endpoint = 'callout:MULE_API_Maestros/'; 
           
			switch on maestro.RecordType.developerName {
			
				when 'Area_Conocimiento_Tecnologico' {					
					String request = '{' 
					                 + '"denominacion": "' + maestro.Area_Conocimiento_Tecnologica__c + '",' 
									 + '"estado": "' + maestro.Estado__c + '"'
									 + '}';
					
					result = CRM_IB_MulesoftAPI.callApiMule(endpoint + 'areas-con-tecnologico', request, 'PUT', maestro.Id, 'MaestroAreasConTecnologico');					
				}
				when 'Sector' {
					String request = '{' 
					                 + '"denominacion": "' + maestro.Sector__c + '",'
									 + '"estado": "' + maestro.Estado__c + '"'
									 + '}';
									 
					result = CRM_IB_MulesoftAPI.callApiMule(endpoint + 'sectores', request, 'PUT', maestro.Id, 'MaestroSectores');                     
				}
				when 'Subsector' {
					String request = '{' +
					                 + '"denominacion": "' + maestro.Subsector__c + '",'
									 + '"idSector": "' + maestro.Sector_lookup__c + '",'
									 + '"estado": "' + maestro.Estado__c + '"'
									 + '}';
									 
					result = CRM_IB_MulesoftAPI.callApiMule(endpoint + 'segmentos', request, 'PUT', maestro.Id, 'MaestroSegmentos');                                    
				}
				when 'Organizacion' {
					String request = '{' +
					                 + '"denominacion": "' + maestro.Organizacion_Comercial__c + '",'
									 + '"estado": "' + maestro.Estado__c + '",'
									 + '"orden": ' + maestro.Orden__c
									 + '}';
					
					result = CRM_IB_MulesoftAPI.callApiMule(endpoint + 'org-comerciales', request, 'PUT', maestro.Id, 'MaestroOrgComerciales');                                    
				}
				when 'CCI' {
					String request = '{' +
					                 + '"denominacion": "' + maestro.CCI__c + '",'
									 + '"estado": "' + maestro.Estado__c + '",'
									 + '"orden": ' + maestro.Orden__c
									 + '}';
					
					result = CRM_IB_MulesoftAPI.callApiMule(endpoint + 'nlos', request, 'PUT', maestro.Id, 'MaestroCCIs');                                    
				}
                when else {
                    return 'El registro no es un Maestro SUPER.';
                }
			}
            
            return result;
			
		} else {
			return 'Registro de maestro no encontrado';
		}
    }
    
    @AuraEnabled
    public static String eliminarOpp(Id idMaestro){
        String result;        
        List<Parametrica_2__c> lMaestros = [SELECT id,RecordType.DeveloperName FROM Parametrica_2__c WHERE Id =:idMaestro LIMIT 1];
        
		if(!lMaestros.isEmpty()) {
			Parametrica_2__c maestro = lMaestros.get(0);
			
			System.debug('eliminarOpp: ' + maestro.RecordType.developerName);
			
        	String endpoint = 'callout:MULE_API_Maestros/'; 

			switch on maestro.RecordType.developerName {
			
				when 'Area_Conocimiento_Tecnologico' {					
					result = CRM_IB_MulesoftAPI.callApiMule(endpoint + 'areas-con-tecnologico', null, 'DELETE', maestro.Id, 'MaestroAreasConTecnologico');					
				}
				when 'Sector' {
					result = CRM_IB_MulesoftAPI.callApiMule(endpoint + 'sectores', null, 'DELETE', maestro.Id, 'MaestroSectores');                     
				}
				when 'Subsector' {
					result = CRM_IB_MulesoftAPI.callApiMule(endpoint + 'segmentos', null, 'DELETE', maestro.Id, 'MaestroSegmentos');                                    
				}
				when 'Organizacion' {
					result = CRM_IB_MulesoftAPI.callApiMule(endpoint + 'org-comerciales', null, 'DELETE', maestro.Id, 'MaestroOrgComerciales');                                    
				}
				when 'CCI' {
					result = CRM_IB_MulesoftAPI.callApiMule(endpoint + 'nlos', null, 'DELETE', maestro.Id, 'MaestroCCIs');                                    
				}
                when else {
                    return 'El registro no es un Maestro SUPER.';
                }
			}
            
            return result;
			
		} else {
			return 'Registro de maestro no encontrado';
		}
    }
}