force-app/main/default/objects/Opportunity/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ATC</fullName>
                <default>true</default>
                <label>ATC</label>
            </value>
            <value>
                <fullName>ATD</fullName>
            </value>
            <value>
                <fullName>INGENIERIA_CIVIL</fullName>
                <label>INGENIERÍA CIVIL Y ARQUITECTURA</label>
            </value>
            <value>
                <fullName>INGENIERIA_INDUSTRIAL</fullName>
                <label>INGENIERÍA INDUSTRIAL</label>
            </value>
            <value>
                <fullName>M2C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Clase_de_oferta__c.field-meta.xml
<CustomField>
    <fullName>Clase_de_oferta__c</fullName>
    <label>Clase de oferta</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>-</fullName>
                <isActive>false</isActive>
                <label>-</label>
            </value>
            <value>
                <fullName>Acuerdo Marco</fullName>
                <isActive>false</isActive>
                <label>Acuerdo Marco / SDA</label>
            </value>
            <value>
                <fullName>Acuerdo Marco Privado</fullName>
                <label>Acuerdo Marco / SDA Privado</label>
            </value>
            <value>
                <fullName>Acuerdo Marco Público</fullName>
                <label>Acuerdo Marco / SDA Público</label>
            </value>
            <value>
                <fullName>Ampliación de Contrato</fullName>
                <isActive>false</isActive>
                <label>Ampliación de Contrato</label>
            </value>
            <value>
                <fullName>Información Previa</fullName>
                <isActive>false</isActive>
                <label>Información Previa</label>
            </value>
            <value>
                <fullName>Invitación Acuerdo Marco</fullName>
                <isActive>false</isActive>
                <label>Invitación Acuerdo Marco / SDA</label>
            </value>
            <value>
                <fullName>Invitación Pública</fullName>
                <isActive>false</isActive>
                <label>Invitación Pública</label>
            </value>
            <value>
                <fullName>Licitación Pública</fullName>
                <isActive>false</isActive>
                <label>Licitación Pública</label>
            </value>
            <value>
                <fullName>Oferta interco</fullName>
                <isActive>false</isActive>
                <label>Oferta interco</label>
            </value>
            <value>
                <fullName>Petición EOI / Pre-Calificación</fullName>
                <isActive>false</isActive>
                <label>Petición EOI / Pre-Calificación</label>
            </value>
            <value>
                <fullName>Privada</fullName>
            </value>
            <value>
                <fullName>Pública</fullName>
            </value>
            <value>
                <fullName>Registro Proveedores</fullName>
                <isActive>false</isActive>
                <label>Registro Proveedores</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Existencia_de_Incoherencias__c.field-meta.xml
<CustomField>
    <fullName>Existencia_de_Incoherencias__c</fullName>
    <description>Validación de incoherencias en los datos de la oportunidad</description>
    <formula>OR(
  AND(
    NOT ( ISPICKVAL(StageName, &apos;Cerrada&apos;) ),
    Fecha_limite_de_presentacion__c  &lt;  TODAY() 
  ),
  AND(
    NOT ( ISPICKVAL(StageName, &apos;Cerrada&apos;) ),
    Fecha_estimada_de_cierre__c  &lt;  TODAY() 
  ),
  AND(
    NOT ( ISPICKVAL(StageName, &apos;Cualificación&apos;) ),
    NOT ( ISPICKVAL(Tipo_de_Oportunidad__c, &apos;Licitación&apos;) )
  ),
  Fecha_estimada_de_cierre__c &lt;= Fecha_limite_de_presentacion__c
)</formula>
    <inlineHelpText>Validation of inconsistencies in the data of the opportunity</inlineHelpText>
    <label>Existencia de Incoherencias</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Fecha_estimada_de_cierre__c.field-meta.xml
<CustomField>
    <fullName>Fecha_estimada_de_cierre__c</fullName>
    <description>Fecha estimada de cierre de la oportunidad</description>
    <inlineHelpText>Fecha estimada de cierre de la oportunidad, indique la fecha REAL si ya se ha cerrado</inlineHelpText>
    <label>Fecha de cierre</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Fecha_limite_de_presentacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_limite_de_presentacion__c</fullName>
    <description>Fecha de presentación de la oferta</description>
    <inlineHelpText>Fecha límite de presentación de la oferta, fecha REAL en caso de haberla presentado</inlineHelpText>
    <label>Fecha presentación</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Importe_Licitacion__c.field-meta.xml
<CustomField>
    <fullName>Importe_Licitacion__c</fullName>
    <inlineHelpText>En el campo Importe total de Licitación (sin IVA) en se indicará todo el importe conocido de la licitación (es conocido en el momento de abrir la oportunidad)</inlineHelpText>
    <label>Importe Total (sin IVA) €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Margen_estimado_incluye_recargos__c.field-meta.xml
<CustomField>
    <fullName>Margen_estimado_incluye_recargos__c</fullName>
    <label>% Margen estimado (incluye recargos)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sociedad_Ayesa__c.field-meta.xml
<CustomField>
    <fullName>Sociedad_Ayesa__c</fullName>
    <description>Sociedad del grupo Ayesa que presenta la oferta</description>
    <inlineHelpText>Sociedad del grupo Ayesa que presenta la oferta</inlineHelpText>
    <label>Sociedad</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0002</fullName>
                <label>0002 - AYESA ENGINEERING S.A</label>
            </value>
            <value>
                <fullName>0003</fullName>
                <label>0003 - AYESA ING. Y ARQU., S.A.</label>
            </value>
            <value>
                <fullName>0004</fullName>
                <label>0004 - ALIA GESTION S.L.</label>
            </value>
            <value>
                <fullName>0005</fullName>
                <label>0005 - AYNOVA, S.A.U.</label>
            </value>
            <value>
                <fullName>0007</fullName>
                <label>0007 - ACT SISTEMAS, S.L.U.</label>
            </value>
            <value>
                <fullName>0012</fullName>
                <label>0012 - AYESA MDE, S.A.</label>
            </value>
            <value>
                <fullName>0018</fullName>
                <label>0018 - AYESA AIR CONTROL S.L.</label>
            </value>
            <value>
                <fullName>0021</fullName>
                <label>0021 - AYESA MEXICO,S.A. de C.V.</label>
            </value>
            <value>
                <fullName>0023</fullName>
                <label>0023 - AYESA SUCURSAL POLONIA</label>
            </value>
            <value>
                <fullName>0024</fullName>
                <label>0024 - AYESA POLSKA SP. Z O.O.</label>
            </value>
            <value>
                <fullName>0025</fullName>
                <label>0025 - AYESA MAROC, S.A.R.L</label>
            </value>
            <value>
                <fullName>0027</fullName>
                <label>0027 - AYESA IMPLEMEN. TECN. S.A</label>
            </value>
            <value>
                <fullName>0030</fullName>
                <label>0030 - AYESA ALGERIE S.A.R.L.</label>
            </value>
            <value>
                <fullName>0034</fullName>
                <label>0034 - AYESA SERVICIOS S RL DECV</label>
            </value>
            <value>
                <fullName>0035</fullName>
                <label>0035 - ALIA WORLDWIDE, S.L.</label>
            </value>
            <value>
                <fullName>0036</fullName>
                <label>0036 - AYESA BRANCH OFFICE</label>
            </value>
            <value>
                <fullName>0040</fullName>
                <label>0040 - AYESA ENGINYERIA SERVEIS</label>
            </value>
            <value>
                <fullName>0045</fullName>
                <label>0045 - ATECH ADVAN. SOL.</label>
            </value>
            <value>
                <fullName>0047</fullName>
                <label>0047 - ATECH BPO, S.L.</label>
            </value>
            <value>
                <fullName>0048</fullName>
                <label>0048 - UNITEC</label>
            </value>
            <value>
                <fullName>0049</fullName>
                <label>0049 - INSOTECH INTERNATIONAL</label>
            </value>
            <value>
                <fullName>0050</fullName>
                <label>0050 - AYESA PERÚ</label>
            </value>
            <value>
                <fullName>0053</fullName>
                <label>0053 - AYESA INDIA PRIVATE LIMIT</label>
            </value>
            <value>
                <fullName>0054</fullName>
                <label>0054 - AYESA COLOMBIA SAS</label>
            </value>
            <value>
                <fullName>0056</fullName>
                <label>0056 - AYESA PANAMÁ</label>
            </value>
            <value>
                <fullName>0057</fullName>
                <label>0057 - AAT PANAMÁ RUC</label>
            </value>
            <value>
                <fullName>0058</fullName>
                <label>0058 - AYESA PANAMÁ RUC</label>
            </value>
            <value>
                <fullName>0059</fullName>
                <label>0059 - AYESA COLOMBIA SUCURSAL</label>
            </value>
            <value>
                <fullName>0060</fullName>
                <label>0060 - AAT ECUADOR</label>
            </value>
            <value>
                <fullName>0061</fullName>
                <label>0061 - AYESA ECUADOR</label>
            </value>
            <value>
                <fullName>0170</fullName>
                <label>0170 - AYESA IBERMÁTICA, S.A.U.</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tipo_Participacion_Ayesa__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Participacion_Ayesa__c</fullName>
    <inlineHelpText>Type of Ayesa Company participation as Main contractor, subconsultant for a Main/Prime Consultant or Temporary Join Venture (TJV)</inlineHelpText>
    <label>Tipo de Participación</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contratista Principal</fullName>
            </value>
            <value>
                <fullName>Subcontratista</fullName>
            </value>
            <value>
                <fullName>UTE</fullName>
            </value>
            <value>
                <fullName>UTE 100% Empresas Grupo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Ayesa.recordType-meta.xml
<RecordType>
    <fullName>Ayesa</fullName>
    <active>true</active>
    <businessProcess>Ayesa</businessProcess>
    <label>Ayesa</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Engineering.recordType-meta.xml
<RecordType>
    <fullName>Engineering</fullName>
    <active>true</active>
    <businessProcess>Engineering</businessProcess>
    <label>Engineering</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Ingenier_a.recordType-meta.xml
<RecordType>
    <fullName>Ingenier_a</fullName>
    <active>true</active>
    <businessProcess>Ingeniería</businessProcess>
    <label>Ingeniería</label>
</RecordType>

force-app/main/default/classes/CRM_Notific_Op_Incoher_Schedule_Test.cls
@isTest(SeeAllData=false)
public class CRM_Notific_Op_Incoher_Schedule_Test {

    @isTest static void batchClassTestEMail() {
        
        Test.startTest();
                
        If(Test.isRunningTest()){
        	ID jobID = Database.executeBatch(new CRM_Notific_Op_Incoherentes(), 10);
             System.abortJob(jobID);
        }else{
      		Database.executeBatch(new CRM_Notific_Op_Incoherentes());
		}
        
        Test.stopTest();
        
    }
    
    @isTest static void scheduleClassTest() {
        
        Test.startTest();
       	
        System.schedule('CRM Notificación de Oportunidades Incoherentes TEST', '0 0 8 * * ?', new CRM_Notific_Op_Incoherentes_Schedule());
    	System.debug('CRM Notificación de Oportunidades Incoherentes programada todos los días a las 8:00 AM');
        
        Test.stopTest();
        
    }
    
    @isTest static void scheduleClassTest2() {
        
        List<Opportunity> ownerByOppIncoherente = [SELECT Id, Name, OwnerId, Owner.name, Owner.email FROM Opportunity WHERE Existencia_de_Incoherencias__c = true order by OwnerId LIMIT 1];
        
        Test.startTest();
       	
        new CRM_Notific_Op_Incoherentes().execute(null, ownerByOppIncoherente);
        
        Test.stopTest();
        
    }
    
    @isTest static void getopptysTest() {
        
        Id userId = [Select Id from User limit 1].Id;
        
        Test.startTest();
       	
        CRM_Notific_Op_Incoherentes_Controller notif = new CRM_Notific_Op_Incoherentes_Controller();
        notif.ownerId = userId;
        notif.getopptys();
        
        Test.stopTest();
        
    }
    
    @testSetup static void cargaDatos() {
        
        User user1 = new User(
            ProfileId = [Select Id from Profile limit 1].Id,
            LastName = 'last',
            Email = 'j.moreno@ayesa.com',
            Username = 'puser000@amamama.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US'
        );
        insert user1;

        Opportunity oppIncoherente = TestDataFactory.createOpportunity('Cualificación', 'Engineering Design & Architecture','Ingenier_a');
        oppIncoherente.Nombre_Corto__c = 'Prueba notificacion incoherencia';
        oppIncoherente.Name = 'Prueba';
        oppIncoherente.Pais__c = 'ES';
        oppIncoherente.Probability = 10;
        oppIncoherente.Area__c = 'ATC';
        oppIncoherente.Importe_Licitacion__c = 1000000;
        oppIncoherente.Margen_estimado_incluye_recargos__c = 0.1;
        oppIncoherente.Fecha_limite_de_presentacion__c = Date.valueOf('2021-02-02');
        oppIncoherente.Fecha_estimada_de_cierre__c = Date.valueOf('2021-01-31');
        oppIncoherente.Plazo_de_ejecuci_n_meses__c = 6;
        oppIncoherente.Tipo_Participacion_Ayesa__c = 'UTE';
        oppIncoherente.Participacion_Ayesa__c = 100;
        oppIncoherente.Sociedad_Ayesa__c = '0170';
        oppIncoherente.Clase_de_oferta__c = 'Pública';
        update oppIncoherente;
                
    }
}