force-app/main/default/objects/Opportunity/fields/Cuenta_Principal__c.field-meta.xml
<CustomField>
    <fullName>Cuenta_Principal__c</fullName>
    <formula>IF( ISBLANK(  Cliente__r.ParentId  ),   Cliente__r.Name  ,  Cliente__r.Parent.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cuenta Principal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Existencia_de_Incoherencias__c.field-meta.xml
<CustomField>
    <fullName>Existencia_de_Incoherencias__c</fullName>
    <description>Validación de incoherencias en los datos de la oportunidad</description>
    <formula>OR(
  AND(
    NOT ( ISPICKVAL(StageName, &apos;Cerrada&apos;) ),
    Fecha_limite_de_presentacion__c  &lt;  TODAY() 
  ),
  AND(
    NOT ( ISPICKVAL(StageName, &apos;Cerrada&apos;) ),
    Fecha_estimada_de_cierre__c  &lt;  TODAY() 
  ),
  AND(
    NOT ( ISPICKVAL(StageName, &apos;Cualificación&apos;) ),
    NOT ( ISPICKVAL(Tipo_de_Oportunidad__c, &apos;Licitación&apos;) )
  ),
  Fecha_estimada_de_cierre__c &lt;= Fecha_limite_de_presentacion__c
)</formula>
    <inlineHelpText>Validation of inconsistencies in the data of the opportunity</inlineHelpText>
    <label>Existencia de Incoherencias</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CRM_Notific_Op_Incoherentes_Controller.cls
public class CRM_Notific_Op_Incoherentes_Controller {
	public Id ownerId {get;set;}
    
    public Map<String, Object> getopptys(){
        
        List<Opportunity> opptys;
        opptys = [SELECT Id, Name, Cuenta_Principal__c, OwnerId, Owner.name, Owner.email FROM Opportunity WHERE Existencia_de_Incoherencias__c = true and (StageName != 'Cerrada' or estado_de_cierre__c = 'Contratada') and OwnerId =: ownerId];
        
        String baseUrl = URL.getOrgDomainUrl().toExternalForm();
            
        Map<String, Object> params = new Map<String, Object>();
        
        params.put('baseUrl', baseUrl);
        params.put('opptys', opptys);
        
        //return opptys;
        return params;
    }
}