force-app/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <description>Entidad creada para gestión y actualización de los estados de los contratos.</description>
    <label>Contrato</label>
    <nameField>
        <label>Denominación SAP</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato__c/fields/Asistencia_juridica__c.field-meta.xml
<CustomField>
    <fullName>Asistencia_juridica__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Asistencia jurídica</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Causa_resolucion__c.field-meta.xml
<CustomField>
    <fullName>Causa_resolucion__c</fullName>
    <label>Causa resolución</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CRES1</fullName>
            </value>
            <value>
                <fullName>CRES2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Causa_retraso__c.field-meta.xml
<CustomField>
    <fullName>Causa_retraso__c</fullName>
    <label>Causa retraso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CR1</fullName>
            </value>
            <value>
                <fullName>CR2</fullName>
            </value>
            <value>
                <fullName>CR3</fullName>
                <isActive>false</isActive>
                <label>CR3</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Causa_suspension__c.field-meta.xml
<CustomField>
    <fullName>Causa_suspension__c</fullName>
    <label>Causa suspensión</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CSUS1</fullName>
            </value>
            <value>
                <fullName>CSUS2</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
                <isActive>false</isActive>
                <label>NO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/CeBe__c.field-meta.xml
<CustomField>
    <fullName>CeBe__c</fullName>
    <description>Traducción realizada desde Contrato__c-es.objectTranslation, realizar desde visual studio.</description>
    <label>Negocio (CeBe)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A1D00P</fullName>
            </value>
            <value>
                <fullName>A1D01P</fullName>
            </value>
            <value>
                <fullName>A1D02P</fullName>
            </value>
            <value>
                <fullName>A1D03P</fullName>
            </value>
            <value>
                <fullName>A1D04P</fullName>
            </value>
            <value>
                <fullName>A1D05P</fullName>
            </value>
            <value>
                <fullName>A1D06P</fullName>
            </value>
            <value>
                <fullName>A1D07P</fullName>
            </value>
            <value>
                <fullName>A1D08P</fullName>
            </value>
            <value>
                <fullName>A2D00P</fullName>
            </value>
            <value>
                <fullName>A2D01P</fullName>
            </value>
            <value>
                <fullName>A2D02P</fullName>
            </value>
            <value>
                <fullName>A2D03P</fullName>
            </value>
            <value>
                <fullName>A2D04P</fullName>
            </value>
            <value>
                <fullName>A2D05P</fullName>
            </value>
            <value>
                <fullName>A2D06P</fullName>
            </value>
            <value>
                <fullName>A2D07P</fullName>
            </value>
            <value>
                <fullName>A2D08P</fullName>
            </value>
            <value>
                <fullName>A2D09P</fullName>
            </value>
            <value>
                <fullName>A2D10P</fullName>
            </value>
            <value>
                <fullName>A2D11P</fullName>
            </value>
            <value>
                <fullName>A3D00P</fullName>
            </value>
            <value>
                <fullName>A3D01P</fullName>
            </value>
            <value>
                <fullName>A3D02P</fullName>
            </value>
            <value>
                <fullName>A3D04P</fullName>
            </value>
            <value>
                <fullName>A3D05P</fullName>
            </value>
            <value>
                <fullName>A3D06P</fullName>
            </value>
            <value>
                <fullName>A3D07P</fullName>
            </value>
            <value>
                <fullName>A3D08P</fullName>
            </value>
            <value>
                <fullName>A5D00P</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Codigo_AJI__c.field-meta.xml
<CustomField>
    <fullName>Codigo_AJI__c</fullName>
    <label>Código AJI</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Codigo_SAP__c.field-meta.xml
<CustomField>
    <fullName>Codigo_SAP__c</fullName>
    <externalId>true</externalId>
    <label>Código SAP</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Costes_aceptados_suspension_local__c.field-meta.xml
<CustomField>
    <fullName>Costes_aceptados_suspension_local__c</fullName>
    <label>Costes aceptados suspensión (local)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Documentando_incidencias__c.field-meta.xml
<CustomField>
    <fullName>Documentando_incidencias__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Documentando incidencias</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ENMA</fullName>
            </value>
            <value>
                <fullName>RECEP</fullName>
            </value>
            <value>
                <fullName>SINC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Fecha_control_correos__c.field-meta.xml
<CustomField>
    <fullName>Fecha_control_correos__c</fullName>
    <label>Fecha control correos</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Moneda__c.field-meta.xml
<CustomField>
    <fullName>Moneda__c</fullName>
    <label>Moneda</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>PAB</fullName>
                <label>Balboa panameño</label>
            </value>
            <value>
                <fullName>BOB</fullName>
                <label>Boliviano</label>
            </value>
            <value>
                <fullName>NOK</fullName>
                <label>Corona noruega</label>
            </value>
            <value>
                <fullName>DZD</fullName>
                <label>Dinar argelino</label>
            </value>
            <value>
                <fullName>MAD</fullName>
                <label>Dirham marroquí</label>
            </value>
            <value>
                <fullName>USD</fullName>
                <label>Dólar</label>
            </value>
            <value>
                <fullName>VND</fullName>
                <label>Dong vietnamita</label>
            </value>
            <value>
                <fullName>EUR</fullName>
                <label>Euro europeo</label>
            </value>
            <value>
                <fullName>HUF</fullName>
                <label>Forint húngaro</label>
            </value>
            <value>
                <fullName>GNF</fullName>
                <label>Franco guineano</label>
            </value>
            <value>
                <fullName>UAH</fullName>
                <label>Griwna ucraniano</label>
            </value>
            <value>
                <fullName>GBP</fullName>
                <label>Libra esterlina</label>
            </value>
            <value>
                <fullName>PEN</fullName>
                <label>Nuevo sol</label>
            </value>
            <value>
                <fullName>CLP</fullName>
                <label>Peso chileno</label>
            </value>
            <value>
                <fullName>COP</fullName>
                <label>Peso colombiano</label>
            </value>
            <value>
                <fullName>DOP</fullName>
                <label>Peso dominicano</label>
            </value>
            <value>
                <fullName>PHP</fullName>
                <label>Peso filipino</label>
            </value>
            <value>
                <fullName>MXN</fullName>
                <label>Peso mexicano</label>
            </value>
            <value>
                <fullName>ZAR</fullName>
                <label>Rand sudafricano</label>
            </value>
            <value>
                <fullName>BRL</fullName>
                <label>Real brasileño</label>
            </value>
            <value>
                <fullName>OMR</fullName>
                <label>Rial omaní</label>
            </value>
            <value>
                <fullName>SAR</fullName>
                <label>Riyal saudí</label>
            </value>
            <value>
                <fullName>RUB</fullName>
                <label>Rublo ruso</label>
            </value>
            <value>
                <fullName>INR</fullName>
                <label>Rupia india</label>
            </value>
            <value>
                <fullName>BDT</fullName>
                <label>Taka bangladeshí</label>
            </value>
            <value>
                <fullName>CNY</fullName>
                <label>Yuan chino</label>
            </value>
            <value>
                <fullName>PLN</fullName>
                <label>Zloty polaco</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <label>País</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AD</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AG</fullName>
            </value>
            <value>
                <fullName>AI</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AN</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AQ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BJ</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BN</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>BS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Sub_area__c.field-meta.xml
<CustomField>
    <fullName>Sub_area__c</fullName>
    <label>Sub-área</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A1</fullName>
            </value>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>A3</fullName>
            </value>
            <value>
                <fullName>A5</fullName>
            </value>
            <value>
                <fullName>A6</fullName>
            </value>
            <value>
                <fullName>A8</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parametros_gestion_contratos__c/Parametros_gestion_contratos__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Parametros gestión contratos</label>
</CustomObject>

force-app/main/default/objects/Parametros_gestion_contratos__c/fields/Dias_sin_actualizar__c.field-meta.xml
<CustomField>
    <fullName>Dias_sin_actualizar__c</fullName>
    <label>Días sin actualizar</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CRM_Recordatorio_Actualizacion_Contrato.cls
global class CRM_Recordatorio_Actualizacion_Contrato implements Database.Batchable<sObject>{
    
    
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        Parametros_gestion_contratos__c param = Parametros_gestion_contratos__c.getOrgDefaults(); //Número de días que se lleva sin actualizar el contrato
        Integer mydays = (integer)param.Dias_sin_actualizar__c;
        string days = string.valueof(mydays);
       // days = '20';
        system.debug('dias: ' + days);
        string estado = 'RECEP'; //Estado que hay que ignorar en los contartos
       // string userName= 'Usuario Pruebas RP';
        
        string query='SELECT id,Sub_area__c, CeBe__c, Codigo_SAP__c, Name, Pais__c, Estado__c,Moneda__c,LastModifiedDate,Codigo_AJI__c,Asistencia_juridica__c,Fecha_control_correos__c,Causa_resolucion__c,Causa_suspension__c,Comentarios__c,';
        query= query + 'Documentando_incidencias__c, Causa_retraso__c, Negociacion_aceptada__c,Costes_aceptados_suspension_local__c,Costes_aceptados_resolucion_local__c,OwnerId, Owner.Email,Owner.Name, Prevision_situacion_contrato__c ';
        query = query + 'FROM Contrato__c WHERE Estado__c != \'' +estado+ '\' and Fecha_control_correos__c != LAST_N_DAYS:'+days ;
        //query = query + 'FROM Contrato__c WHERE Estado__c != \'' +estado+ '\' and LastModifiedDate != LAST_N_DAYS:'+days ;
       // query = query + 'FROM Contrato__c WHERE Estado__c != \'' +estado+ '\' and Owner.name =\''+userName+'\' and LastModifiedDate != LAST_N_DAYS:'+days+' order by lastmodifieddate asc' ;
       
        
        
        return Database.getQueryLocator(query);
        
    }
    
    global void execute(Database.BatchableContext BC, List<Contrato__c> contratos){
        system.debug('Tamaño de lista de contratos RECORDATORIO:  ' + contratos.size());
               
       //Se crea lista de emails
  		List<Messaging.SingleEmailMessage> theEmails = new List<Messaging.SingleEmailMessage>(); 
        
        //Guardo los Id's de los usuarios (idioma 1.1)
        Set <Id> lista_Ids_RPS = new Set<Id>();
        for (Contrato__c con : contratos){
            lista_Ids_RPS.add(con.OwnerId);
        }
        
        //Hago lista de usuarios con esos IDS (idioma 1.2)
        
        List<User> lista_Usuarios = [SELECT id,LanguageLocaleKey FROM User where id IN :lista_Ids_RPS ];
        
        system.debug('Tamaño de lista de RPS:  '+ lista_Ids_RPS.size());
        system.debug('Tamaño de lista de Usuarios consultados:  '+ lista_Usuarios.size());
        
        //Mapa identificador contrato --> Idioma del email(idioma 1.3)
        Map<Id, User> mapa_Usuarios = new Map<Id, User>(lista_Usuarios);
         Map<Id, String> mapa_Contrato_Idioma = new Map<Id, String>();
        
        for (Contrato__c con : contratos){
            mapa_Contrato_Idioma.put(con.Id, mapa_Usuarios.get(con.OwnerId).LanguageLocaleKey); //Ya tengo emparejado cada identificador de contrato con el idioma del email
        }
        
       
        
        //Se crea el cuerpo del email por cada contrato
        for(Contrato__c con : contratos) {
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            string idioma=mapa_Contrato_Idioma.get(con.Id);
            system.debug('Idioma del email: '+idioma);
            string body;
            string subject;
            switch on idioma {
                when 'es' {
                   
            subject = Label.GC_Email_Recordatorio_Asunto;
 
            body = Label.GC_Email_Recordatorio00 + ' ' +  con.Owner.Name + ',\n\n';
            
            body +=  Label.GC_Email_Recordatorio01 + con.Name + Label.GC_Email_Recordatorio02 + '\n\n';
            
            body += Label.GC_Email_Recordatorio03 + '\n\n';
                }
                when 'en_US' {
                   
            subject = Label.GC_Email_Recordatorio_Asunto_Eng;
       
            body = Label.GC_Email_Recordatorio00_Eng + ' ' +  con.Owner.Name + ',\n\n';
            
            body +=  Label.GC_Email_Recordatorio01_Eng + con.Name + Label.GC_Email_Recordatorio02_Eng + '\n\n';
            
            body += Label.GC_Email_Recordatorio03_Eng + '\n\n';
                }
            }

  
            body += system.URL.getOrgDomainUrl().toExternalForm() +'/'+con.Id ;
            //system.debug(con.Owner.LanguageLocaleKey);
            email.setToAddresses(new String[] {con.Owner.Email});
            email.setSaveAsActivity(false);
            email.setTreatTargetObjectAsRecipient(false);
            email.setSubject( subject );
            // email.setTargetObjectId(con.Owner.id);
            // email.setTemplateId(emailTemplate.Id);
            email.setPlainTextBody( body );
            // email.setWhatId(con.Id);
            theEmails.add(email);
        }
		
        //Para evitar el limite de 10 envios de SingleEmail, se recorre la lista y se añaden todos sus elementos a una lista de EMAILS
        List<Messaging.Email> allMails = new List<Messaging.Email>();
        for( Integer j = 0; j < theEmails.size(); j++ ){
            allMails.add(theEmails.get(j));
        }
        List<Messaging.SendEmailResult> results = new List<Messaging.SendEmailResult>();
        //Se mandan todos los emails
        if(!Test.isRunningTest()){
			results = Messaging.sendEmail( allMails );
        }

        //Se recogen los errores si los hubiera
       List<Messaging.SendEmailError> errors = new List<Messaging.SendEmailError>();
        system.debug('results is :: '+results);
        String emailErrorReport;
        
        for( Messaging.SendEmailResult currentResult : results ) {
            errors = currentResult.getErrors();
            if( null != errors ) {
                for( Messaging.SendEmailError currentError : errors ) {
                    emailErrorReport = emailErrorReport + '(' + currentError.getStatusCode() + ') ' + currentError.getMessage() + 'r' ;
                    system.debug(emailErrorReport);
                }
            }
        }
      

                            
                        }
    
    global void finish(Database.BatchableContext BC){
        
    }
}