force-app/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <description>Entidad creada para gestión y actualización de los estados de los contratos.</description>
    <label>Contrato</label>
    <nameField>
        <label>Denominación SAP</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato__c/fields/Codigo_SAP__c.field-meta.xml
<CustomField>
    <fullName>Codigo_SAP__c</fullName>
    <externalId>true</externalId>
    <label>Código SAP</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo que relaciona la entidad Contrato (Gestión contratos) con la entidad Proyecto (AContract)</description>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Contratos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Historico_estado_contrato__c/Historico_estado_contrato__c.object-meta.xml
<CustomObject>
    <label>Histórico estado contrato</label>
    <nameField>
        <label>Histórico estado contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Histórico estado contratos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Historico_estado_contrato__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contrato__c</referenceTo>
    <relationshipLabel>Histórico estado contrato</relationshipLabel>
    <relationshipName>Historico_estado_contrato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Historico_estado_contrato__c/fields/Lets_Talk__c.field-meta.xml
<CustomField>
    <fullName>Lets_Talk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lets Talk</label>
    <referenceTo>Lets_Talk__c</referenceTo>
    <relationshipLabel>Histórico Lets Talk</relationshipLabel>
    <relationshipName>Historico_estado_contratos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Historico_estado_contrato__c/fields/Lets_Talk_Asunto__c.field-meta.xml
<CustomField>
    <fullName>Lets_Talk_Asunto__c</fullName>
    <label>Lets Talk Asunto</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_estado_contrato__c/fields/Lets_Talk_CC__c.field-meta.xml
<CustomField>
    <fullName>Lets_Talk_CC__c</fullName>
    <label>Lets Talk CC</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_estado_contrato__c/fields/Lets_Talk_Cuerpo_Mensaje__c.field-meta.xml
<CustomField>
    <fullName>Lets_Talk_Cuerpo_Mensaje__c</fullName>
    <label>Lets Talk Mensaje</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Historico_estado_contrato__c/fields/Lets_Talk_Destinatarios__c.field-meta.xml
<CustomField>
    <fullName>Lets_Talk_Destinatarios__c</fullName>
    <label>Lets Talk Destinatarios</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_estado_contrato__c/fields/Lets_Talk_Fecha_envio_correo__c.field-meta.xml
<CustomField>
    <fullName>Lets_Talk_Fecha_envio_correo__c</fullName>
    <label>Lets Talk Fecha envio correo</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Historico_estado_contrato__c/fields/Lets_Talk_Fecha_respuesta_correo__c.field-meta.xml
<CustomField>
    <fullName>Lets_Talk_Fecha_respuesta_correo__c</fullName>
    <label>Lets Talk Fecha respuesta correo</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Historico_estado_contrato__c/fields/Lets_Talk_Respuesta_Asunto__c.field-meta.xml
<CustomField>
    <fullName>Lets_Talk_Respuesta_Asunto__c</fullName>
    <label>Lets Talk Respuesta Asunto</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_estado_contrato__c/fields/Lets_Talk_Respuesta_Mensaje__c.field-meta.xml
<CustomField>
    <fullName>Lets_Talk_Respuesta_Mensaje__c</fullName>
    <label>Lets Talk Respuesta Mensaje</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Historico_estado_proyecto__c/Historico_estado_proyecto__c.object-meta.xml
<CustomObject>
    <label>Historico estado proyecto</label>
    <nameField>
        <label>Nombre de Historico</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Historico estado proyecto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Historico_estado_proyecto__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código de Proyecto</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_estado_proyecto__c/fields/Lets_Talk__c.field-meta.xml
<CustomField>
    <fullName>Lets_Talk__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lets Talk</label>
    <referenceTo>Lets_Talk__c</referenceTo>
    <relationshipLabel>Historico lets talk proyecto</relationshipLabel>
    <relationshipName>Historico_estado_proyecto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Historico_estado_proyecto__c/fields/Lets_Talk_Asunto__c.field-meta.xml
<CustomField>
    <fullName>Lets_Talk_Asunto__c</fullName>
    <label>Lets Talk Asunto</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_estado_proyecto__c/fields/Lets_Talk_CC__c.field-meta.xml
<CustomField>
    <fullName>Lets_Talk_CC__c</fullName>
    <label>Lets Talk CC</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_estado_proyecto__c/fields/Lets_Talk_Cuerpo_Mensaje__c.field-meta.xml
<CustomField>
    <fullName>Lets_Talk_Cuerpo_Mensaje__c</fullName>
    <label>Lets Talk Mensaje</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Historico_estado_proyecto__c/fields/Lets_Talk_Destinatarios__c.field-meta.xml
<CustomField>
    <fullName>Lets_Talk_Destinatarios__c</fullName>
    <label>Lets Talk Destinatarios</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_estado_proyecto__c/fields/Lets_Talk_Fecha_envio_correo__c.field-meta.xml
<CustomField>
    <fullName>Lets_Talk_Fecha_envio_correo__c</fullName>
    <label>Lets Talk Fecha envio correo</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Historico_estado_proyecto__c/fields/Lets_Talk_Fecha_respuesta_correo__c.field-meta.xml
<CustomField>
    <fullName>Lets_Talk_Fecha_respuesta_correo__c</fullName>
    <label>Lets Talk Fecha respuesta correo</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Historico_estado_proyecto__c/fields/Lets_Talk_Respuesta_Asunto__c.field-meta.xml
<CustomField>
    <fullName>Lets_Talk_Respuesta_Asunto__c</fullName>
    <label>Lets Talk Respuesta Asunto</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_estado_proyecto__c/fields/Lets_Talk_Respuesta_Mensaje__c.field-meta.xml
<CustomField>
    <fullName>Lets_Talk_Respuesta_Mensaje__c</fullName>
    <label>Lets Talk Respuesta Mensaje</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Historico_estado_proyecto__c/fields/Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Histórico proyecto</relationshipLabel>
    <relationshipName>Historico_estado_proyecto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lets_Talk__c/Lets_Talk__c.object-meta.xml
<CustomObject>
    <label>Lets Talk</label>
    <nameField>
        <label>Nombre de Lets Talk</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lets Talk</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lets_Talk__c/fields/Asunto__c.field-meta.xml
<CustomField>
    <fullName>Asunto__c</fullName>
    <label>Asunto</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lets_Talk__c/fields/CC__c.field-meta.xml
<CustomField>
    <fullName>CC__c</fullName>
    <inlineHelpText>Separar email con punto y coma &apos;;&apos;</inlineHelpText>
    <label>CC</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lets_Talk__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contrato__c</referenceTo>
    <relationshipLabel>Lets Talk</relationshipLabel>
    <relationshipName>Lets_Talk</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lets_Talk__c/fields/Cuerpo_Mensaje__c.field-meta.xml
<CustomField>
    <fullName>Cuerpo_Mensaje__c</fullName>
    <label>Mensaje</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Lets_Talk__c/fields/Destinatarios__c.field-meta.xml
<CustomField>
    <fullName>Destinatarios__c</fullName>
    <inlineHelpText>Separar email con punto y coma &apos;;&apos;</inlineHelpText>
    <label>Destinatarios</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lets_Talk__c/fields/Fecha_respuesta_correo__c.field-meta.xml
<CustomField>
    <fullName>Fecha_respuesta_correo__c</fullName>
    <label>Fecha respuesta</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lets_Talk__c/fields/Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Lets Talk</relationshipLabel>
    <relationshipName>Lets_Talk</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lets_Talk__c/fields/Respuesta_Asunto__c.field-meta.xml
<CustomField>
    <fullName>Respuesta_Asunto__c</fullName>
    <label>Respuesta Asunto</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lets_Talk__c/fields/Respuesta_Cuerpo_Mensaje__c.field-meta.xml
<CustomField>
    <fullName>Respuesta_Cuerpo_Mensaje__c</fullName>
    <label>Respuesta Mensaje</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Lets_Talk__c/fields/Ultimo_mensaje_enviado__c.field-meta.xml
<CustomField>
    <fullName>Ultimo_mensaje_enviado__c</fullName>
    <label>Último mensaje enviado</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Proyecto__c/Proyecto__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre del Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proyecto__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Código de Proyecto</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Lets_talk_controller.cls
public class Lets_talk_controller {
    
    //Para Lets talk Contrato
    @AuraEnabled
    public static Lets_talk__c do_init (String lets_talk_Id){
        
        Lets_talk__c email = [SELECT id,name,Contrato__r.Name,Contrato__r.Codigo_SAP__c,Destinatarios__c,Asunto__c,Cuerpo_Mensaje__c,Respuesta_Asunto__c,Respuesta_Cuerpo_mensaje__c,Fecha_respuesta_Correo__c,CC__c from Lets_talk__c where ID=:lets_talk_Id limit 1];
        system.debug('Lets talk record ID do init '+ email.id);
        
        return email;
        
    }
    
    @AuraEnabled
    public static String enviar_email (String lets_talk_Id){
        
        Lets_talk__c correo = [SELECT id,name,Contrato__r.Id,Contrato__r.Name,Contrato__r.Codigo_SAP__c,Destinatarios__c,Asunto__c,Cuerpo_Mensaje__c,ultimo_mensaje_enviado__c,CC__c from Lets_talk__c where ID=:lets_talk_Id limit 1];
        system.debug('Lets talk record ID do init '+ correo.id);
        system.debug('Contrato relacionado con lets talk '+ correo.Contrato__r.Name);
        
        
        String LetsTalk_RecordTypeID = [SELECT id FROM RecordType WHERE name = 'Historico Lets Talk Send Email' and sobjecttype ='Historico_estado_contrato__c'].Id;
        Historico_estado_contrato__c myNewHistoricos = new Historico_estado_contrato__c();
        
        
        System.debug('Destinatario:'+ correo.Destinatarios__c);
        System.debug('Creo histórico');
        Historico_estado_contrato__c myNewHistorico= new Historico_estado_contrato__c ();
        myNewHistorico.RecordTypeId=LetsTalk_RecordTypeID;
        myNewHistorico.Name = 'OACI envía correo - ' + Datetime.now() ;
        myNewHistorico.Lets_talk__c =correo.Id;
        myNewHistorico.Lets_Talk_Asunto__c=correo.Contrato__r.Codigo_SAP__c + '. ' + correo.Asunto__c;
        myNewHistorico.Lets_Talk_Destinatarios__c = correo.Destinatarios__c;
        myNewHistorico.Lets_talk_CC__c = correo.CC__c;
        myNewHistorico.lets_talk_cuerpo_mensaje__c= correo.Cuerpo_mensaje__c;
        myNewHistorico.lets_talk_fecha_envio_correo__c = Datetime.now();
        
        string fin = 'FIN';
        insert myNewHistorico;
        
        system.debug('Envio correo');
        
        
        //System.debug('Sender ORG Wide: '+ sender.address );
        
        //Paso 1. Creamos email
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        
        //Paso 2. Personas a las que enviamos el email
        List<String> listaDestinatarios = correo.Destinatarios__c.split(';');
        
        message.setToAddresses( listaDestinatarios );
        if(correo.CC__c !=null){
           List<String> listaCC = correo.CC__c.split(';');
           message.setCcAddresses( listaCC); 
        }
        
        
        //Paso 3. Asignamos quien envía el email
        OrgWideEmailAddress sender = [select Id from OrgWideEmailAddress where Address =: 'oaci@ayesa.com' limit 1];
        message.setOrgWideEmailAddressId(sender.Id);
        message.setReplyTo('oaci@ayesa.com');
       // message.setSenderDisplayName('Oficina de Auditoría y Control Interno <oaci@ayesa.com>');
        
        //Paso 4. Contenido del email, asunto y mensaje
        message.setSubject(correo.Contrato__r.Codigo_SAP__c + '. '+ correo.Asunto__c);
        String body = '<html lang="es"> <head>	<meta charset="utf-8">	<meta name="viewport" content="width=device-width, initial-scale=1">	<title></title>	<link rel="preconnect" href="https://fonts.googleapis.com">	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>';
	    body = body + '<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300&display=swap" rel="stylesheet"> 	<style type="text/css">		body {		font-family: \'IBM Plex Sans\', sans-serif;		} p.small_font_size {font-size: smaller;}		</style> </head> <body>';
        body = body + correo.Cuerpo_Mensaje__c ;
        body = body + '<br></br> <strong> Oficina de Auditoria y Control Interno </strong> <br></br> ';
        body = body + '<p class="small_font_size">Marie Curie, 2 - Edificio Ayesa<br> ';
        body = body + 'PCT Cartuja <br> ';
        body = body + '41092 Sevilla, España</p>';
        body = body + '</body></html>';
        
        message.setHtmlBody(body);
      
        // Paso 5. Enviamos el email al destinatario
    
          
        try {
            if(!Test.isRunningTest()){
                Messaging.sendEmail( new Messaging.SingleEmailMessage[] { message } );
            
                System.debug('Enviadooo');
            }
        } catch (Exception ex) {
            System.debug('Error no esperado al realizar el envío de correo: ' + ex);
            
        }
        
        //Limpiamos los campos de lets Talk por si hay que enviar otro correo2
        correo.ultimo_mensaje_enviado__c= 'Fecha envío: ' + Datetime.now() +'<br></br>'+ correo.Cuerpo_Mensaje__c;
        correo.Destinatarios__c='';
        correo.Asunto__c='';
        correo.Cuerpo_Mensaje__c='';
        correo.CC__c='';
        update correo;
        
        
        return fin;
        
    }
    
    @AuraEnabled
    public static String guardar_email (String lets_talk_Id){
        
        Lets_talk__c correo = [SELECT id,name,Contrato__r.Name,Respuesta_Asunto__c,Respuesta_Cuerpo_mensaje__c,Fecha_respuesta_Correo__c from Lets_talk__c where ID=:lets_talk_Id limit 1];
        system.debug('Lets talk record ID do init '+ correo.id);
        
        String LetsTalk_RecordTypeID = [SELECT id FROM RecordType WHERE name = 'Historico Lets Talk Save Email' and sobjecttype ='Historico_estado_contrato__c'].Id;
        
        
        Historico_estado_contrato__c myNewHistorico= new Historico_estado_contrato__c ();
        myNewHistorico.RecordTypeId=LetsTalk_RecordTypeID;
        myNewHistorico.Name = 'Respuesta usuario - ' + correo.Fecha_respuesta_Correo__c ;
        myNewHistorico.Lets_talk__c =correo.Id;
        myNewHistorico.Lets_Talk_Respuesta_Asunto__c = correo.Respuesta_Asunto__c;
        myNewHistorico.lets_talk_Respuesta_mensaje__c = correo.Respuesta_Cuerpo_mensaje__c;
        myNewHistorico.lets_talk_fecha_respuesta_correo__c = correo.Fecha_respuesta_Correo__c;
        insert myNewHistorico;
        
        
        
        
        //Limpiamos los campos de lets Talk por si hay que enviar otro correo
        
        correo.Respuesta_Asunto__c='';
        correo.Respuesta_Cuerpo_mensaje__c='';
        correo.Fecha_respuesta_Correo__c=null;
        update correo;
        string fin = 'FIN';
        return fin;
        
    }
    //FIN CONTRATO
    
    
    
    
    //Para Lets talk Proyecto
    @AuraEnabled
    public static Lets_talk__c do_init_proyecto (String lets_talk_Id){
        
        Lets_talk__c email = [SELECT id,name,Proyecto__r.Name,Proyecto__r.Codigo__c,Destinatarios__c,Asunto__c,Cuerpo_Mensaje__c,Respuesta_Asunto__c,Respuesta_Cuerpo_mensaje__c,Fecha_respuesta_Correo__c,CC__c from Lets_talk__c where ID=:lets_talk_Id limit 1];
        system.debug('Lets talk record ID do init '+ email.id);
       
        return email;
        
    }


    
    @AuraEnabled
    public static String enviar_email_proyecto (String lets_talk_Id){
        
        Lets_talk__c correo = [SELECT id,name,Proyecto__r.Id,Proyecto__r.Name,Proyecto__r.Codigo__c,Destinatarios__c,Asunto__c,Cuerpo_Mensaje__c,ultimo_mensaje_enviado__c,CC__c from Lets_talk__c where ID=:lets_talk_Id limit 1];
        system.debug('Lets talk record ID do init '+ correo.id);
        system.debug('Contrato relacionado con lets talk '+ correo.Proyecto__r.Name);
        
        
        String LetsTalk_RecordTypeID = [SELECT id FROM RecordType WHERE name = 'Historico Lets Talk Send Email' and sobjecttype ='Historico_estado_proyecto__c'].Id;
        Historico_estado_proyecto__c myNewHistoricos = new Historico_estado_proyecto__c();
        
        
        System.debug('Destinatario:'+ correo.Destinatarios__c);
        System.debug('Creo histórico');
        Historico_estado_proyecto__c myNewHistorico= new Historico_estado_proyecto__c ();
        myNewHistorico.RecordTypeId=LetsTalk_RecordTypeID;
        myNewHistorico.Name = 'OACI envía correo - ' + Datetime.now() ;
        myNewHistorico.Lets_talk__c =correo.Id;
        myNewHistorico.Lets_Talk_Asunto__c=correo.Proyecto__r.Codigo__c + '. '+ correo.Asunto__c;
        myNewHistorico.Lets_Talk_Destinatarios__c = correo.Destinatarios__c;
        myNewHistorico.Lets_talk_CC__c = correo.CC__c;
        myNewHistorico.lets_talk_cuerpo_mensaje__c= correo.Cuerpo_mensaje__c;
        myNewHistorico.lets_talk_fecha_envio_correo__c = Datetime.now();
        
        string fin = 'FIN';
        insert myNewHistorico;
        
        system.debug('Envio correo');
        
        
        //System.debug('Sender ORG Wide: '+ sender.address );
        
        //Paso 1. Creamos email
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        
        //Paso 2. Personas a las que enviamos el email
        List<String> listaDestinatarios = correo.Destinatarios__c.split(';');
        
        message.setToAddresses( listaDestinatarios );
        if(correo.CC__c !=null){
           List<String> listaCC = correo.CC__c.split(';');
           message.setCcAddresses( listaCC); 
        }
        
        
        //Paso 3. Asignamos quien envía el email
        OrgWideEmailAddress sender = [select Id from OrgWideEmailAddress where Address =: 'oaci@ayesa.com' limit 1];
        message.setOrgWideEmailAddressId(sender.Id);
        message.setReplyTo('oaci@ayesa.com');
       // message.setSenderDisplayName('Oficina de Auditoría y Control Interno <oaci@ayesa.com>');
        
        //Paso 4. Contenido del email, asunto y mensaje
        message.setSubject(correo.Proyecto__r.Codigo__c + '. '+ correo.Asunto__c);
        String body = '<html lang="es"> <head>	<meta charset="utf-8">	<meta name="viewport" content="width=device-width, initial-scale=1">	<title></title>	<link rel="preconnect" href="https://fonts.googleapis.com">	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>';
	    body = body + '<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300&display=swap" rel="stylesheet"> 	<style type="text/css">		body {		font-family: \'IBM Plex Sans\', sans-serif;		} p.small_font_size {font-size: smaller;}		</style> </head> <body>';
        body = body + correo.Cuerpo_Mensaje__c ;
        body = body + '<br></br> <strong> Oficina de Auditoria y Control Interno </strong> <br></br> ';
        body = body + '<p class="small_font_size">Marie Curie, 2 - Edificio Ayesa<br> ';
        body = body + 'PCT Cartuja <br> ';
        body = body + '41092 Sevilla, España</p>';
        body = body + '</body></html>';
        message.setHtmlBody(body);
      
        // Paso 5. Enviamos el email al destinatario
    
          
        try {
            if(!Test.isRunningTest()){
                Messaging.sendEmail( new Messaging.SingleEmailMessage[] { message } );
            
                System.debug('Enviadooo');
            }
        } catch (Exception ex) {
            System.debug('Error no esperado al realizar el envío de correo: ' + ex);
            
        }
        
        //Limpiamos los campos de lets Talk por si hay que enviar otro correo2
        correo.ultimo_mensaje_enviado__c= 'Fecha envío: ' + Datetime.now() +'<br></br>'+ correo.Cuerpo_Mensaje__c;
        correo.Destinatarios__c='';
        correo.Asunto__c='';
        correo.Cuerpo_Mensaje__c='';
        correo.CC__c='';
        update correo;
        
        
        return fin;
        
    }
    
    @AuraEnabled
    public static String guardar_email_proyecto (String lets_talk_Id){
        
        Lets_talk__c correo = [SELECT id,name,Proyecto__r.Name,Proyecto__r.Codigo__c,Respuesta_Asunto__c,Respuesta_Cuerpo_mensaje__c,Fecha_respuesta_Correo__c from Lets_talk__c where ID=:lets_talk_Id limit 1];
        system.debug('Lets talk record ID do init '+ correo.id);
        
        String LetsTalk_RecordTypeID = [SELECT id FROM RecordType WHERE name = 'Historico Lets Talk Save Email' and sobjecttype ='Historico_estado_proyecto__c'].Id;
        
        
        Historico_estado_proyecto__c myNewHistorico= new Historico_estado_proyecto__c ();
        myNewHistorico.RecordTypeId=LetsTalk_RecordTypeID;
        myNewHistorico.Name = 'Respuesta usuario - ' + correo.Fecha_respuesta_Correo__c ;
        myNewHistorico.Lets_talk__c =correo.Id;
        myNewHistorico.Lets_Talk_Respuesta_Asunto__c = correo.Respuesta_Asunto__c;
        myNewHistorico.lets_talk_Respuesta_mensaje__c = correo.Respuesta_Cuerpo_mensaje__c;
        myNewHistorico.lets_talk_fecha_respuesta_correo__c = correo.Fecha_respuesta_Correo__c;
        insert myNewHistorico;
        
        
        
        
        //Limpiamos los campos de lets Talk por si hay que enviar otro correo
        
        correo.Respuesta_Asunto__c='';
        correo.Respuesta_Cuerpo_mensaje__c='';
        correo.Fecha_respuesta_Correo__c=null;
        update correo;
        string fin = 'FIN';
        return fin;
        
    }
    
    
    
    
    
    
    
    
}