force-app/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <description>Entidad creada para gestión y actualización de los estados de los contratos.</description>
    <label>Contrato</label>
    <nameField>
        <label>Denominación SAP</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato__c/fields/Codigo_SAP__c.field-meta.xml
<CustomField>
    <fullName>Codigo_SAP__c</fullName>
    <externalId>true</externalId>
    <label>Código SAP</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/IC_real__c.field-meta.xml
<CustomField>
    <fullName>IC_real__c</fullName>
    <label>IC Real moneda contrato</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo que relaciona la entidad Contrato (Gestión contratos) con la entidad Proyecto (AContract)</description>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Contratos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proyecto__c/Proyecto__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre del Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proyecto__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Código de Proyecto</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Proyecto__c/fields/Importe_calculado_contrato__c.field-meta.xml
<CustomField>
    <fullName>Importe_calculado_contrato__c</fullName>
    <description>Importe del proyecto calculado como la suma de los importes de contrato</description>
    <label>Importe calculado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GC_Calculo_Imp_Proyecto.cls
global class GC_Calculo_Imp_Proyecto implements Database.Batchable<sObject> {
    /*  
@AuraEnabled
public static void Calculoimporte (){

List<Proyecto__c>  Lista_proyectos = [SELECT ID,Name,Codigo__c,Importe_calculado_contrato__c FROM Proyecto__c];
System.debug('Lista de proyectos: '+ lista_proyectos.size());

List<Proyecto__c>  Lista_Proyectos_update = new List<Proyecto__c>();

for(Proyecto__c proj: Lista_proyectos){
Double Imp_proy_sum=0;
List<Contrato__c> Contratos_relacionados = new List<Contrato__c>();
Contratos_relacionados = [SELECT ID, Name,Codigo_SAP__C, IC_Real__c FROM Contrato__c Where Proyecto__c=: proj.Id];

if(contratos_relacionados.size()>0){
for(Contrato__c contra: Contratos_relacionados){
if(contra.IC_real__c >=0){
Imp_proy_sum+= contra.IC_real__c;
}
}
}

proj.Importe_calculado_contrato__c=Imp_proy_sum;
Lista_Proyectos_update.add(proj);
}
System.debug('Terminado el bucle de los proyectos y los contratos');

update Lista_Proyectos_update;
}
*/
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        
        string query = 'SELECT ID,Name,Codigo__c,Importe_calculado_contrato__c FROM Proyecto__c';
        
        System.debug('QUERY: '+ query);
        return Database.getQueryLocator(query);
    } 
    global void execute(Database.BatchableContext BC, List<Proyecto__c> proyectos){
        List<Proyecto__c>  Lista_proyectos = [SELECT ID,Name,Codigo__c,Importe_calculado_contrato__c FROM Proyecto__c];
        System.debug('Lista de proyectos: '+ lista_proyectos.size());
        
        List<Proyecto__c>  Lista_Proyectos_update = new List<Proyecto__c>();
        
        for(Proyecto__c proj : [SELECT ID, Name,Codigo__c,Importe_calculado_contrato__c, (SELECT ID, Name,Codigo_SAP__C, IC_Real__c from Contratos__r) FROM Proyecto__c]){
            Double Imp_proy_sum=0;
           // List<Contrato__c> Contratos_relacionados = new List<Contrato__c>();
         //   Contratos_relacionados = [SELECT ID, Name,Codigo_SAP__C, IC_Real__c FROM Contrato__c Where Proyecto__c=: proj.Id];
            
            
                for(Contrato__c contra: proj.Contratos__r){
                    if(contra.IC_real__c >=0){
                        Imp_proy_sum+= contra.IC_real__c;
                    }
                }
      
            
            proj.Importe_calculado_contrato__c=Imp_proy_sum;
            Lista_Proyectos_update.add(proj);
        }
        System.debug('Terminado el bucle de los proyectos y los contratos');
        
        update Lista_Proyectos_update;
        
    }
    global void finish(Database.BatchableContext BC){
        
    }
}