force-app/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <description>Entidad creada para gestión y actualización de los estados de los contratos.</description>
    <label>Contrato</label>
    <nameField>
        <label>Denominación SAP</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato__c/fields/Codigo_SAP__c.field-meta.xml
<CustomField>
    <fullName>Codigo_SAP__c</fullName>
    <externalId>true</externalId>
    <label>Código SAP</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/DivisionPicklist__c.field-meta.xml
<CustomField>
    <fullName>DivisionPicklist__c</fullName>
    <label>División</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mercado__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>V-AERONAUTICS</fullName>
            </value>
            <value>
                <fullName>V-AGE</fullName>
            </value>
            <value>
                <fullName>V-AUSTRALIA</fullName>
                <isActive>false</isActive>
                <label>V-AUSTRALIA</label>
            </value>
            <value>
                <fullName>V-AVIATION</fullName>
            </value>
            <value>
                <fullName>V-BANKING</fullName>
            </value>
            <value>
                <fullName>V-BPO (PS)</fullName>
            </value>
            <value>
                <fullName>V-BPO (U&amp;E)</fullName>
            </value>
            <value>
                <fullName>V-BUILDING EMEA &amp; ASIA</fullName>
            </value>
            <value>
                <fullName>V-BUILDING LATAM</fullName>
            </value>
            <value>
                <fullName>V-BUILDING SPAIN</fullName>
            </value>
            <value>
                <fullName>V-COMUNIDAD DE MADRID</fullName>
            </value>
            <value>
                <fullName>V-CONSUMER</fullName>
            </value>
            <value>
                <fullName>V-CONTROL GESTION AERONAUTICA</fullName>
            </value>
            <value>
                <fullName>V-CULTURA Y TURISMO</fullName>
            </value>
            <value>
                <fullName>V-DESARROLLO SOST Y TURISMO</fullName>
                <label>V-DESARROLLO SOSTENIBLE</label>
            </value>
            <value>
                <fullName>V-DIRECTOR DIGITAL SERVICES</fullName>
                <isActive>false</isActive>
                <label>V-DIRECTOR DIGITAL SERVICES</label>
            </value>
            <value>
                <fullName>V-DIVERSIFICATION DIRECTOR</fullName>
                <isActive>false</isActive>
                <label>V-DIVERSIFICATION DIRECTOR</label>
            </value>
            <value>
                <fullName>V-E.E.U.U.</fullName>
                <isActive>false</isActive>
                <label>V-E.E.U.U.</label>
            </value>
            <value>
                <fullName>V-ECOFIN</fullName>
            </value>
            <value>
                <fullName>V-EDUCACION</fullName>
            </value>
            <value>
                <fullName>V-EMPLEO E INNOVACION</fullName>
            </value>
            <value>
                <fullName>V-ENEL</fullName>
            </value>
            <value>
                <fullName>V-ENERGY ENG.</fullName>
            </value>
            <value>
                <fullName>V-ENVIRONMENT</fullName>
            </value>
            <value>
                <fullName>V-ETC VALUE OFFERING (C)</fullName>
                <isActive>false</isActive>
                <label>V-ETC VALUE OFFERING (C)</label>
            </value>
            <value>
                <fullName>V-ETC VALUE OFFERING (PS)</fullName>
                <isActive>false</isActive>
                <label>V-ETC VALUE OFFERING (PS)</label>
            </value>
            <value>
                <fullName>V-ETC VALUE OFFERING (R&amp;E)</fullName>
                <isActive>false</isActive>
                <label>V-ETC VALUE OFFERING (R&amp;E)</label>
            </value>
            <value>
                <fullName>V-ETC VALUE OFFERING (T)</fullName>
                <isActive>false</isActive>
                <label>V-ETC VALUE OFFERING (T)</label>
            </value>
            <value>
                <fullName>V-ETC VALUE OFFERING (U&amp;E)</fullName>
                <isActive>false</isActive>
                <label>V-ETC VALUE OFFERING (U&amp;E)</label>
            </value>
            <value>
                <fullName>V-GESTION TERRITORIAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ENMA</fullName>
            </value>
            <value>
                <fullName>RECEP</fullName>
            </value>
            <value>
                <fullName>SINC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Id_Tasking__c.field-meta.xml
<CustomField>
    <fullName>Id_Tasking__c</fullName>
    <label>Id Tasking</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Id_tasking_Elemento_SAP_Contrato__c.field-meta.xml
<CustomField>
    <fullName>Id_tasking_Elemento_SAP_Contrato__c</fullName>
    <label>Id tasking Elemento SAP Contrato</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Mercado__c.field-meta.xml
<CustomField>
    <fullName>Mercado__c</fullName>
    <label>Mercado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>60029505</fullName>
                <label>V-AERONAUTICS</label>
            </value>
            <value>
                <fullName>V-ANGLO MARKET</fullName>
                <isActive>false</isActive>
                <label>V-ANGLO MARKET</label>
            </value>
            <value>
                <fullName>60034542</fullName>
                <label>V-BFSI, TELCO &amp; MEDIA</label>
            </value>
            <value>
                <fullName>V-CITIES</fullName>
                <isActive>false</isActive>
                <label>V-CITIES</label>
            </value>
            <value>
                <fullName>60029413</fullName>
                <label>V-DIGITAL ADMINISTRATION &amp; HEALTH</label>
            </value>
            <value>
                <fullName>60030704</fullName>
                <isActive>false</isActive>
                <label>V-INNO</label>
            </value>
            <value>
                <fullName>60029512</fullName>
                <label>V-MANUFACT. &amp; COMSUMER</label>
            </value>
            <value>
                <fullName>60029482</fullName>
                <label>V-RESOURCES &amp; ENVIRONMENT</label>
            </value>
            <value>
                <fullName>60029494</fullName>
                <label>V-TRANSPORTATION &amp; CITIES</label>
            </value>
            <value>
                <fullName>60029427</fullName>
                <label>V-UTILITIES &amp; ENERGY</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo que relaciona la entidad Contrato (Gestión contratos) con la entidad Proyecto (AContract)</description>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Contratos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proyecto__c/Proyecto__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre del Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proyecto__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Código de Proyecto</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Proyecto__c/fields/Mercado__c.field-meta.xml
<CustomField>
    <fullName>Mercado__c</fullName>
    <label>Mercado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>60029505</fullName>
                <label>V-AERONAUTICS</label>
            </value>
            <value>
                <fullName>60034542</fullName>
                <label>V-BFSI, TELCO &amp; MEDIA</label>
            </value>
            <value>
                <fullName>V-CITIES</fullName>
                <isActive>false</isActive>
                <label>V-CITIES</label>
            </value>
            <value>
                <fullName>60029413</fullName>
                <label>V-DIGITAL ADMINISTRATION &amp; HEALTH</label>
            </value>
            <value>
                <fullName>60030704</fullName>
                <isActive>false</isActive>
                <label>V-INNO</label>
            </value>
            <value>
                <fullName>60029512</fullName>
                <label>V-MANUFACT. &amp; COMSUMER</label>
            </value>
            <value>
                <fullName>60029482</fullName>
                <label>V-RESOURCES &amp; ENVIRONMENT</label>
            </value>
            <value>
                <fullName>60029494</fullName>
                <label>V-TRANSPORTATION &amp; CITIES</label>
            </value>
            <value>
                <fullName>60029427</fullName>
                <label>V-UTILITIES &amp; ENERGY</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GC_Importacion_Tasking_Test.cls
@isTest(SeeAllData = true)
public class GC_Importacion_Tasking_Test {

    @isTest(SeeAllData = true)
    public static void test() {
		Contrato__c myContract = new Contrato__c();
        List<Contrato__c> contratos = [SELECT id, Codigo_SAP__c, Proyecto__r.Codigo__c, Id_Tasking__c, Id_tasking_Elemento_SAP_Contrato__c
                                       FROM Contrato__c
                                       WHERE Codigo_SAP__c != null AND Proyecto__r.Codigo__c != null
                                       LIMIT 1
                                      ];
        
        if (!contratos.isEmpty()) {
            myContract = contratos[0];
        } else {
            myContract.Codigo_SAP__c = 'SAP_TEST_001';
            myContract.Id_Tasking__c = 'TASK123';
            myContract.Id_tasking_Elemento_SAP_Contrato__c = 'TASK_SAP';
            myContract.Estado__c='ENMA';
            myContract.DivisionPicklist__c='V-AERONAUTICS';
            myContract.Mercado__c='60029505';
            
            // Simulamos también el campo relacionado Proyecto__r.Codigo__c, si es accedido por métodos
            Proyecto__c proyectoFake = new Proyecto__c(Codigo__c = 'PRJ001');
            insert proyectoFake;
            myContract.Proyecto__r = proyectoFake;
            insert myContract;
        }
        GC_Importacion_Tasking.contractInfo(myContract.Id);
        GC_Importacion_Tasking.test();

    }
}