force-app/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <description>Entidad creada para gestión y actualización de los estados de los contratos.</description>
    <label>Contrato</label>
    <nameField>
        <label>Denominación SAP</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ENMA</fullName>
            </value>
            <value>
                <fullName>RECEP</fullName>
            </value>
            <value>
                <fullName>SINC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/IC_moneda_contrato__c.field-meta.xml
<CustomField>
    <fullName>IC_moneda_contrato__c</fullName>
    <label>IC moneda contrato</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Hito__c/Hito__c.object-meta.xml
<CustomObject>
    <label>Hito</label>
    <nameField>
        <label>Nombre de Hito</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hitos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Hito__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contrato__c</referenceTo>
    <relationshipLabel>Hitos</relationshipLabel>
    <relationshipName>Hitos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hito__c/fields/Importe_contractual__c.field-meta.xml
<CustomField>
    <fullName>Importe_contractual__c</fullName>
    <label>Importe contractual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Subentregable__c/Subentregable__c.object-meta.xml
<CustomObject>
    <label>Entregable</label>
    <nameField>
        <label>Nombre de Entregables</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entregables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subentregable__c/fields/Avance__c.field-meta.xml
<CustomField>
    <fullName>Avance__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Avance</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Subentregable__c/fields/AvancePonderado__c.field-meta.xml
<CustomField>
    <fullName>AvancePonderado__c</fullName>
    <formula>Peso__c *  Avance__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Weight per advance. Used to calculate the production progress of the deliverable</inlineHelpText>
    <label>Avance Ponderado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Subentregable__c/fields/Cerrado__c.field-meta.xml
<CustomField>
    <fullName>Cerrado__c</fullName>
    <formula>ISPICKVAL(Estado__c, &apos;Firmado&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cerrado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subentregable__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contrato__c</referenceTo>
    <relationshipLabel>Entregables</relationshipLabel>
    <relationshipName>Entregables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subentregable__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estado_Entregables</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subentregable__c/fields/Hito__c.field-meta.xml
<CustomField>
    <fullName>Hito__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hito</label>
    <referenceTo>Hito__c</referenceTo>
    <relationshipLabel>Entregables</relationshipLabel>
    <relationshipName>Entregables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subentregable__c/fields/Peso__c.field-meta.xml
<CustomField>
    <fullName>Peso__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Peso</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/TDRSubentregable__c/TDRSubentregable__c.object-meta.xml
<CustomObject>
    <label>Relación Entregable con TDR</label>
    <nameField>
        <displayFormat>TDRSUB-{0000000}</displayFormat>
        <label>Código TDR-ENT</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relaciones Entregables con TDRs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TDRSubentregable__c/fields/Subentregable__c.field-meta.xml
<CustomField>
    <fullName>Subentregable__c</fullName>
    <label>Entregable</label>
    <referenceTo>Subentregable__c</referenceTo>
    <relationshipLabel>Relaciones Entregables con TDR</relationshipLabel>
    <relationshipName>TDRsEntregables</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TDRSubentregable__c/fields/TerminoReferencia__c.field-meta.xml
<CustomField>
    <fullName>TerminoReferencia__c</fullName>
    <label>Término de Referencia</label>
    <referenceTo>Termino_de_Referencia__c</referenceTo>
    <relationshipName>TDRsEntregables</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Termino_de_Referencia__c/Termino_de_Referencia__c.object-meta.xml
<CustomObject>
    <label>Término de Referencia</label>
    <nameField>
        <label>Código TDR</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Términos de Referencia</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Termino_de_Referencia__c/fields/Cerrado__c.field-meta.xml
<CustomField>
    <fullName>Cerrado__c</fullName>
    <formula>TEXT(Estado__c) = &apos;Aprobado&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Automatically checked when status is accepted</inlineHelpText>
    <label>Cerrado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Termino_de_Referencia__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contrato__c</referenceTo>
    <relationshipLabel>Término de Referencia</relationshipLabel>
    <relationshipName>Terminos_de_Referencia</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Termino_de_Referencia__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
                <default>true</default>
                <label>Pendiente</label>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Estado_Entregables.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cancelado</fullName>
    </customValue>
    <customValue>
        <fullName>Pendiente</fullName>
        <default>true</default>
        <label>Pendiente</label>
    </customValue>
    <customValue>
        <fullName>En proceso</fullName>
    </customValue>
    <customValue>
        <fullName>En Revisión Interna</fullName>
    </customValue>
    <customValue>
        <fullName>Finalizado</fullName>
    </customValue>
    <customValue>
        <fullName>Liberado</fullName>
    </customValue>
    <customValue>
        <fullName>Firmado</fullName>
    </customValue>
    <customValue>
        <fullName>Pendiente de Firma</fullName>
        <isActive>false</isActive>
        <label>Pendiente de Firma</label>
    </customValue>
    <customValue>
        <fullName>En desarrollo</fullName>
        <isActive>false</isActive>
        <label>En desarrollo</label>
    </customValue>
    <masterLabel>Estado Entregables</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GC_Avances_Contrato_Controller.cls
public class GC_Avances_Contrato_Controller {

    //Listado informacion de avances / KPIs
    public class AvancesInfo {
       
        public string result; 
        public List<Avance> avance;
        
    }
    //Resultados informacion de avances / KPIs
    public class Avance {
       
        public string entidad ;
        public string seccion;
        public string info;
        
    }
    
    private static string sOpen = 'Pendiente', sClosed = 'Aprobado';
    //private static string ePending = 'Pendiente', eDev ='En desarrollo', eFree = 'Liberado', eClosed = 'Firmado';
    
    @AuraEnabled
    public static string getInfoAvances(string contractId){
        string result='';
        List<Contrato__c> myContract= [Select id, name, IC_moneda_contrato__c from Contrato__c where id=:contractId];
        Decimal importContract=0;
        List<Termino_de_Referencia__c> myCurrentTDRList = [SELECT id, name from Termino_de_Referencia__c where Contrato__c=:contractId]; //lista de actuales TDR's de mi contrato  
        List<Termino_de_Referencia__c> myCurrentAprovedTDRList = [SELECT id, name, Cerrado__c from Termino_de_Referencia__c where Contrato__c=:contractId and Cerrado__c=true]; //lista de actuales TDR's APROBADOS de mi contrato  
        List<Subentregable__c> myCurrentEntregableList = [SELECT id, name from Subentregable__c where Contrato__c=:contractId]; //lista de actuales Entregables de mi contrato
        List<Subentregable__c> myCurrentSignedList = [SELECT id, name from Subentregable__c where Contrato__c=:contractId and Cerrado__c=true]; //lista de actuales Entregables FIRMADOS de mi contrato

        Decimal avanceTDR=0;
        Decimal avanceENT=0;
        
        //Para calculo de avance Técnico
        List<Subentregable__c> myRelatedEntregableHitoList = [SELECT id, name,Avance__c, AvancePonderado__c, Peso__c, Hito__r.id from Subentregable__c where Contrato__c=:contractId and Hito__c!=null];
        List<Hito__c> myCurrentHitoList = [SELECT id, name, Importe_contractual__c,  Contrato__r.IC_moneda_contrato__c  from Hito__c where Contrato__c=:contractId];
        
        Map<String,Subentregable__c> myMapEntregablesconHito = new Map<String,Subentregable__c>();
        Map<String,Hito__c> myMapHitos = new Map<String,Hito__c>();
        
        AvancesInfo myAvancesList = new AvancesInfo();
        List<Avance> avancesList = new List<Avance>();
        Avance myTDRInfo = new Avance();
        Avance myTDRAprovedInfo = new Avance();
        Avance myTDRAvanceInfo = new Avance();
        Avance myEntInfo = new Avance();
        Avance myEntSignedInfo = new Avance();
        Avance myEntAvanceInfo = new Avance();
        Avance myHitoInfo = new Avance();
        
        myAvancesList.result='OK';
        system.debug('CONTEO - Tamaño lista TDRs: '+ myCurrentTDRList.size());
        system.debug('CONTEO - Tamaño lista TDRS aprobados: '+myCurrentAprovedTDRList.size() );
        system.debug('CONTEO - Tamaño lista Entregables: '+myCurrentEntregableList.size() );
        system.debug('CONTEO - Tamaño lista Entregables Firmados: '+myCurrentSignedList.size() );
        //system.debug('CONTEO - Tamaño lista Hitos: '+myCurrentHitoList.size() );
        //system.debug('CONTEO - Tamaño lista Relaciones: '+ (myCurrentRelacionesList.size() + myRelatedEntregableHitoList.size()) );
        
        
        if(myCurrentTDRList.size() >= 0){
           
            myTDRInfo.entidad='TDR' ;
            myTDRInfo.seccion='Total de TDRs';
            myTDRInfo.info= string.ValueOf(myCurrentTDRList.size());
                     
        }
        
        if(myCurrentAprovedTDRList.size() >= 0){
           
            myTDRAprovedInfo.entidad='TDR' ;
            myTDRAprovedInfo.seccion='Total de TDRs aprobados';
            myTDRAprovedInfo.info= string.ValueOf(myCurrentAprovedTDRList.size());
            
            avanceTDR= ((Decimal.ValueOf(myCurrentAprovedTDRList.size())/Decimal.ValueOf(myCurrentTDRList.size())) *100 ).setScale(2);
             system.debug('Avance TDR: '+avanceTDR);
            
            myTDRAvanceInfo.entidad='TDR_AVANCE' ;
            myTDRAvanceInfo.seccion='AVANCE';
            myTDRAvanceInfo.info= string.ValueOf(avanceTDR);
        }
        
        
        if(myCurrentEntregableList.size() >= 0){
            myEntInfo.entidad='ENT' ;
            myEntInfo.seccion='Total de Entregables';
            myEntInfo.info= string.ValueOf(myCurrentEntregableList.size());
        }
        
        if(myCurrentSignedList.size() >= 0){
            myEntSignedInfo.entidad='ENT' ;
            myEntSignedInfo.seccion='Total de Entregables firmados';
            myEntSignedInfo.info= string.ValueOf(myCurrentSignedList.size());
            
            avanceENT= ((Decimal.ValueOf(myCurrentSignedList.size())/Decimal.ValueOf(myCurrentEntregableList.size()))*100).setScale(2);
            
           
            system.debug('Avance ENTREGABLES double: '+avanceENT);
            
            myEntAvanceInfo.entidad='ENT_AVANCE' ;
            myEntAvanceInfo.seccion='AVANCE';
            myEntAvanceInfo.info= string.ValueOf(avanceENT);
        }
        
        if(myRelatedEntregableHitoList.size() > 0){ //Tiene Entregables relacionados con algún Hito
            
            //Relleno el mapa de entregables
            /*for(Subentregable__c ent : myRelatedEntregableHitoList){
                myMapEntregablesconHito.put(ent.Id, ent);
            }*/
            
            if(myContract.size() > 0){
                importContract=myContract[0].IC_moneda_contrato__c;
            }
            
            //Relleno el mapa de hitos
            for(Hito__c hito : myCurrentHitoList){
                myMapHitos.put(hito.Id, hito);
            }
            
            //Recorro cada Hito 
            Decimal sumTotal=0;
            Decimal porcentajeFinal=0;
            Decimal sumAux=0;
            for (String keyHito : myMapHitos.keySet()){
                 //sumAux=0;
                 for(Subentregable__c ent : myRelatedEntregableHitoList){                    
                     if(keyHito==ent.Hito__r.id){
                         sumAux=sumAux + (ent.AvancePonderado__c)*(myMapHitos.get(keyHito)).Importe_contractual__c;
                     }
                }
            }
            porcentajeFinal= (sumAux / importContract).setScale(2);
            
            myHitoInfo.entidad='HITO' ;
            myHitoInfo.seccion='Avance técnico ';
            myHitoInfo.info= string.Valueof(porcentajeFinal);
            
        }else if (myRelatedEntregableHitoList.size() == 0) {
            myHitoInfo.entidad='HITO' ;
            myHitoInfo.seccion='Avance técnico ';
            myHitoInfo.info= '0';
        }
        
        
        avancesList.add(myTDRInfo);
        avancesList.add(myTDRAprovedInfo);
        avancesList.add(myEntInfo);
        avancesList.add(myEntSignedInfo);
        avancesList.add(myHitoInfo);
        avancesList.add(myEntAvanceInfo);
        avancesList.add(myTDRAvanceInfo);
        
        
        myAvancesList.avance=avancesList;
        
        result= JSON.serialize(myAvancesList);
        
        return result;
    }
    
     
    //Método que se utiliza en los botones ACTUALIZAR TDR's
    @AuraEnabled
    public static string updateTdrStatusProcess(string contractId){
        // Se sincronizan los estados de los TDR's asociados a los subentregables
        string result ='KO';
        List<Termino_de_Referencia__c> tdrs = [SELECT id from Termino_de_Referencia__c where Contrato__c = :contractId];
        List<Id> tdrIds = new List<ID>();
        for(Termino_de_Referencia__c tdr : tdrs){
            tdrIds.add(tdr.Id);
        }
        
        Termino_de_Referencia__c tmpTdr;
        List<Termino_de_Referencia__c> finalTdrs = new List<Termino_de_Referencia__c>();
        List<AggregateResult> openTdrs = [select terminoreferencia__c, count(subentregable__r.Id) open from TDRSubentregable__c where subentregable__r.cerrado__c = false and terminoreferencia__c in :tdrIds group by terminoreferencia__c];   
        for(AggregateResult tdr : openTdrs){
            tmpTdr = new Termino_de_Referencia__c();
            tmpTdr.Id = (Id)tdr.get('TerminoReferencia__c');
            tmpTdr.estado__c = sOpen;
            tdrIds.remove(tdrIds.indexOf(tmpTdr.Id));       
            finalTdrs.add(tmpTdr);
        }
        
        List<Termino_de_Referencia__c> closedTdrs = [select id from Termino_de_Referencia__c where id in (select terminoreferencia__c from TDRSubentregable__c where terminoreferencia__c in:tdrIds)];       
        for(Termino_de_Referencia__c tdr : closedTdrs){   
            tdr.estado__c =sClosed;
            finalTdrs.add(tdr);
        }
        
        List<Termino_de_Referencia__c> uncoveredTdrs = [select id from Termino_de_Referencia__c where id in :tdrids and id not in (select terminoreferencia__c from TDRSubentregable__c where terminoreferencia__c in:tdrIds)];       
        for(Termino_de_Referencia__c tdr : uncoveredTdrs){   
            tdr.estado__c = sOpen;
            finalTdrs.add(tdr);
        }
        
        Map<Id, Termino_de_Referencia__c> mapTdr = new Map<Id, Termino_de_Referencia__c>();
        mapTdr.putAll(finalTdrs);
        
        
        try{
            update  mapTdr.values();
            result='OK';
            System.debug('CALCULO TDRS - Tamaño lista actualizada : ' + mapTdr.size());
            
        }catch(System.DmlException ex){
            result='KO';            
            System.debug('Error: ' + ex.getMessage());         
            System.debug('Mensaje: ' + ex.getStackTraceString());
            System.debug(ex.getCause());
            
        }catch(System.SecurityException es){
            result='KO';
            System.debug('Error: ' + es.getMessage());
            system.debug('Error: ' + es.getTypeName());
            system.debug('Error: ' + es.getCause());
            
        }catch(Exception e){
            result='KO';
            System.debug('Error: ' + e.getMessage());  
        }
        return result;
        
        
    }
}