force-app/main/default/objects/Equipo_Oferta__c/Equipo_Oferta__c.object-meta.xml
<CustomObject>
    <label>Equipo Oferta</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Nombre</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipos Oferta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipo_Oferta__c/fields/Horas__c.field-meta.xml
<CustomField>
    <fullName>Horas__c</fullName>
    <label>Horas</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Equipo_Oferta__c/fields/Mercantil__c.field-meta.xml
<CustomField>
    <fullName>Mercantil__c</fullName>
    <label>Mercantil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0002 - AYESA ENGINEERING S.A</fullName>
            </value>
            <value>
                <fullName>0003 - AYESA ING. Y ARQU., S.A.</fullName>
            </value>
            <value>
                <fullName>0004 - ALIA GESTION S.L.</fullName>
            </value>
            <value>
                <fullName>0005 - AYNOVA, S.A.U.</fullName>
            </value>
            <value>
                <fullName>0007 - ACT SISTEMAS, S.L.U.</fullName>
            </value>
            <value>
                <fullName>0012 - AYESA MDE, S.A.</fullName>
            </value>
            <value>
                <fullName>0018 - AYESA AIR CONTROL S.L.</fullName>
            </value>
            <value>
                <fullName>0021 - AYESA MEXICO,S.A. de C.V.</fullName>
            </value>
            <value>
                <fullName>0023 - AYESA SUCURSAL POLONIA</fullName>
            </value>
            <value>
                <fullName>0024 - AYESA POLSKA SP. Z O.O.</fullName>
            </value>
            <value>
                <fullName>0025 - AYESA MAROC, S.A.R.L</fullName>
            </value>
            <value>
                <fullName>0027 - AYESA IMPLEMEN. TECN. S.A</fullName>
            </value>
            <value>
                <fullName>0030 - AYESA ALGERIE S.A.R.L.</fullName>
            </value>
            <value>
                <fullName>0034 - AYESA SERVICIOS S RL DECV</fullName>
            </value>
            <value>
                <fullName>0035 - ALIA WORLDWIDE, S.L.</fullName>
            </value>
            <value>
                <fullName>0036 - AYESA BRANCH OFFICE</fullName>
            </value>
            <value>
                <fullName>0040 - AYESA ENGINYERIA SERVEIS</fullName>
            </value>
            <value>
                <fullName>0045 - ATECH ADVAN. SOL.</fullName>
            </value>
            <value>
                <fullName>0047 - ATECH BPO, S.L.</fullName>
            </value>
            <value>
                <fullName>0048 - UNITEC</fullName>
            </value>
            <value>
                <fullName>0049 - INSOTECH INTERNATIONAL</fullName>
            </value>
            <value>
                <fullName>0050 - AYESA PERÚ</fullName>
            </value>
            <value>
                <fullName>0053 - AYESA INDIA PRIVATE LIMIT</fullName>
            </value>
            <value>
                <fullName>0054 - AYESA COLOMBIA SAS</fullName>
            </value>
            <value>
                <fullName>0056 - AYESA PANAMÁ</fullName>
            </value>
            <value>
                <fullName>0057 - AAT PANAMÁ RUC</fullName>
            </value>
            <value>
                <fullName>0058 - AYESA PANAMÁ RUC</fullName>
            </value>
            <value>
                <fullName>0059 - AYESA COLOMBIA SUCURSAL</fullName>
            </value>
            <value>
                <fullName>0060 - AAT ECUADOR</fullName>
            </value>
            <value>
                <fullName>0061 - AYESA ECUADOR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Equipo_Oferta__c/fields/Nombre_y_apellidos__c.field-meta.xml
<CustomField>
    <fullName>Nombre_y_apellidos__c</fullName>
    <label>Nombre y apellidos</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Equipo_Oferta__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Equipos Oferta</relationshipLabel>
    <relationshipName>Equipos_Oferta</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Equipo_Oferta__c.field-meta.xml
<CustomField>
    <fullName>Equipo_Oferta__c</fullName>
    <label>Equipo Oferta</label>
    <length>13107</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/EquipoPreventaServiceTest.cls
@IsTest
private class EquipoPreventaServiceTest {
    @TestSetup
    static void setup() {
        Opportunity o = new Opportunity(Name='Test Opp', StageName='Prospecting', CloseDate=Date.today().addDays(30));
        insert o;
        insert new Equipo_Oferta__c(Opportunity__c=o.Id, Nombre_y_apellidos__c='Juan Pérez', Mercantil__c='A', Horas__c=10);
    }
    @IsTest
    static void testLoadAndSave() {
        Opportunity o = [SELECT Id FROM Opportunity LIMIT 1];
        EquipoPreventaService.InitData d = EquipoPreventaService.loadData(o.Id);
        System.assert(!d.existentes.isEmpty(), 'Debe haber 1');
        // Simular cambio + alta + baja
        List<EquipoPreventaService.EquipoPreventaWrapper> lista = new List<EquipoPreventaService.EquipoPreventaWrapper>();
        EquipoPreventaService.EquipoPreventaWrapper orig = d.existentes[0];
        orig.horas = 12; orig.isChanged = true; // update
        orig.isDeleted = true; // delete (prima el borrado)
        EquipoPreventaService.EquipoPreventaWrapper nuevo = new EquipoPreventaService.EquipoPreventaWrapper();
        nuevo.nombre='Nuevo'; nuevo.mercantil='A'; nuevo.horas=5; nuevo.isNew=true; nuevo.isChanged=true;
        lista.add(orig);
        lista.add(nuevo);
        EquipoPreventaService.SaveResultWrapper sr = EquipoPreventaService.save(o.Id, lista);
        System.assertEquals(1, sr.insertados, 'Insertados');
        System.assertEquals(0, sr.actualizados, 'Actualizados');
        System.assertEquals(1, sr.eliminados, 'Eliminados');
        System.assert(sr.html.contains('<table'), 'HTML generado');
    }
}