force-app/main/default/objects/Entregable__c/Entregable__c.object-meta.xml
<CustomObject>
    <label>Grupo de Entregables</label>
    <nameField>
        <label>Nombre de Grupo de Entregables</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos de Entregables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Entregable__c/fields/Entregable__c.field-meta.xml
<CustomField>
    <fullName>Entregable__c</fullName>
    <externalId>true</externalId>
    <label>Código Grupo de Entregables</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Entregable__c/fields/Fase__c.field-meta.xml
<CustomField>
    <fullName>Fase__c</fullName>
    <label>Fase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Preparación</fullName>
                <label>1 - Preparación Inicial</label>
            </value>
            <value>
                <fullName>Diseño</fullName>
                <label>2 - Diseño</label>
            </value>
            <value>
                <fullName>Construcción</fullName>
                <label>3 - Construcción</label>
            </value>
            <value>
                <fullName>Pruebas</fullName>
                <label>4 - Pruebas</label>
            </value>
            <value>
                <fullName>Preparación Final</fullName>
                <label>5 - Preparación Final</label>
            </value>
            <value>
                <fullName>Go Live y Soporte</fullName>
                <label>6 - Go Live y Soporte</label>
            </value>
            <value>
                <fullName>Garantía</fullName>
                <label>7 - Garantía</label>
            </value>
            <value>
                <fullName>8 - Todas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Entregable__c/fields/Hito__c.field-meta.xml
<CustomField>
    <fullName>Hito__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Hito</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Proyecto__c</field>
            <operation>equals</operation>
            <valueField>Hito__c.Proyecto__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Hito__c</referenceTo>
    <relationshipLabel>Grupos de Entregables</relationshipLabel>
    <relationshipName>Grupos_de_Entregables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entregable__c/fields/Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Proyecto__c</fullName>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipName>Entregables</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Entregable__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_Entregable</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hito__c/Hito__c.object-meta.xml
<CustomObject>
    <label>Hito</label>
    <nameField>
        <label>Nombre de Hito</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hitos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Hito__c/fields/Fecha_Fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Fin__c</fullName>
    <description>Fecha Contractual de Fin</description>
    <label>Fecha Real</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Hito__c/fields/Peso_Facturacion__c.field-meta.xml
<CustomField>
    <fullName>Peso_Facturacion__c</fullName>
    <description>Porcentaje del hito en la facturación.</description>
    <label>Peso Facturación</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Hito__c/fields/Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Proyecto__c</fullName>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Hitos</relationshipLabel>
    <relationshipName>Hitos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proyecto__c/Proyecto__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre del Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proyecto__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Código de Proyecto</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Proyecto__c/fields/Documentalista__c.field-meta.xml
<CustomField>
    <fullName>Documentalista__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Documentalista</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ProyectosDocumentalistas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proyecto__c/fields/Entregable__c.field-meta.xml
<CustomField>
    <fullName>Entregable__c</fullName>
    <formula>Entregables__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entregables</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Tipo_Entregable.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Arquitectura</fullName>
    </customValue>
    <customValue>
        <fullName>Diseño Funcional</fullName>
    </customValue>
    <customValue>
        <fullName>Diseño Técnico</fullName>
    </customValue>
    <customValue>
        <fullName>Formación</fullName>
    </customValue>
    <customValue>
        <fullName>Gestión del Cambio</fullName>
    </customValue>
    <customValue>
        <fullName>Gestión del Proyecto</fullName>
    </customValue>
    <customValue>
        <fullName>Interfaces</fullName>
    </customValue>
    <customValue>
        <fullName>Licenciamiento</fullName>
    </customValue>
    <customValue>
        <fullName>Metodología</fullName>
    </customValue>
    <customValue>
        <fullName>Migración</fullName>
    </customValue>
    <customValue>
        <fullName>Otros</fullName>
    </customValue>
    <customValue>
        <fullName>Pruebas</fullName>
    </customValue>
    <customValue>
        <fullName>Garantía, Soporte y Mantenimiento</fullName>
    </customValue>
    <customValue>
        <fullName>Puesta en Producción</fullName>
    </customValue>
    <masterLabel>Tipo Entregable</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ActualizaAvanceTecnico_Test.cls
@isTest (SeeAllData = false)
public class ActualizaAvanceTecnico_Test {
    
    @testSetup 
    static void setup() { 
        id userid = Userinfo.getUserId();
        User user1 = [SELECT Id FROM User WHERE Id = :userid LIMIT 1];
        System.runAs ( user1 ) {
            Proyecto__c proyecto = new Proyecto__c(Name = 'Proyecto Test', Codigo__c = 'Proyecto-001', Documentalista__c = user1.Id);
            insert proyecto;
            Hito__c hito = new Hito__c(Name = 'Hito', Proyecto__c = proyecto.Id, Fecha_Fin__c = Date.newInstance(2018, 12, 17), Peso_Facturacion__c = 20 );
            insert hito;
            Entregable__c entr = new Entregable__c(Name = 'Ent', Proyecto__c = proyecto.Id, Hito__c = hito.Id, Entregable__c = 'Ent', Tipo__c = 'Otros', Fase__c = 'Pruebas');
            insert entr;
            Entregable__c entr2 = new Entregable__c(Name = 'Ent2', Proyecto__c = proyecto.Id, Hito__c = hito.Id, Entregable__c = 'Ent2', Tipo__c = 'Otros', Fase__c = 'Pruebas');
            insert entr2;
        } 
    }
    
    static TestMethod void actualizarAvanceTecnico(){
        Test.startTest(); 
        Datetime dt = Datetime.now().addMinutes(1); 
        String CRON_EXP = '0 '+ dt.minute() + ' * ' + dt.day() + ' ' + dt.month() + ' ? ' + dt.year();
        String jobId = System.schedule('Sample_Heading', CRON_EXP, new ActualizaAvanceTecnico() );
        Test.stopTest();        
    }
}