force-app/main/default/objects/Entregable__c/Entregable__c.object-meta.xml
<CustomObject>
    <label>Grupo de Entregables</label>
    <nameField>
        <label>Nombre de Grupo de Entregables</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos de Entregables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Entregable__c/fields/Avance_Total_Mes__c.field-meta.xml
<CustomField>
    <fullName>Avance_Total_Mes__c</fullName>
    <description>Guarda el campo Avance Total Mes cuando se actualizan los datos económicos del Proyecto de forma mensual.</description>
    <label>Avance Total Mes</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Entregable__c/fields/AvanceTotal__c.field-meta.xml
<CustomField>
    <fullName>AvanceTotal__c</fullName>
    <formula>Avance_Producci_n__c * Hito__r.Peso_Facturacion__c * Peso_Entregable__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Avance * Peso del hito de facturación en el total del contrato * Peso del entregable en el hito de facturación</inlineHelpText>
    <label>Avance Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Entregable__c/fields/Entregable__c.field-meta.xml
<CustomField>
    <fullName>Entregable__c</fullName>
    <externalId>true</externalId>
    <label>Código Grupo de Entregables</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Entregable__c/fields/Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Proyecto__c</fullName>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipName>Entregables</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proyecto__c/Proyecto__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre del Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proyecto__c/fields/Entregable__c.field-meta.xml
<CustomField>
    <fullName>Entregable__c</fullName>
    <formula>Entregables__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entregables</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ActualizaAvanceTecnico.cls
global class ActualizaAvanceTecnico implements Schedulable{    
    
    global void execute(SchedulableContext SC) {
        
        Proyecto__c[] proyectos = [select id from Proyecto__c];
        List<Id> proyIds = new List<Id>();
        for(Proyecto__c p : proyectos){
            proyIds.add(p.Id);
        } 
        Entregable__c[] grupoEntregables = [select id, AvanceTotal__c, Avance_Total_Mes__c from Entregable__c where Proyecto__c IN :proyIds];
        for(Entregable__c e : grupoEntregables){
            e.Avance_Total_Mes__c = e.AvanceTotal__c;
        }
        update grupoEntregables;
        
    }
    
}