force-app/main/default/objects/Entregable__c/Entregable__c.object-meta.xml
<CustomObject>
    <label>Grupo de Entregables</label>
    <nameField>
        <label>Nombre de Grupo de Entregables</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos de Entregables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Entregable__c/fields/Entregable__c.field-meta.xml
<CustomField>
    <fullName>Entregable__c</fullName>
    <externalId>true</externalId>
    <label>Código Grupo de Entregables</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Entregable__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <formula>IF(N_mero_Entregables__c == Entregables_liberados__c , &apos;Liberado&apos;, IF( N_mero_Entregables__c ==  Entregables_Aceptados__c, &apos;Firmado&apos;, &apos;Pendiente&apos;) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estado OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entregable__c/fields/Fase__c.field-meta.xml
<CustomField>
    <fullName>Fase__c</fullName>
    <label>Fase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Preparación</fullName>
                <label>1 - Preparación Inicial</label>
            </value>
            <value>
                <fullName>Diseño</fullName>
                <label>2 - Diseño</label>
            </value>
            <value>
                <fullName>Construcción</fullName>
                <label>3 - Construcción</label>
            </value>
            <value>
                <fullName>Pruebas</fullName>
                <label>4 - Pruebas</label>
            </value>
            <value>
                <fullName>Preparación Final</fullName>
                <label>5 - Preparación Final</label>
            </value>
            <value>
                <fullName>Go Live y Soporte</fullName>
                <label>6 - Go Live y Soporte</label>
            </value>
            <value>
                <fullName>Garantía</fullName>
                <label>7 - Garantía</label>
            </value>
            <value>
                <fullName>8 - Todas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Entregable__c/fields/Hito__c.field-meta.xml
<CustomField>
    <fullName>Hito__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Hito</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Proyecto__c</field>
            <operation>equals</operation>
            <valueField>Hito__c.Proyecto__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Hito__c</referenceTo>
    <relationshipLabel>Grupos de Entregables</relationshipLabel>
    <relationshipName>Grupos_de_Entregables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entregable__c/fields/Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Proyecto__c</fullName>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipName>Entregables</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Entregable__c/fields/Subtipo__c.field-meta.xml
<CustomField>
    <fullName>Subtipo__c</fullName>
    <label>Subtipo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tipo__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Subtipo_Entregable</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Entregable__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_Entregable</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hito__c/Hito__c.object-meta.xml
<CustomObject>
    <label>Hito</label>
    <nameField>
        <label>Nombre de Hito</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hitos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Hito__c/fields/Fecha_Fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Fin__c</fullName>
    <description>Fecha Contractual de Fin</description>
    <label>Fecha Real</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Hito__c/fields/Peso_Facturacion__c.field-meta.xml
<CustomField>
    <fullName>Peso_Facturacion__c</fullName>
    <description>Porcentaje del hito en la facturación.</description>
    <label>Peso Facturación</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Hito__c/fields/Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Proyecto__c</fullName>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Hitos</relationshipLabel>
    <relationshipName>Hitos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proyecto__c/Proyecto__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre del Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proyecto__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Código de Proyecto</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Proyecto__c/fields/Documentalista__c.field-meta.xml
<CustomField>
    <fullName>Documentalista__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Documentalista</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ProyectosDocumentalistas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proyecto__c/fields/Entregable__c.field-meta.xml
<CustomField>
    <fullName>Entregable__c</fullName>
    <formula>Entregables__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entregables</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subentregable__c/Subentregable__c.object-meta.xml
<CustomObject>
    <label>Entregable</label>
    <nameField>
        <label>Nombre de Entregables</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entregables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subentregable__c/fields/AprobadorFinal__c.field-meta.xml
<CustomField>
    <fullName>AprobadorFinal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Normalmente el cliente. Una vez aprobado pasa a Firmado.</inlineHelpText>
    <label>Aprobador Final</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EntregablesFirmar</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subentregable__c/fields/AprobadorN1__c.field-meta.xml
<CustomField>
    <fullName>AprobadorN1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Normalmente el cliente. Una vez aprobado pasa al Aprobador Final</inlineHelpText>
    <label>Aprobador Nivel 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EntregablesSupervisados</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subentregable__c/fields/Avance__c.field-meta.xml
<CustomField>
    <fullName>Avance__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Avance</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Subentregable__c/fields/CodigoSubentregable__c.field-meta.xml
<CustomField>
    <fullName>CodigoSubentregable__c</fullName>
    <externalId>true</externalId>
    <label>Código Entregable</label>
    <length>35</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Subentregable__c/fields/Descripciom__c.field-meta.xml
<CustomField>
    <fullName>Descripciom__c</fullName>
    <label>Descripción</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Subentregable__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estado_Entregables</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subentregable__c/fields/Fecha_Limite_de_inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Limite_de_inicio__c</fullName>
    <description>Fecha en la cual se debe iniciar la elaboración de los soportes de cada entregable, este campo servirá para establecer una fecha en la cual se pueda asignar cada entregable a su responsable</description>
    <label>Fecha Inicio Plan</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subentregable__c/fields/Hito__c.field-meta.xml
<CustomField>
    <fullName>Hito__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hito</label>
    <referenceTo>Hito__c</referenceTo>
    <relationshipLabel>Entregables</relationshipLabel>
    <relationshipName>Entregables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subentregable__c/fields/Peso__c.field-meta.xml
<CustomField>
    <fullName>Peso__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Peso</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Subentregable__c/fields/Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Proyecto__c</fullName>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Entregables</relationshipLabel>
    <relationshipName>Entregables1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subentregable__c/fields/ResponsableN1__c.field-meta.xml
<CustomField>
    <fullName>ResponsableN1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable Nivel 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EntregablesResponsable</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subentregable__c/fields/ResponsableN2__c.field-meta.xml
<CustomField>
    <fullName>ResponsableN2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable Nivel 2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Entregables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subentregable__c/fields/Subtipo__c.field-meta.xml
<CustomField>
    <fullName>Subtipo__c</fullName>
    <label>Subtipo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tipo__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Subtipo_Entregable</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subentregable__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_Entregable</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Estado_Entregables.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cancelado</fullName>
    </customValue>
    <customValue>
        <fullName>Pendiente</fullName>
        <default>true</default>
        <label>Pendiente</label>
    </customValue>
    <customValue>
        <fullName>En proceso</fullName>
    </customValue>
    <customValue>
        <fullName>En Revisión Interna</fullName>
    </customValue>
    <customValue>
        <fullName>Finalizado</fullName>
    </customValue>
    <customValue>
        <fullName>Liberado</fullName>
    </customValue>
    <customValue>
        <fullName>Firmado</fullName>
    </customValue>
    <customValue>
        <fullName>Pendiente de Firma</fullName>
        <isActive>false</isActive>
        <label>Pendiente de Firma</label>
    </customValue>
    <customValue>
        <fullName>En desarrollo</fullName>
        <isActive>false</isActive>
        <label>En desarrollo</label>
    </customValue>
    <masterLabel>Estado Entregables</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Subtipo_Entregable.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Otros</fullName>
    </customValue>
    <masterLabel>Subtipo Entregable</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tipo_Entregable.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Arquitectura</fullName>
    </customValue>
    <customValue>
        <fullName>Diseño Funcional</fullName>
    </customValue>
    <customValue>
        <fullName>Diseño Técnico</fullName>
    </customValue>
    <customValue>
        <fullName>Formación</fullName>
    </customValue>
    <customValue>
        <fullName>Gestión del Cambio</fullName>
    </customValue>
    <customValue>
        <fullName>Gestión del Proyecto</fullName>
    </customValue>
    <customValue>
        <fullName>Interfaces</fullName>
    </customValue>
    <customValue>
        <fullName>Licenciamiento</fullName>
    </customValue>
    <customValue>
        <fullName>Metodología</fullName>
    </customValue>
    <customValue>
        <fullName>Migración</fullName>
    </customValue>
    <customValue>
        <fullName>Otros</fullName>
    </customValue>
    <customValue>
        <fullName>Pruebas</fullName>
    </customValue>
    <customValue>
        <fullName>Garantía, Soporte y Mantenimiento</fullName>
    </customValue>
    <customValue>
        <fullName>Puesta en Producción</fullName>
    </customValue>
    <masterLabel>Tipo Entregable</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Submit_ApprovarControlador_Test.cls
@isTest (SeeAllData = false)
public class Submit_ApprovarControlador_Test {
  @testSetup 
    static void setup() { 
      //  Profile profileId = [SELECT Id FROM Profile WHERE Name='System Administrator' LIMIT 1];
      //  UserRole uRole = [SELECT Id FROM UserRole WHERE Name ='Supervision' LIMIT 1];
       
        id userid = Userinfo.getUserId();
        //User user1 = [SELECT Id FROM User WHERE Id = userid LIMIT 1];
        //User user1 = new User(LastName = 'test1',FirstName='test1',Alias = 'uT1',Email = 'user1Test@test.com',Username = 'user1Test' + Datetime.now().getTime() + '@test.com',ProfileId = profileId.Id,UserRoleId = uRole.id,TimeZoneSidKey = 'America/Lima', LanguageLocaleKey = 'en_US', EmailEncodingKey = 'UTF-8',LocaleSidKey = 'en_US');
        //insert user1;
        //System.runAs ( user1 ) {
            Proyecto__c proyecto = new Proyecto__c(Name = 'Proyecto Test', Codigo__c = 'Proyecto-001', Documentalista__c = userid);
            insert proyecto;
            Hito__c hito = new Hito__c(Name = 'Hito', Proyecto__c = proyecto.Id, Fecha_Fin__c = Date.newInstance(2018, 12, 17), Peso_Facturacion__c = 20 );
            insert hito;
            Entregable__c entr = new Entregable__c(Name = 'Ent', Proyecto__c = proyecto.Id, Hito__c = hito.Id, Entregable__c = 'Ent', Tipo__c = 'Otros', Fase__c = 'Pruebas');
            insert entr;
            Entregable__c entr2 = new Entregable__c(Name = 'Ent2', Proyecto__c = proyecto.Id, Hito__c = hito.Id, Entregable__c = 'Ent2', Tipo__c = 'Otros', Fase__c = 'Pruebas');
            insert entr2;
            Subentregable__c sub= new Subentregable__c(Name= 'Sub1',Proyecto__c=proyecto.Id,CodigoSubentregable__c='Sub1',Descripciom__c='Sub1',Estado__c='Pendiente',ResponsableN1__c=userid,ResponsableN2__c=userid,AprobadorN1__c=userid,AprobadorFinal__c=userid, Fecha_Limite_de_inicio__c= date.today(), Tipo__c='Otros',Subtipo__c='Otros', Avance__c=0,	Peso__c=0);
 			insert sub;	
        	Subentregable__c sub2= new Subentregable__c(Name= 'Sub2',Proyecto__c=proyecto.Id,CodigoSubentregable__c='Sub2',Descripciom__c='Sub2',Estado__c='Pendiente',ResponsableN1__c=userid,ResponsableN2__c=userid,AprobadorN1__c=userid,AprobadorFinal__c=userid, Fecha_Limite_de_inicio__c= date.today(), Tipo__c='Otros',Subtipo__c='Otros', Avance__c=0, Peso__c=0);
			insert sub2;
			           
       // } 
    }
    
        static TestMethod void Submit_ApprovarControlador(){
            Test.startTest(); 
            Proyecto__c nameProyecto= [SELECT Id FROM Proyecto__c WHERE Name ='Proyecto Test' LIMIT 1]; 
            Submit_ApprovarControlador.processPoject(nameProyecto.Id);
   			Test.stopTest();
        }
    
       
    
}