force-app/main/default/objects/Entregable__c/Entregable__c.object-meta.xml
<CustomObject>
    <label>Grupo de Entregables</label>
    <nameField>
        <label>Nombre de Grupo de Entregables</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos de Entregables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Entregable__c/fields/AvanceContractual__c.field-meta.xml
<CustomField>
    <fullName>AvanceContractual__c</fullName>
    <formula>Entregables_Aceptados__c / N_mero_Entregables__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Número de Subentregables Firmados / Total de Subentregables</inlineHelpText>
    <label>Avance Contractual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Entregable__c/fields/Cerrado__c.field-meta.xml
<CustomField>
    <fullName>Cerrado__c</fullName>
    <formula>Estado__c = &apos;Firmado&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Se marca automáticamente cuando el entregable está en estado Aprobado.</inlineHelpText>
    <label>Cerrado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Entregable__c/fields/Entregable__c.field-meta.xml
<CustomField>
    <fullName>Entregable__c</fullName>
    <externalId>true</externalId>
    <label>Código Grupo de Entregables</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Entregable__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <formula>IF(N_mero_Entregables__c == Entregables_liberados__c , &apos;Liberado&apos;, IF( N_mero_Entregables__c ==  Entregables_Aceptados__c, &apos;Firmado&apos;, &apos;Pendiente&apos;) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estado OLD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entregable__c/fields/Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Proyecto__c</fullName>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipName>Entregables</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proyecto__c/Proyecto__c.object-meta.xml
<CustomObject>
    <label>Proyecto</label>
    <nameField>
        <label>Nombre del Proyecto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proyectos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proyecto__c/fields/Entregable__c.field-meta.xml
<CustomField>
    <fullName>Entregable__c</fullName>
    <formula>Entregables__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entregables</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subentregable__c/Subentregable__c.object-meta.xml
<CustomObject>
    <label>Entregable</label>
    <nameField>
        <label>Nombre de Entregables</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entregables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subentregable__c/fields/Cerrado__c.field-meta.xml
<CustomField>
    <fullName>Cerrado__c</fullName>
    <formula>ISPICKVAL(Estado__c, &apos;Firmado&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cerrado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subentregable__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estado_Entregables</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subentregable__c/fields/Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Proyecto__c</fullName>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Entregables</relationshipLabel>
    <relationshipName>Entregables1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TDRSubentregable__c/TDRSubentregable__c.object-meta.xml
<CustomObject>
    <label>Relación Entregable con TDR</label>
    <nameField>
        <displayFormat>TDRSUB-{0000000}</displayFormat>
        <label>Código TDR-ENT</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relaciones Entregables con TDRs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TDRSubentregable__c/fields/Entregable__c.field-meta.xml
<CustomField>
    <fullName>Entregable__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo de Entregables</label>
    <referenceTo>Entregable__c</referenceTo>
    <relationshipLabel>Relaciones Grupo de Entregables con TDRs</relationshipLabel>
    <relationshipName>TDRsEntregables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TDRSubentregable__c/fields/Subentregable__c.field-meta.xml
<CustomField>
    <fullName>Subentregable__c</fullName>
    <label>Entregable</label>
    <referenceTo>Subentregable__c</referenceTo>
    <relationshipLabel>Relaciones Entregables con TDR</relationshipLabel>
    <relationshipName>TDRsEntregables</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TDRSubentregable__c/fields/TerminoReferencia__c.field-meta.xml
<CustomField>
    <fullName>TerminoReferencia__c</fullName>
    <label>Término de Referencia</label>
    <referenceTo>Termino_de_Referencia__c</referenceTo>
    <relationshipName>TDRsEntregables</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Termino_de_Referencia__c/Termino_de_Referencia__c.object-meta.xml
<CustomObject>
    <label>Término de Referencia</label>
    <nameField>
        <label>Código TDR</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Términos de Referencia</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Termino_de_Referencia__c/fields/Cerrado__c.field-meta.xml
<CustomField>
    <fullName>Cerrado__c</fullName>
    <formula>TEXT(Estado__c) = &apos;Aprobado&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Automatically checked when status is accepted</inlineHelpText>
    <label>Cerrado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Termino_de_Referencia__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
                <default>true</default>
                <label>Pendiente</label>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Termino_de_Referencia__c/fields/Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Proyecto__c</fullName>
    <label>Proyecto</label>
    <referenceTo>Proyecto__c</referenceTo>
    <relationshipLabel>Términos de Referencia</relationshipLabel>
    <relationshipName>Terminos_de_Referencia</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Estado_Entregables.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cancelado</fullName>
    </customValue>
    <customValue>
        <fullName>Pendiente</fullName>
        <default>true</default>
        <label>Pendiente</label>
    </customValue>
    <customValue>
        <fullName>En proceso</fullName>
    </customValue>
    <customValue>
        <fullName>En Revisión Interna</fullName>
    </customValue>
    <customValue>
        <fullName>Finalizado</fullName>
    </customValue>
    <customValue>
        <fullName>Liberado</fullName>
    </customValue>
    <customValue>
        <fullName>Firmado</fullName>
    </customValue>
    <customValue>
        <fullName>Pendiente de Firma</fullName>
        <isActive>false</isActive>
        <label>Pendiente de Firma</label>
    </customValue>
    <customValue>
        <fullName>En desarrollo</fullName>
        <isActive>false</isActive>
        <label>En desarrollo</label>
    </customValue>
    <masterLabel>Estado Entregables</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AyesaSyncCore.cls
public class AyesaSyncCore {
    
    private static string sOpen = 'Pendiente', sClosed = 'Aprobado';
    //private static string ePending = 'Pendiente', eDev ='En desarrollo', eFree = 'Liberado', eClosed = 'Firmado';
   
    public static void processTDRS(List<ID> tdrIds){
        // Se sincronizan los estados de los TDR's asociados a los subentregables     +
        
        Termino_de_Referencia__c tmpTdr;
        List<Termino_de_Referencia__c> finalTdrs = new List<Termino_de_Referencia__c>();
        List<AggregateResult> openTdrs = [select terminoreferencia__c, count(subentregable__r.Id) open from TDRSubentregable__c where subentregable__r.cerrado__c = false and terminoreferencia__c in :tdrIds group by terminoreferencia__c];   
        for(AggregateResult tdr : openTdrs){
            tmpTdr = new Termino_de_Referencia__c();
            tmpTdr.Id = (Id)tdr.get('TerminoReferencia__c');
            tmpTdr.estado__c = AyesaSyncCore.sOpen;
            tdrIds.remove(tdrIds.indexOf(tmpTdr.Id));       
            finalTdrs.add(tmpTdr);
        }
        
        List<Termino_de_Referencia__c> closedTdrs = [select id from Termino_de_Referencia__c where id in (select terminoreferencia__c from TDRSubentregable__c where terminoreferencia__c in:tdrIds)];       
        for(Termino_de_Referencia__c tdr : closedTdrs){   
            tdr.estado__c = AyesaSyncCore.sClosed;
            finalTdrs.add(tdr);
        }
        
        List<Termino_de_Referencia__c> uncoveredTdrs = [select id from Termino_de_Referencia__c where id in :tdrids and id not in (select terminoreferencia__c from TDRSubentregable__c where terminoreferencia__c in:tdrIds)];       
        for(Termino_de_Referencia__c tdr : uncoveredTdrs){   
            tdr.estado__c = AyesaSyncCore.sOpen;
            finalTdrs.add(tdr);
        }
        
        Map<Id, Termino_de_Referencia__c> mapTdr = new Map<Id, Termino_de_Referencia__c>();
        mapTdr.putAll(finalTdrs);
        update mapTdr.values();
        
    }
    
    
    @AuraEnabled
    public static void processPoject(ID project){
        List<Termino_de_Referencia__c> tdrs = [SELECT id from Termino_de_Referencia__c where proyecto__c = :project];
        List<Id> ids = new List<ID>();
        for(Termino_de_Referencia__c tdr : tdrs){
            ids.add(tdr.Id);
        }
        AyesaSyncCore.processTDRS(ids);
    
    }
    
 /*   public static void processSubentregables (List<Id> lSubs){
        // Se sincroniza el estado de los entregables asociados.
        List<Entregable__c> lEnt2Update = new List<Entregable__c>();
        
        List<Subentregable__c> subsToProcess = [select id, entregable__r.cerrado__c, entregable__r.AvanceContractual__c, entregable__r.NumeroSubentregables__c, entregable__r.Subentregables_Liberados__c from Subentregable__c where entregable__c in :lSubs];
        Entregable__c tmpEnt;
        
        for(Subentregable__c sub: subsToProcess){
            tmpEnt = sub.entregable__r;
            if(!tmpEnt.cerrado__c && tmpEnt.AvanceContractual__c == 1){
                tmpEnt.estado__c = AyesaSyncCore.eClosed;
                lEnt2Update.add(tmpEnt);
            } else if (tmpEnt.NumeroSubentregables__c == tmpEnt.Subentregables_Liberados__c ){
                tmpEnt.estado__c = AyesaSyncCore.eFree;
                lEnt2Update.add(tmpEnt);
            } else if ( tmpEnt.NumeroSubentregables__c != tmpEnt.Subentregables_Liberados__c  &&  tmpEnt.AvanceContractual__c < 1){
                tmpEnt.estado__c = AyesaSyncCore.sOpen;
                lEnt2Update.add(tmpEnt);
            }
        }
        
        update lEnt2Update;
    }*/
    
    
}