force-app/main/default/objects/CRM_Ibermatica_Configuration__c/CRM_Ibermatica_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CRM Ibermatica Configuration</label>
</CustomObject>

force-app/main/default/objects/CRM_Ibermatica_Configuration__c/fields/URL_Preventa__c.field-meta.xml
<CustomField>
    <fullName>URL_Preventa__c</fullName>
    <label>URL Preventa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/No_ejecutar_triggers__c/No_ejecutar_triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>No ejecutar triggers</label>
</CustomObject>

force-app/main/default/objects/No_ejecutar_triggers__c/fields/Correo_usuario__c.field-meta.xml
<CustomField>
    <fullName>Correo_usuario__c</fullName>
    <label>Correo usuario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Ayesa.recordType-meta.xml
<RecordType>
    <fullName>Ayesa</fullName>
    <active>true</active>
    <businessProcess>Ayesa</businessProcess>
    <label>Ayesa</label>
</RecordType>

force-app/main/default/objects/Parametrica_2__c/Parametrica_2__c.object-meta.xml
<CustomObject>
    <description>Parametrica que contiene los datos de Ibermatica</description>
    <label>Parametrica Ibermática</label>
    <nameField>
        <label>Nombre de Parametrica Ibermática</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parametricas Ibermática</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parametrica_2__c/fields/Centro_Res_Super_lookup__c.field-meta.xml
<CustomField>
    <fullName>Centro_Res_Super_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centro Responsabilidad Super</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Parametrica_2__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Centro Responsabilidad</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Parametrica_2__c</referenceTo>
    <relationshipLabel>Parametricas Ibermática (Centro Responsabilidad Super)</relationshipLabel>
    <relationshipName>CR_lookup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Centro_resp_Super__c.field-meta.xml
<CustomField>
    <fullName>Centro_resp_Super__c</fullName>
    <label>Centro resp. Super</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Codigo_CR__c.field-meta.xml
<CustomField>
    <fullName>Codigo_CR__c</fullName>
    <label>Codigo CR</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Codigo_Gestor_Produccion__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Gestor_Produccion__c</fullName>
    <label>Codigo Gestor Produccion</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/CR_Importe_OCP__c.field-meta.xml
<CustomField>
    <fullName>CR_Importe_OCP__c</fullName>
    <label>CR Importe OCP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Desglose_importes__c.field-meta.xml
<CustomField>
    <fullName>Desglose_importes__c</fullName>
    <inlineHelpText>Opciones: Sí / No</inlineHelpText>
    <label>Desglose importes</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>Activo</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>Inactivo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/FICEPI__c.field-meta.xml
<CustomField>
    <fullName>FICEPI__c</fullName>
    <label>FICEPI</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Gestor_de_produccion__c.field-meta.xml
<CustomField>
    <fullName>Gestor_de_produccion__c</fullName>
    <label>Gestor de produccion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Gestor_de_produccion_lookup__c.field-meta.xml
<CustomField>
    <fullName>Gestor_de_produccion_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gestor de produccion</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Parametrica_2__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Gestor Produccion</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Parametrica_2__c</referenceTo>
    <relationshipLabel>Parametricas Ibermática (Gestor de produccion)</relationshipLabel>
    <relationshipName>Gestor_de_produccion_lookup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/fields/Horizontal__c.field-meta.xml
<CustomField>
    <fullName>Horizontal__c</fullName>
    <label>Horizontal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parametrica_2__c/recordTypes/Gestor_Produccion.recordType-meta.xml
<RecordType>
    <fullName>Gestor_Produccion</fullName>
    <active>true</active>
    <label>Gestor Produccion</label>
</RecordType>

force-app/main/default/classes/CRM_CentroResponsabilidad_Test.cls
@IsTest
public class CRM_CentroResponsabilidad_Test {
    
    @testSetup
    static void seed() {
        
        insert new No_ejecutar_triggers__c(
            Correo_usuario__c = 'soporteoaci@ayesa.com'
        );
        
        Parametrica_2__c cr = TestDataFactory.createParam2(
            'Centro Responsabilidad',
            new Map<String,Object>{
                'Name'                 => 'CR-Test',
                    'Centro_resp_Super__c' => 'CENTRO PRUEBA',
                    'Codigo_CR__c'         => '015',
                    'Horizontal__c'        => 'Digital impact',
                    'Desglose_importes__c' => 'No',
                    'CR_Importe_OCP__c'    => 1000,
                    'Estado__c'            => '1'
                    });
        
        Parametrica_2__c gp = TestDataFactory.createParam2(
            'Gestor Produccion',
            new Map<String,Object>{
                'Name'                        => 'GP-Test',
                    'Gestor_de_produccion__c'     => 'USUARIO GP TEST',
                    'Codigo_Gestor_Produccion__c' => '999',
                    'FICEPI__c'                   => 'F999',
                    'Estado__c'                   => '1'
                    });
        
        TestDataFactory.createParam2(
            'Gestor Produccion - Centro Responsabilidad',
            new Map<String,Object>{
                'Name'                           => 'Rel-CR-GP',
                    'Centro_Res_Super_lookup__c'     => cr.Id,
                    'Gestor_de_produccion_lookup__c' => gp.Id,
                    'Estado__c'                      => '1'
                    });
        
        TestDataFactory.createOpportunity('Cualificación', 'Digital impact');
        
        upsert new CRM_Ibermatica_Configuration__c(
            SetupOwnerId    = UserInfo.getOrganizationId(),
            URL_Preventa__c = 'https://dummy/preventa'
        );
    }
    
    private static Opportunity opp() {
        return [SELECT Id FROM Opportunity WHERE Name = 'Opp-Test' LIMIT 1];
    }
    private static String etiquetaCR() {
        Parametrica_2__c c = [
            SELECT Centro_resp_Super__c, Codigo_CR__c
            FROM   Parametrica_2__c
            WHERE  RecordType.Name = 'Centro Responsabilidad'
            LIMIT  1
        ];
        return c.Centro_resp_Super__c + ' -- ' + c.Codigo_CR__c;
    }
    private static String nombreGP() {
        return [SELECT Gestor_de_produccion__c
                FROM   Parametrica_2__c
                WHERE  RecordType.Name = 'Gestor Produccion'
                LIMIT  1]
            .Gestor_de_produccion__c;
    }
    
    @IsTest static void testInicio() {
        Test.startTest();
        String json = CRM_CentroResponsabilidad.inicio(opp().Id);
        Test.stopTest();
        System.assertNotEquals(null, json, 'inicio() debe devolver JSON');
    }
    
    @IsTest static void testGestorProduccion() {
        Test.startTest();
        List<String> lista = CRM_CentroResponsabilidad.gestor_produccion(etiquetaCR());
        Test.stopTest();
        System.assertEquals(
            new List<String>{ nombreGP() },
            lista,
            'gestor_produccion() no devolvió el GP esperado');
    }
    
    @IsTest static void testSaveOpp() {
        Test.startTest();
        String res = CRM_CentroResponsabilidad.saveOpp(etiquetaCR(), nombreGP(), opp().Id);
        Test.stopTest();
        System.assertEquals('Actualizado', res);
    }
    
    @IsTest static void testSuperPreventa() {
        Test.startTest();
        String url = CRM_CentroResponsabilidad.superPreventa(opp().Id);
        Test.stopTest();
        System.assert(
            url.startsWith('https://dummy/preventa'),
            'superPreventa() generó URL inesperada');
    }
    
    @IsTest static void testReadOnlyCR() {
        Test.startTest();
        Boolean readOnly = CRM_CentroResponsabilidad.readOnlyCR(opp().Id);
        Test.stopTest();
        System.assertEquals(false, readOnly,
                            'readOnlyCR() debería devolver FALSE');
    }
}